### ISSUE TITLE
Erro no envio de áudio

### ISSUE THREAD

**Issue by DjotaHasse** [wppconnect-team/wa-js#1002]
Ao tentar enviar áudio com a função SenFileMessageEx, o console retorna um warning e não envia o áudio.

![WhatsApp Image 2023-03-24 at 14 15 29](https://user-images.githubusercontent.com/54808117/227614182-183b3393-b8dd-433d-88d8-425aa9ccf741.jpeg)

**Comment by edgardmessias** [comment]
Isso é apenas um warning, pela mensagem, o problema é por causa de não ter tido nenhuma interação na página, na qual o chrome bloqueia as APIs de áudio., você pode usar a flag `--autoplay-policy=no-user-gesture-required` para ignorar isso.

Sobre o áudio não enviar, é bom realizar mais testes por garantia.

Caso continue o problema de não enviar, reabrir a issue.
