### ISSUE TITLE
How to get a profile name for any wid?

### ISSUE THREAD

**Issue by Gethin0321** [wppconnect-team/wa-js#1012]
Hi,If I have a wid, which function should I call to obtain the profile name of this wid?

**Comment by vphelipe** [comment]
WPP.whatsapp.ContactStore.get('[number]@c.us').displayName 

or

WPP.whatsapp.ContactStore.get('556182615929@c.us').notifyName

**Comment by edgardmessias** [comment]
`WPP.whatsapp.ContactStore.get` is the pure way to do that, but I will create a wrap  like `WPP.contact.get`
