### ISSUE TITLE
This message will not disappear from the chat. The sender may be on an old version of WhatsApp.

### ISSUE THREAD

**Issue by rhutikcodes** [wppconnect-team/wa-js#1014]
## Description
I am getting this message on my phone when sending a message to groups that have disappearing messages turned on. 
This message will not disappear from the chat. The sender may be on an old version of WhatsApp.

## Environment

- **WhatsApp version:** 2.2314.7
- **WA-JS version(s):** [2.22.3-alpha.0](https://github.com/wppconnect-team/wa-js/compare/v2.22.2...v2.22.3-alpha.0)
- **Browser:** Chrome 111.0.5563.146
- **OS:** Mac 13.2.1
## Steps to Reproduce

1. Turn on disappearing message on group
2. send text message await WPP.chat.sendTextMessage("1629364913@g.us","hi")

## Your Code

```
await WPP.chat.sendTextMessage("1629364913@g.us","hi")
```

## Additional context / Screenshot
![image](https://user-images.githubusercontent.com/46106467/229274321-7fa1ba5d-b01f-4c75-8c1c-4cb5e5b0d6f3.png)

@edgardmessias Can you please look into this

**Comment by rhutikcodes** [comment]
@edgardmessias 👋 Hi

**Comment by icleitoncosta** [comment]
I believe when send message to a group, and this group have contacts with whatsapp in versions not updated, do you receive this message. In my opinion, this is a "error" of whatsapp itself.
