### ISSUE TITLE
Button Messages not send

### ISSUE THREAD

**Issue by vishwajit76** [wppconnect-team/wa-js#1024]
I tested your recent release but button messages not send from normal WhatsApp account.

![image](https://user-images.githubusercontent.com/25575802/229435112-de190434-1169-4998-9bb6-120d3ffc6a9a.png)

**Comment by veracity-ind** [comment]
For me also not working. it goes to waiting sign.

<img width="485" alt="Screenshot 2023-04-03 at 14 36 59" src="https://user-images.githubusercontent.com/107061774/229464415-d7b4b918-e143-4b3d-9a92-177729ed2a9e.png">

**Comment by raajrush** [comment]
![IMG-20230403-WA0000](https://user-images.githubusercontent.com/54767677/229484491-e53510a9-e957-4164-9da2-0e03750c91f8.jpg)

Same here

**Comment by jaydeep9246** [comment]
![Image](https://github.com/user-attachments/assets/593e950b-21f0-4cd5-aa94-721c3d1492c3)
someone can send image + button, I received it on my number , but that message cant show in web WhatsApp, anyone know which method they use to send button?
