### ISSUE TITLE
Problem sending status with image/video

### ISSUE THREAD

**Issue by vphelipe** [wppconnect-team/wa-js#1035]
## Description

Sending status with image/video is not working. Studying the reason here, I verified that the message is going correctly with all the media data (directPath, deprecatedMms3Url, filehash...), but when checking the status, it does not have this data, just the body with the base64 of the image. I tried some alternatives like: uploading the file and forcing the sending of this data, but it dont work. Sending in groups and privately works normally, only status@broadcast does not. For contacts, the status appears only on whatsapp web, but it does not load, it keeps loading forever and nothing happens, according to print. In some cases it caused the iphone to crash.

## Environment

![Screenshot (1)](https://user-images.githubusercontent.com/32254362/230726168-cca028ae-fce8-4785-9426-e9ecf6073a88.png)

![Screenshot (2)](https://user-images.githubusercontent.com/32254362/230726196-18eb2102-8419-4a94-b5f7-823ccb623f2f.png)

- **WhatsApp version:** 2.2315.6
- **WA-JS version(s):** 2.23.1
- **Browser:** Chrome Versão 112.0.5615.49 (Versão oficial) 64 bits
- **OS:** Windows 11
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. Send status with image/video

**Comment by amiruldev20** [comment]
@edgardmessias  same problem
