### ISSUE TITLE
button template message can only be displayed on the web page

### ISSUE THREAD

**Issue by ionictemplate-app** [wppconnect-team/wa-js#1060]
The button template message can only be displayed on the web page, android cannot display any information

## Environment

- **WhatsApp version:** last
- **WA-JS version(s):** last
 
- **MultiDevice (BETA):** yes/no

**Comment by estopassoli** [comment]
Estou tendo o mesmo problema, os botões aparecem apenas no Web WhatsApp

**Comment by renat473** [comment]
deprecated
