### ISSUE TITLE
TypeError: P.PHOTO_PICKER_QUALIFIED_EMOJIS is not iterable

### ISSUE THREAD

**Issue by yuzedong** [wppconnect-team/wa-js#1061]
## Description

I imported wa.js in my Chrome extension. When a user clicks on the three-dot button in the top right corner of a group chat in web.whatsapp.com, the group info does not show up and an error is reported in the console. The error is as follows:

TypeError: P.PHOTO_PICKER_QUALIFIED_EMOJIS is not iterable
at t.default (lazy_loaded_low_priority_components.2eb74f3a79d43c7a730d.js:2:295311)
at wa (vendor1~app.93f2846fd0de96e2ec08.js:30:62964)
at _u (vendor1~app.93f2846fd0de96e2ec08.js:30:120158)
at vl (vendor1~app.93f2846fd0de96e2ec08.js:30:109100)
at pl (vendor1~app.93f2846fd0de96e2ec08.js:30:109028)
at hl (vendor1~app.93f2846fd0de96e2ec08.js:30:108891)
at nl (vendor1~app.93f2846fd0de96e2ec08.js:30:105698)
at ol (vendor1~app.93f2846fd0de96e2ec08.js:30:106087)
at Fi (vendor1~app.93f2846fd0de96e2ec08.js:30:46805)
at vendor1~app.93f2846fd0de96e2ec08.js:30:103606

![WX20230418-100956@2x](https://user-images.githubusercontent.com/6629143/232652157-b6411c68-d7fc-48b9-b0a4-5d70a7c84a96.png)

## Environment

- **WA-JS version(s): 2.23.3
- **Browser:** Chrome 111
- **OS:** Windows X / OSX 

## Steps to Reproduce

1. Inject wppconnect-wa.js.
2. Click on a specific group on web.whatsapp.com.
3. Click on the More (three-dot) icon at the top right corner and select the first group info option.
4. An error is reported in the console.

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by yuzedong** [comment]
Please take a look for me, and thank you very much!

**Comment by edgardmessias** [comment]
@yuzedong what is the WhatsApp version?

**Comment by yuzedong** [comment]
2.2316.6

**Comment by luiscuriel** [comment]
I fixed it by injecting the js later, after authentication is ok.

**Comment by edgardmessias** [comment]
Thanks @luiscuriel , I will try to reproduce it on my machine and try to figure out a way to avoid this

**Comment by yuzedong** [comment]
> Thanks @luiscuriel , I will try to reproduce it on my machine and try to figure out a way to avoid this

When can this issue be fixed? tks.

**Comment by luiscuriel** [comment]
It is still happening on some sessions for me...

**Comment by yuzedong** [comment]
Ok, Please fix it as soon as possible. Thanks!

**Comment by yuzedong** [comment]
I'm using the latest version 2.24.0, and the process remains the same as before. The previous console error has disappeared, but a new error has occurred. The error is as follows:
![WX20230506-102925@2x](https://user-images.githubusercontent.com/6629143/236593978-bead537b-fb6e-4337-a89c-45966b1ff5aa.png)
