### ISSUE TITLE
GET get-messages não trás Base64 dos ptt

### ISSUE THREAD

**Issue by pedromagnox** [wppconnect-team/wa-js#1089]
Chega o Base64 de todos os outros arquivos, menos de áudio gravado
config.ts já está autoDownload: true

É necessário fazer algo diferente para o áudio ou realmente é um bug?

ps: o mimetype do áudio está chegando

**Comment by icleitoncosta** [comment]
Pedro,tente utilizar a função downloadMedia

https://wppconnect.io/wa-js/functions/chat.downloadMedia.html
