### ISSUE TITLE
Failed to addParticipants in group

### ISSUE THREAD

**Issue by bracketsApps007** [wppconnect-team/wa-js#1114]
![image](https://github.com/wppconnect-team/wa-js/assets/110741940/04eae5fa-1463-4d43-9a86-e69801ca0cf7)

**Comment by PwccaCode** [comment]
i was able to reproduce the same problem, seems to be an issue since last whatsapp update

**Comment by edgardmessias** [comment]
Related to #1119

**Comment by edgardmessias** [comment]
I need to update the code to use another WhatsApp function, use the `addParticipants` instead of `sendAddParticipants`, because the WhatsApp is changing some attributes to work with @lid

**Comment by PwccaCode** [comment]
> I need to update the code to use another WhatsApp function, use the `addParticipants` instead of `sendAddParticipants`, because the WhatsApp is changing some attributes to work with @lid

isn't he already using addParticipants? or is there somewhere else the change has to be made?

**Comment by edgardmessias** [comment]
> isn't he already using addParticipants? or is there somewhere else the change has to be made?

It is an internal change to do.
