### ISSUE TITLE
Como forçar a sincronização de mensagens antigas?

### ISSUE THREAD

**Issue by opsJson** [wppconnect-team/wa-js#1122]
Estou fazendo uma extensão para assinar mensagens enviadas:

![image](https://github.com/wppconnect-team/wa-js/assets/54485405/0d1d9e06-6e61-4955-aa28-8c7e4665b238)

O meio que estou utilizando é esperar por uma nova mensagem com um eventListener, e editar a propriedade body da mensagem para a assinatura + body, antes dela ser enviada.

Tudo funciona bem, mas, quando o usuário da refresh na pagina, a mensagem com o conteúdo modificado some. (mesmo chegano a mensagem com assinatura para o destinatário.)

A única forma que encontrei do usuário voltar a ver a mensagem com a assinatura, é relogando, scanneando um novo QR Code, e fazendo a sincronização das mensagens antigas novamente:

![image](https://github.com/wppconnect-team/wa-js/assets/54485405/4917910b-b8c7-4504-8837-18d58658bfc5)

Gostaria de saber se tem algum jeito de realizar algumas dessas alternativas:
1. Forçar sincronização de mensagens antigas.
2. Fazer o processo de deslogar e relogar automaticamente.
3. "Dar" trigger em algum evento pro Whatsapp perceber que precisa rebaixar essa mensagem

**Comment by icleitoncosta** [comment]
Creio, que o melhor para o seu caso, seja uma função que edite essa mensagem antes dela ser enviada de uma outra forma.., 
Por exemplo, um wrapper na função que envia a mensagem, e ai você pode adicionar o que voce precisa no body da mesma, quando for texto.

**Comment by IgorRSGraziano** [comment]
> Creio, que o melhor para o seu caso, seja uma função que edite essa mensagem antes dela ser enviada de uma outra forma.., Por exemplo, um wrapper na função que envia a mensagem, e ai você pode adicionar o que voce precisa no body da mesma, quando for texto.

Tem como dar um exemplo? Esse wrapper, seria de algum método de envio, ou em cima do input nativo do WhatsApp? Pois editando a mensagem a partir do evento funciona, mas gera o problema relatado

**Comment by opsJson** [comment]
Fiz um código para editar mensagens no IndexedDB tendo como base esse site: https://mazzo.li/posts/whatsapp-backup.html

```js
let decryptArgs;
let decodeProtobuf;
let encodeProtobuf;
let MsgRowOpaqueData;

const getIndexedDB = (database, table, key) => {
	return new Promise(r => {
		const dbRequest = window.indexedDB.open(database);
		
		dbRequest.onsuccess = (event) => {
			const db = event.target.result;
			const transaction = db.transaction(table, "readonly");
			const objectStore = transaction.objectStore(table);
			const getRequest = objectStore.get(key);

			getRequest.onsuccess = (event) => {
				r(event.target.result);
			};

			getRequest.onerror = (event) => {
				r(null);
			};
		};
		
		dbRequest.onerror = (event) => {
			r(null);
		};
	});
}

const setIndexedDB = (database, table, object) => {
	return new Promise(r => {
		const dbRequest = window.indexedDB.open(database);

		dbRequest.onsuccess = (event) => {
			const db = event.target.result;
			const transaction = db.transaction(table, "readwrite");
			const objectStore = transaction.objectStore(table);
			const putRequest = objectStore.put(object);
			
			putRequest.onsuccess = (event) => {
				r(true);
			};
			putRequest.onerror = (event) => {
				r(false);
			};
		};
		
		dbRequest.onerror = (event) => {
			r(null);
		};
	});
}

const getDecryptArgs = async () => {
	return new Promise(r => {
		window.indexedDB.open("model-storage").onsuccess = (event) => {
			const db = event.target.result;
			
			db.transaction("message").objectStore("message").openCursor().onsuccess = (event) => {
				const testData = event.target.result.value.msgRowOpaqueData;
				
				const originalDecrypt = window.crypto.subtle.decrypt;
				window.crypto.subtle.decrypt = async function(algorithm, key, data) {
					try {
						await originalDecrypt.call(this, { ...algorithm, iv: testData.iv }, key, testData._data);

						window.crypto.subtle.decrypt = originalDecrypt;
						r({algorithm, key});
					}
					catch (e) {
					}
					return originalDecrypt.call(this, algorithm, key, data);
				};	
			};
		};
	});
};

const setIDBMessage = async (id, body) => {
		const IDBmessage = await getIndexedDB("model-storage", "message", id);
		
		const decryptedIDBMessage = await crypto.subtle.decrypt({
			name: decryptArgs.algorithm.name,
			iv: IDBmessage.msgRowOpaqueData.iv
		}, decryptArgs.key, IDBmessage.msgRowOpaqueData._data);
		
		const decodedIDBMessage = decodeProtobuf(MsgRowOpaqueData, decryptedIDBMessage);
		
		decodedIDBMessage.currentMsg.body = body;
		
		const encodedIDBMessage = encodeProtobuf(MsgRowOpaqueData, decodedIDBMessage);
		
		const encryptedIDBMessage = await crypto.subtle.encrypt({
			name: decryptArgs.algorithm.name,
			iv: IDBmessage.msgRowOpaqueData.iv
		}, decryptArgs.key, encodedIDBMessage.readBuffer());
		
		IDBmessage.msgRowOpaqueData._data = encryptedIDBMessage;
		
		setIndexedDB("model-storage", "message", IDBmessage);
};
```
