### ISSUE TITLE
The issue of buttons not displaying properly after WhatsApp update

### ISSUE THREAD

**Issue by happykala** [wppconnect-team/wa-js#1123]
## Description

When trying out the WPP.Chat.sendTextMessage API again to send button messages, it displays normally on the computer, but does not display button messages on Android phones. Is it related to WhatsApp updates?

## Environment

- **WhatsApp version:** 2.2320.10
- **Phone ： WhatsApp version:** 2.23.8.76
- **WA-JS version(s):** 2.24.0
- **Browser:** Chrome 113.0.5672.92
- **OS:** Windows X / OSX X.Y.Z
- **MultiDevice (BETA):** No

## Steps to Reproduce

1. The first step is to send a message with a button type，Computer display is normal
![按钮消息](https://github.com/wppconnect-team/wa-js/assets/12750432/8112cb04-a640-4c68-8adc-0d1f2f9af798)
2. Android phones cannot be displayed
![按钮消息2](https://github.com/wppconnect-team/wa-js/assets/12750432/15e04a99-7769-4396-ac1f-b3374360fb02)

**Comment by PwccaCode** [comment]
this is not a new issue, and will probably not be fixed as mentioned in #905

**Comment by edgardmessias** [comment]
The buttons are deprecated, the Meta blocked it
