### ISSUE TITLE
DuplicateMessageError

### ISSUE THREAD

**Issue by carlosmixz** [wppconnect-team/wa-js#1126]
## Description

Não estou conseguindo enviar mais mensagens via wa-js, literalmente todas respondem da mesma forma: DuplicateMessageError

## Environment

- **WhatsApp version:** 2.2321.6
- **WA-JS version(s):** 2.24.0
- **Browser:** Chrome 113.0.5672.127
- **OS:** Windows 10
- **MultiDevice (BETA):** no

## Steps to Reproduce

1. Envie uma mensagem via WPP.chat.sendTextMessage.
2. Aguarde o promisse dar uma resposta.

## Log Output

```
Uncaught (in promise) DuplicateMessageError
    at app.f886ba84e18051dc3d13.js:40:448059
```

## Your Code

```
let a = WPP.chat.getActiveChat()
WPP.chat.sendTextMessage(a.__x_id._serialized, "Disney")
```

## Additional context / Screenshot
![image](https://github.com/wppconnect-team/wa-js/assets/68700320/5552c5ed-2cf3-44c4-a26b-c1428ee482a7)

**Comment by carlosmixz** [comment]
### God

**Comment by Matheus2212** [comment]
Aparentemente, ainda ocorre.
