### ISSUE TITLE
WPP.chat.sendTextMessage not work

### ISSUE THREAD

**Issue by oto-tatsuu** [wppconnect-team/wa-js#1130]
## Description

I'm using WPP in my project. I use WPP.chat.sendTextMessage to send message. When I call this api for the second time I am getting this error. I think it is due to version update of whatsapp. It can be called normally in version 2.2320.10 but an error will be reported in version 2.2321.6
![WhatsApp Image 2023-05-19 at 7 32 16 PM](https://github.com/wppconnect-team/wa-js/assets/39005237/8603f3f7-bd63-484d-837c-2f922fa36cc3)

## Environment

- **WhatsApp version:** 2.2321.6
- **WA-JS version(s):** latest
- **Browser:** Chrome 113.0.5672.126

## Steps to Reproduce

1. use api to send a message（We found that the message will be blocked and not sent successfully）
2. use api to send a message again the error happen

**Comment by marcelo386** [comment]
WA-JS **v2.24.1** is Working

**Comment by marcelo386** [comment]
#1126

**Comment by theprometeus** [comment]
O envio realmente não está sendo realizado, a mensagem não é enviada mesmo na última versão da biblioteca.

**Comment by edgardmessias** [comment]
Fixed at https://github.com/wppconnect-team/wa-js/releases/tag/v2.24.1
