### ISSUE TITLE
Send List not displaying on receiving end

### ISSUE THREAD

**Issue by ParthThakkar08** [wppconnect-team/wa-js#1145]
## Description
Sending List in new version is not displaying in receiving end when you use WPP.chat.SendListMessage code

## Environment

WhatsApp version: 2.2321.6 (both beta and non beta)
WA-JS version(s): last nightly (2.24.2-alpha.0) according to WPP.version
Browser: Chrome 113.0.5672.127
OS: Windows 10
MultiDevice (BETA): yes

**Comment by edgardmessias** [comment]
This resource was blocked by Meta, there are nothing to do at moment.

**Comment by ParthThakkar08** [comment]
any good news on this?
