### ISSUE TITLE
Timing issue

### ISSUE THREAD

**Issue by Marqui-be** [wppconnect-team/wa-js#1150]
Issue has been resolved.
Main question now: How can I obtain the WhatsApp version?

---

Since 2 weeks, messages sent using WA-js chat.sendTextMessage are no longer sent. They are marked with a 'clock' icon, indicaton network issues. When trying a second time I get a DuplicateMessageError.
No code was changed, behavior is the same on WA-js v2.24.1 and 2.24.2 and older versions.

Manually sent messages work fine, so there is no 'real' network issue so it appears that WA-js is triggering this behavior since the latest WA update.
![image](https://github.com/wppconnect-team/wa-js/assets/24767531/5164f9c0-8ebd-45bb-b49d-846b6e4f709e)

Does this resonate with someone? 
Is there a solution?
Where can I get the WhatsApp version?

How to reproduce:
Open console (or code) and enter:
window.WPP.chat.sendTextMessage('[number]@c.us', 'test', {
      createChat: true
});
Issue: message is marked as 'not sent'

**Comment by yuzedong** [comment]
Using the latest version of wa-js can resolve the issue.

**Comment by Saifallak** [comment]
Fixed by https://github.com/wppconnect-team/wa-js/commit/d95b140164e688c2603487602283039114a9e9b0 ?
