### ISSUE TITLE
Some numbers do not receive the message sent

### ISSUE THREAD

**Issue by roux3** [wppconnect-team/wa-js#1157]
## Description
I have a scheduling system that sends a booking receipt every time an appointment is made, however I was doing some tests here with some phone numbers, and I noticed that contacts that I spoke little to and contacts that I never exchanged messages are not receiving the vouchers, I can see from my cell phone that wppconnect sent the message but it didn't arrive on the customer's cell phone.

## Environment

- **WPPConnect version(s):**1.19.1
- **WA-JS version(s):** 2.17.0
- **Node version:** Node 19.2.0
- **WhatsApp version:** 2.22.2
- **MultiDevice (BETA):** no

**Comment by icleitoncosta** [comment]
Hello, sorry for the delay in response.

Have you managed to resolve the issue?

If not, I've run some tests and couldn't reproduce the error. I noticed you make a button call. Have you been passing the button parameters?

If yes, the button sending feature has been discontinued.
