### ISSUE TITLE
WPP.status.getMyStatus always return undefined

### ISSUE THREAD

**Issue by Gethin0321** [wppconnect-team/wa-js#1175]
https://wppconnect.io/wa-js/functions/status.getMyStatus.html

    const result = await client.pupPage.evaluate(
                        () => WPP.status.getMyStatus()
                    );
                    console.log('getMyStatus', result);

always return undefined

**Comment by Gethin0321** [comment]
And how to get  this status reading list

**Comment by Gethin0321** [comment]
@edgardmessias

**Comment by edgardmessias** [comment]
This is not a bug, this return a "Collection" from your status, it is like a chat
