### ISSUE TITLE
Getting Error after injecting wa.js in browser 

### ISSUE THREAD

**Issue by bracketsApps007** [wppconnect-team/wa-js#1178]
![image](https://github.com/wppconnect-team/wa-js/assets/110741940/6ff4071e-99f7-48d9-835c-0aa22d5bf571)

**Comment by PwccaCode** [comment]
i was able to reproduce on SOME machines, just now

**Comment by edgardmessias** [comment]
@PwccaCode @bracketsApps007 , could you teste with https://github.com/wppconnect-team/wa-js/releases/tag/nightly version?

**Comment by edgardmessias** [comment]
Fixed at https://github.com/wppconnect-team/wa-js/releases/tag/v2.24.3
