### ISSUE TITLE
Send Location Issue

### ISSUE THREAD

**Issue by ParthThakkar08** [wppconnect-team/wa-js#1187]
Sending Location set a message with timer which is never resolved and the whole app gets stuck

**Comment by edgardmessias** [comment]
I did some tests, and currently this is a bug from WhatsApp server.

You can test it usin a business account and use slash shortcut to send the business location, the result will be the same.

**Comment by edgardmessias** [comment]
This still be a bug in whatsapp web, but I could solve it using a little modification
