### ISSUE TITLE
Hoy Start?

### ISSUE THREAD

**Issue by jesussales** [wppconnect-team/wa-js#1188]
I want start with this project, but i don’t know how make It

**Comment by icleitoncosta** [comment]
> I want start with this project, but i don’t know how make It

Hello, what exactly do you need to do? WPPConnect is a comprehensive project with various features, and one of the packages is wa-js, which consists of the exported functions from WhatsApp Web. In the readme on the project's main page (https://github.com/wppconnect-team/wa-js/blob/main/README.md), you can see precisely how to set it up and run it.
