### ISSUE TITLE
WPP.contac.list Bug

### ISSUE THREAD

**Issue by yuzedong** [wppconnect-team/wa-js#1208]
The data structure obtained from WPP.contact.list() has been modified, causing the properties or methods such as isUser, isMyContact, formattedPhone, and others to be used incorrectly. Please fix this issue.Tks.

## Environment

- **WhatsApp version: web.whatsapp.com
- **WA-JS version(s): 2.24.4
- **Browser: Chrome 114
- **OS: OSX

<img width="759" alt="WechatIMG9883" src="https://github.com/wppconnect-team/wa-js/assets/6629143/32898ded-fbf2-4c25-86be-29391dd4d0ec">

**Comment by higormachado3** [comment]
I have the same problem, I am not able to list my contacts through "await WPP.contact.list({onlyMyContacts: true})"
