### ISSUE TITLE
Can't join this group because the number was restricted it

### ISSUE THREAD

**Issue by bracketsApps007** [wppconnect-team/wa-js#1214]
A Question

![image](https://github.com/wppconnect-team/wa-js/assets/110741940/35a8d165-f2c4-4f3b-83f1-33250231869a)

What is the mean exactly?

**Comment by edgardmessias** [comment]
This person is using a privacy setting that don't allow to put he in a group, you can use the invite_code to send a custom invite to the group

**Comment by bracketsApps007** [comment]
Under the privacy -> Groups -> Set to 'Everyone', still returning the same message.

**Comment by bracketsApps007** [comment]
Here is the news, previously I was able to add members in Group without saving them in my contact list, But now its restricted
