### ISSUE TITLE
An issue with addParticipants method

### ISSUE THREAD

**Issue by alechkos** [wppconnect-team/wa-js#1222]
## Description

If the user has forbidden adding himself to the groups, then the method returns a private invitation code, after clicking on which (after creating a link with it) a message is displayed stating that this group does not exist.

## Environment

- **WhatsApp version:** 2.2327.4
- **WA-JS version(s):** 2.24.5
- **Browser:** Chrome 114.0.5735.199
- **OS:** Windows 10
- **MultiDevice (BETA):** yes

**Comment by PwccaCode** [comment]
If the number you are trying to add is not in your contacts it returns and error

**Comment by alechkos** [comment]
> If the number you are trying to add is not in your contacts it returns and error

what error did you get?

**Comment by renat473** [comment]
hello,

to add a member to the group you need to have the contact saved in your device.

The goal now only accepts a new member to be added with the saved number.
