### ISSUE TITLE
Force load all contacts when the amount is in thousands

### ISSUE THREAD

**Issue by tinyCoder32** [wppconnect-team/wa-js#1225]
**Is your feature request related to a problem? Please describe.**
The JS script doesn't load all the contact models when the amount of contacts is higher than 2K or 3K contacts.

**Describe the solution you'd like**
Is there a function that forces WhatsApp to sync the whole contacts list from the phone and get the full list?

Thanks.

**Comment by tinyCoder32** [comment]
Pinging this up.

**Comment by icleitoncosta** [comment]
Hello, it is automatically synchronized when all your contacts are connected.

If you want to check, use:
WPP.whatsapp.ContactStore
