### ISSUE TITLE
send photo with caption is not working

### ISSUE THREAD

**Issue by YHWH-P** [wppconnect-team/wa-js#1232]
## Description

It is not possible to send a base64 photo with an embedded caption through wa-js.

## Environment

- **WhatsApp version:** 2.2329.9
- **WA-JS version(s):** 2.24.7
- **Browser:** Chrome 114.0.5735.199
- **OS:** Windows 10
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. Open Whatsapp Web + WA-JS injected.
2. Open Console, run command: 
WPP.chat.sendFileMessage(WPP.chat.getActiveChat().id,await WPP.util.convertToFile(BASE64string),
                         {filename:"nome",caption:"test",mimetype:(await WPP.util.convertToFile(BASE64string).type})
3. your message will be displayed with the message that it was not possible to send

## Log Output

```
NO LOGS
```
## Additional context / Screenshot
![WhatsApp Image 2023-07-14 at 14 31 02](https://github.com/wppconnect-team/wa-js/assets/22944284/3c7473b1-1eca-4f8f-b59b-7dc940c8aa02)

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by PwccaCode** [comment]
Similar issue when sending video using sendfilemessage

`{message: undefined, name: 'InvalidMediaFileType', stack: 'InvalidMediaFileType\n    at new i (https://web.wha….com/vendor1~app.be50aaad33253076fc3f.js:2:66694)'}`

**Comment by PwccaCode** [comment]
WPP.chat.sendFileMessage(WPP.chat.getActiveChat().id,await WPP.util.convertToFile(BASE64string),
{filename:"nome",caption:"test",mimetype:(await WPP.util.convertToFile(BASE64string).type})

What is WPP.util.convertToFile(BASE64string) doing here? send file message expects a base64 not a file, if you are already providing the base64 in (BASE64string)

just do WPP.chat.sendFileMessage(WPP.chat.getActiveChat().id, BASE64string, 
{filename:"nome",caption:"test",mimetype:''})
