### ISSUE TITLE
Number not save but message not deliver whatsapp up how to solve ?

### ISSUE THREAD

**Issue by Akash-Rathore** [wppconnect-team/wa-js#1233]
unsave number message not deliver  wa js whatsup How to solve
<img width="398" alt="Screenshot 2023-07-16 232522" src="https://github.com/wppconnect-team/wa-js/assets/44320485/133f92d9-e2bc-491d-95af-8ed75a8a1108">

**Comment by edgardmessias** [comment]
You must use createChat option to do it. See at https://wppconnect.io/wa-js/functions/chat.sendTextMessage.html

```js
WPP.chat.sendTextMessage('[number]@c.us', 'Hello new contact', {
  createChat: true
});
```
