### ISSUE TITLE
queryExist takes too long

### ISSUE THREAD

**Issue by rhutikcodes** [wppconnect-team/wa-js#1236]
## Description

queryExist takes too long to complete for the first time, then it works properly.

async function queryExist(jid) {
	return await WPP.contact.queryExists(jid);
}

## Environment

- **WhatsApp version:** 2.2330.11
- **WA-JS version(s):** v2.24.7
- **Browser:** Chrome 114.0.5735.198 (Official Build) (arm64)
- **OS:** Windows X / OSX 13.4.1
- **MultiDevice (BETA):** yes/no

## Steps to Reproduce

1. run await WPP.contact.queryExists(jid);
2. it doesn't return anything for too long
3. after returning, subsequent call works normally 

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
async function queryExist(jid) {
	return await WPP.contact.queryExists(jid);
}
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by rhutikcodes** [comment]
@edgardmessias how to fix this?

**Comment by edgardmessias** [comment]
@rhutikcodes , I did some tests, but I couldn't reproduce it

**Comment by bracketsApps007** [comment]
this is very random issue, No any issue with this library.
Response from WhatsApp server takes too much time. Simply disconnect you internet and connect again
