### ISSUE TITLE
Disponibilização de servidor WPPConnect/WA-JS API SERVER

### ISSUE THREAD

**Issue by GMUNDI** [wppconnect-team/wa-js#1250]
Segue url de servidor disponibilizado para uso da comunidade:

https://tb04.gmundi.com.br

**Comment by icleitoncosta** [comment]
> Segue url de servidor disponibilizado para uso da comunidade:
> 
> https://tb04.gmundi.com.br

Olá @GMUNDI testei, porém, o mesmo não está funcionando. Poderia verificar?
