### ISSUE TITLE
Not able to get Poll response through new message event

### ISSUE THREAD

**Issue by harvansh265** [wppconnect-team/wa-js#1262]
I am using this for new message and its working fine but when user response for Poll message its not triggered 
whatsapp.MsgStore.on('add', (msg) => {console.log(msg)})

basically I want to catch the users response on Poll

**Comment by edgardmessias** [comment]
You can use the `chat.poll_response` event - https://wppconnect.io/wa-js/interfaces/ev.ChatEventTypes.html#chat_poll_response
