### ISSUE TITLE
TypeError: r.findQueryImpl is not a function - error sending messages to new chats

### ISSUE THREAD

**Issue by lukasportal** [wppconnect-team/wa-js#1268]
## Description

New web app update broke `Chat.find()` which is what is called when sending messages with `createChat: true`

## Environment

- **WhatsApp version:** 2.2333.11

## Steps to Reproduce

1. Try to send a message to a new chat (`createChat: true`), making sure the number is not in your chat list.

## Log Output

```
app.9bf7959578bdb7663582.js:52 Uncaught TypeError: r.findImpl is not a function
    at app.9bf7959578bdb7663582.js:51
    at Generator.next (<anonymous>)
    at t (vendor1~app.7f14216f970118f62a35.js:2)
    at s (vendor1~app.7f14216f970118f62a35.js:2)
    at vendor1~app.7f14216f970118f62a35.js:2
    at new Promise (<anonymous>)
    at vendor1~app.7f14216f970118f62a35.js:2
    at O._serverQuery (app.9bf7959578bdb7663582.js:51)
    at O._query (app.9bf7959578bdb7663582.js:51)
    at O.find (app.9bf7959578bdb7663582.js:51)
```

## Additional context / Screenshot
from my findings. they released a new version 2.2333.11
Basically, this is under the`Chat` module.
this class has some methods, mainly `find()` which is used to find a chat. If the chat is already in your chat list (you have a history with it), it will simply call `Chat.get()` and return just fine.
If it is a new conversation, it will try to query its server by first calling `_query()` which will then call `_queryServer()` which will then try to call `findImpl()`, but the problem is that `findImpl()` does not exist! No idea how they can deploy a build that doesn't build lol

or maybe they are now using another method to start a new chat and send messages that does not use `Chat.find()`, which is what we have to figure out: how to get a Chat instance and send a message if there's no conversation with that person yet

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by lukasportal** [comment]
here's my temporary solution until we find a better one it's still under testing, but hoping to work its basically overwriting Store.Chat.find to make sure the new chat is in store and avoiding to call findImpl

```
if (!window.Store.Chat.findTemp) {
    window.Store.Chat.findTemp = window.Store.Chat.find;
}
window.Store.Chat.find = async function (id) {
    try {
        return await window.Store.Chat.findTemp(id);
    }
    catch (err) {
        if (err && err.message && err.message.includes('findImpl')) {
            var tempChat = new window.Store.Chat.modelClass({ id });
            window.Store.Chat.add(tempChat);
            return await window.Store.Chat.findTemp(id);
        }
        throw err;
    }
};
```

this is me using my custom version of WAPI, but surely you can adapt to wa-js format

**Comment by edgardmessias** [comment]
WA-JS do not use Store.Chat, we use a new way to do that.

About the find function, you can use [WPP.chat.find](https://wppconnect.io/wa-js/functions/chat.find.html)
