### ISSUE TITLE
WPP.status.sendTextStatus not working

### ISSUE THREAD

**Issue by Gethin0321** [wppconnect-team/wa-js#1270]
WPP.status.sendTextStatus(`Bootstrap primary color: #0275d8`, { backgroundColor: '#0275d8', font: 2});

now got this data:
{"id":"true_status@broadcast_718B24CDEBD5A66E480F82558D4C7E14_44xxxxxx@c.us","ack":0,"sendMsgResult":[]}

Neither myself nor my friends can see this status

When we could see it before, the returned data was like this:
{"id":"true_status@broadcast_718B24CDEBD5A66E480F82558D4C7E14_44xxxxxx@c.us","ack":1,"sendMsgResult":[]}

ack is different

**Comment by Krb0** [comment]
@Gethin0321  I'm having the same error, have you found any work around?
