### ISSUE TITLE
Bug ContactModel.commonGroups

### ISSUE THREAD

**Issue by loic-hamdi** [wppconnect-team/wa-js#1273]
Hi,

[ContactModel.commonGroups](https://wppconnect.io/wa-js/classes/whatsapp.ContactModel.html#commonGroups) doesn't seem to work properly, it doesn't return any data.

**Comment by icleitoncosta** [comment]
Hello, what is expected from this function specifically? It's declared but I've never tested it.

**Comment by loic-hamdi** [comment]
Hi @icleitoncosta 
You are supposed to see the groups that the user and you have in common
