### ISSUE TITLE
Even though I send statuses to all of my contacts, nothing is being viewed. The status doesn't even open for me, and it doesn't appear on the phone.

### ISSUE THREAD

**Issue by gustavokoz** [wppconnect-team/wa-js#1284]
## Description

Even though I send statuses to all of my contacts, nothing is being viewed. The status doesn't even open for me, and it doesn't appear on the phone.

## Environment

- **WhatsApp version:** 2.2334.12
- **WA-JS version(s):** 2.24.7
- **Browser:** Chrome 115.0.0.0
- **OS:** Linux x86_64
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. WPP.status.sendImageStatus(base64string)

## Additional context / Screenshot
![image](https://github.com/wppconnect-team/wa-js/assets/86996937/4d392eea-5bd9-4ffe-ae54-65d1f3c6fdcd)
![image](https://github.com/wppconnect-team/wa-js/assets/86996937/fac49aed-46db-42db-b51c-a0d7f9d9a4cd)

**Comment by fancywhat** [comment]
i got same error did u resolve it?
