### ISSUE TITLE
Videos recorded at the same time

### ISSUE THREAD

**Issue by boinaweb** [wppconnect-team/wa-js#1305]
There is a way to upload recorded video at the same time using the WPP api, I haven't found anything so far because it's a new feature

**Comment by icleitoncosta** [comment]
Currently, it's not possible through wa-js. The function doesn't yet exist in WhatsApp Web (as far as I've seen), but there are traces of code. With more time, we might be able to create an alternative solution.

**Comment by icleitoncosta** [comment]
Currently, it's not possible through wa-js. The function doesn't yet exist in WhatsApp Web (as far as I've seen), but there are traces of code. With more time, we might be able to create an alternative solution.

**Comment by boinaweb** [comment]
Wonderful, thanks for the clarification. The buttons you have news I saw
people using the buttons menu but I went to test and it doesn't work by wpp
it could be another module.

Em dom., 27 de ago. de 2023 às 19:32, Cleiton Carvalho <
***@***.***> escreveu:

**Comment by icleitoncosta** [comment]
> Wonderful, thanks for the clarification. The buttons you have news I saw people using the buttons menu but I went to test and it doesn't work by wpp it could be another module.

The main alternative APIs don't support buttons. Perhaps there's a lesser-known option, or (more likely) the official API, where it works 100%.
