### ISSUE TITLE
Opção para desativar geração de thumb pelo wa-js-api-server no endpoint semd-message

### ISSUE THREAD

**Issue by GMUNDI** [wppconnect-team/wa-js#1315]
Para evitar os erros de geração de thumbs no envio de mensagem do tipo texto, passo parâmetros adicionais no payload do endpoint send-message.
Com isto consigo enviar exatamente o thumb que quero, sempre enviando em tamanho grande.
Mas mesmo assim no envio continua gerando a thumb quando o endpoint send-message é requisitado.
Quando o server de thumb selecionado para gerar a miniatura está fora do ar ou com lentidão, há muita demora no envio, mas que não está relacionado com o envio em si.
Além disto, por vezes dá timeout. E em alguma vezes que dá timeout a mensagem é enviada mas não retorna a informação de success no json, mas de timeout.
A ideia é realmente poder definir a cada envio se usará o gerador de thumb ou não, ou até mesmo ao identificar que foi passado parâmetros no payload para o envio da thumb, não requisitar do server de thumb.

**Comment by edgardmessias** [comment]
You can pass the message option `{linkPreview: false}`

**Comment by GMUNDI** [comment]
Boa noite. Acredito que não fui claro ao relatar a sugestão.
Se passar linkPreview: false não vai gerar o thumb.
Mas a ideia é, como eu mesmo gero o thumb via programação e passo no options como base64, desativar a tentativa de geração de thumb pela API, mas podendo enviar o meu base64, titel e description.

**Comment by edgardmessias** [comment]
Sim, você foi claro, você pode passar as opções manualmente também nessa mesma opção, em vez de false, passe o objeto com as opções.

```
linkPreview?: boolean | {
    canonicalUrl?: string;
    description?: string;
    doNotPlayInline: boolean;
    matchedText?: string;
    richPreviewType?: number;
    thumbnail?: string;
    title?: string;
}
```

> Boa noite. Acredito que não fui claro ao relatar a sugestão. Se passar linkPreview: false não vai gerar o thumb. Mas a ideia é, como eu mesmo gero o thumb via programação e passo no options como base64, desativar a tentativa de geração de thumb pela API, mas podendo enviar o meu base64, titel e description.
