### ISSUE TITLE
Não carrega chat

### ISSUE THREAD

**Issue by jchiavellibr** [wppconnect-team/wa-js#1322]
Desculpe, meu inglês não é suficiente.

Atualizei para a versão 2.25.0 mas ainda continuo com problemas ao clicar nas conversas, elas não estão sendo carregadas/exibidas.
 

## Environment

- **WhatsApp version:** 2.2335.9
- **WA-JS version(s):** 2.25.0
- **Browser:** Brave  1.57.53 Chromium: 116.0.5845.114 (Versão oficial) 64 bits] 
- **OS:** Windows 11 x64
- **MultiDevice (BETA):** no

## Steps to Reproduce

1. carregar web.whatsapp.com 
2. clicar em alguma conversa na lista
3. chat/conversa não é carregada (lado direito). Tela do "chat" fica toda vazia

## Log Output

Ao carregar a página, os erros abaixo ocorrem apenas se a a biblioteca (wppconnect-wa.js) for carregada:
![image](https://github.com/wppconnect-team/wa-js/assets/39078199/8067e332-4667-4605-92ff-2c17670dd2f1)

Ao clicar nas conversas, o seguinte erro acontece:
![image](https://github.com/wppconnect-team/wa-js/assets/39078199/e79819c2-7c8b-4e59-82ca-900fec72fff4)

 
 
A tela fica assim:
![image](https://github.com/wppconnect-team/wa-js/assets/39078199/9a49d13b-732d-4b9c-8d3b-d32567f58350)

**Comment by boinaweb** [comment]
Hi, did you try to update chromium?

**Comment by dhulke** [comment]
I'm seeing the same issue following the tutorial on the homepage using tampermonkey: https://wppconnect.io/wa-js/#md:tampermonkey-or-greasemonkey

**Comment by jchiavellibr** [comment]
It just got back working using a 3 second setTimetout() to load the js.

*só voltou a funcionar usando um setTimeout de 3s para então carregar o js

**Comment by robertoitec** [comment]
está funcionando bem na versão pessoal, mas no business o bug persiste.

**Comment by robertoitec** [comment]
está funcionando bem na versão pessoal, mas no business o bug persiste.
