### ISSUE TITLE
Select chat programmatically

### ISSUE THREAD

**Issue by dhulke** [wppconnect-team/wa-js#1324]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I want to be able to call a function an change the active chat, including on the whatsapp frontend.

**Describe alternatives you've considered**
None so far

**Additional context**
I'm implementing an extension that uses a router to refer to chats like: https://web.whatsapp.com/#/chat/123... and I want these routes to open specific chats so that I can pass links of chats to other users that share the same whatsapp number.

**Comment by edgardmessias** [comment]
You can use WPP.chat.openChatFromUnread or WPP.chat.openChatBottom

https://wppconnect.io/wa-js/functions/chat.openChatFromUnread.html

https://wppconnect.io/wa-js/functions/chat.openChatBottom.html

**Comment by dhulke** [comment]
Perfect, that might be just what I need. I'm currently unable to test because wajs stopped working on this last version: https://github.com/wppconnect-team/wa-js/issues/1322

**Comment by dhulke** [comment]
@edgardmessias I was able to test this copying wa-js code directly into the developer console but noticed an issue: the chat is selected, but the text that indicates whether a message is from today, yesterday or some other day changes to russian:

before:
<img width="497" alt="image" src="https://github.com/wppconnect-team/wa-js/assets/5838232/f13f73e0-3c86-4570-a21d-b1dc5619e32b">

after calling any of the two functions:
<img width="466" alt="image" src="https://github.com/wppconnect-team/wa-js/assets/5838232/f9eee6f8-1542-44c8-b158-5c1d9b1a2ca0">

I'd be interested in supporting financially this fix.
