### ISSUE TITLE
An event for when whatsapp progress bar finishes

### ISSUE THREAD

**Issue by dhulke** [wppconnect-team/wa-js#1325]
**Is your feature request related to a problem? Please describe.**
The current onready event triggers way before the whatsapp initial progress bar finishes.

**Describe the solution you'd like**
I'd like an event that triggers when the whatsapp loading screen vanishes.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by icleitoncosta** [comment]
Hello @dhulke , you can use the 'conn.main_ready' event, which is only triggered after it's completely loaded. However, the onReady you mentioned, is it the event from the library, or did you mean some other type of event?

**Comment by dhulke** [comment]
The onReady I was refering to is `WPP.webpack.onReady`
