### ISSUE TITLE
why i can't send a status, get error 'ERROR_UNKNOWN'

### ISSUE THREAD

**Issue by fancywhat** [wppconnect-team/wa-js#1327]
only send the web whatspp , but not show in phone whatsapp
why

<img width="939" alt="image" src="https://github.com/wppconnect-team/wa-js/assets/50398009/6415d69b-938b-4e1a-98a3-92b29424ccfe">

**Comment by ParthThakkar08** [comment]
Any updates on this yet?

**Comment by tinyCoder32** [comment]
Any update?

**Comment by edgardmessias** [comment]
Not yet, I am working on it
