### ISSUE TITLE
The isNewMsg property only appears in the latest unread message.

### ISSUE THREAD

**Issue by daviladanielc** [wppconnect-team/wa-js#1333]
## Description

I have implemented the following function:

```
window.WAPI.list = async function () {
  const options = {
    onlyWithUnreadMessage: true
  };

  const chats = await WPP.chat.list(options);
  let messagesResult = [];

  if (chats) {
    try {
      for (var i = 0; i < chats.length; i++) {
        if (chats[i].unreadCount > 0) { // Verifique se msgs existe
          let msgs = await WPP.chat.getMessages(chats[i].__x_id._serialized, {count: -1, onlyUnread: true});
          for (var j = 0; j < msgs.length; j++) {   
            console.log("msg:", JSON.stringify(msgs[j]));         
            if (msgs[j].__x_isNewMsg === true) {                    
              messagesResult.push(msgs[j]);
            }
          }
        }
      }
      console.log(JSON.stringify(messagesResult));
      //SetConsoleMessage("getList", JSON.stringify(messagesResult));
    } catch (e) {
      console.log('Erro:'.concat(e));
    }
  } else {
    console.log('ERRO');
  }
};
```

Previously, in the version of wa-js v2.24.7 with WhatsApp 2.2333.11, if I sent the messages:
1
2
3

using my implementation:

```
if (msgs[j].__x_type === 'chat' && msgs[j].__x_isNewMsg === true) {                    
    messagesResult.push(msgs[j]);
}
```
All three messages were added within the messagesResult.push(msgs[j]);.

However, in the latest versions of wa-js (v2.25.0) and WhatsApp Web (2.2335.9), only the message "3" retains the isNewMsg property, and the messages "1" and "2" do not have this property anymore.

But in my test case, messages 1 and 2 should have isNewMsg = true because they were sent simultaneously along with message 3.

## Environment

- **WhatsApp version:** 2.2336.8
- **WA-JS version(s):** [v2.25.0](https://github.com/wppconnect-team/wa-js/releases/tag/v2.25.0)
- **Browser:** Chrome 110.0.5481.179 / Chromium 110.0.31.0
- **OS:** Windows 10 
- **MultiDevice (BETA):** yes

## Log Output

```

**Comment by edgardmessias** [comment]
@daviladanielc , please, don't use `__x_` attributes, they are non standard

**Comment by marcelo386** [comment]
window.WAPI.list = async function () {
  const options = {
    onlyWithUnreadMessage: true
  };

  const chats = await WPP.chat.list(options);
  let messagesResult = [];

  if (chats) {
    try {
      for (var i = 0; i < chats.length; i++) {
        if (chats[i].unreadCount > 0) { // Verifique se msgs existe
          let msgs = await WPP.chat.getMessages(chats[i].id._serialized, {count: -1, onlyUnread: true});
          for (var j = 0; j < msgs.length; j++) {  
            
            if (msgs[j].isNewMsg === true) {                    
              messagesResult.push(msgs[j]);
            }
          }
        }
      }
      //console.log(JSON.stringify(messagesResult));
      SetConsoleMessage("getList", JSON.stringify(messagesResult));
    } catch (e) {
      console.log('Erro:'.concat(e));
    }
  } else {
    console.log('ERRO');
  }
};

modified the attribute __x_ even so it is not returning all messages pending reading, it only lists the last message
