### ISSUE TITLE
Error when sending mp4 video by PTV type

### ISSUE THREAD

**Issue by DXPRO** [wppconnect-team/wa-js#1343]
## Description

When trying to send a video in mp4 format using the wa-js sendfile by type ptv, in some cases it presents invalid type errors or just the message that it was not possible to send the file

## Environment

- **WhatsApp version:** 2.2337.7
- **WA-JS version(s):**[v2.26.0](https://github.com/wppconnect-team/wa-js/releases/tag/v2.26.0)
- **Browser:** Google Chrome 115.0.5790.171
- **OS:** Edição	Windows 11 Home Single Language
Versão	22H2
Instalado em	‎25/‎07/‎2023
Compilação do SO	22621.2134
Experiência	Windows Feature Experience Pack 1000.22659.1000.0

- **MultiDevice (BETA):** no

## Steps to Reproduce

1 - First step is to inject the wa-js in the browser console by shortcut Ctrl + Shift + J

2 - Second step is to take the video file and transform it into base64 with the correct datatype, I use the site below:
https://base64.guru/converter/encode/video
as shown in the screenshot:
[Screenshot](https://prnt.sc/s9OeeoaQyKCh)

3 - In the third and final step, I paste the function with the id of a group and the base64 file into the console:

 // The PTV Video (micro video)
  WPP.chat.sendFileMessage(
   '120363159509749924@g.us',
   'data:application/msword;base64,<a long base64 file...>',
   {
     type: 'ptv',
   }
  );

## Log Output

```
In the output log it shows the message that I present in the screenshot:
https://prnt.sc/0OEGsKgyef5e

It did not generate any errors this time, but it did not send the video, in other cases it shows that it generated an invalid media format error
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by boinaweb** [comment]
There is a way to not give an error send the mp4 video to your personal number without being ptv, then try to send ptv again it will go without errors, I believe that it stores it temporarily there it ends up recognizing it as valid media.

**Comment by icleitoncosta** [comment]
"Today I ran some tests, but with no success. Only by sending the message first as a video and then resending it as 'ptv' does it work. I need to investigate further, but I haven't given up."
