### ISSUE TITLE
Erro ao adicionar nova Etitqueta

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wa-js#1351]
## Description

Erro ao add uma nova etiqueta.

## Environment

- **WhatsApp version:** 2.2331.9
- **WA-JS version(s):**  2.26.0
- **Browser:** Chrome 
- **OS:** Windows 10
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. Exeucute o código "await WPP.labels.addNewLabel(labelName, { labelColor });"

## Log Output
D:\xampp\htdocs\meuprojeto\sender\node_modules\@wppconnect\wa-js\dist\wppconnect-wa.js:2 Uncaught (in promise) TypeError: i.LabelStore.getLabelColorPalette is not a function
    at t.getLabelColorPalette (D:\xampp\htdocs\meuprojeto\sender\node_modules\@wppconnect\wa-js\dist\wppconnect-wa.js:2:259099)
    at t.colorIsInLabelPalette (D:\xampp\htdocs\meuprojeto\sender\node_modules\@wppconnect\wa-js\dist\wppconnect-wa.js:2:257505)
    at t.addNewLabel (D:\xampp\htdocs\meuprojeto\sender\node_modules\@wppconnect\wa-js\dist\wppconnect-wa.js:2:256749)
    at addLabel (<anonymous>:13:26)
    
```
If relevant, paste all of your Log Output
```

## Your Code
async function addLabel(labelName, labelColor, to_whatsapp) {

    const labels = await WPP.labels.getAllLabels();
    const existingLabel = labels.find(label => label.name === labelName);

    if (existingLabel) {

        console.log(`Etiqueta já existe.`, existingLabel);

    } else {

        console.log(`Etiquta não existe.`);
        await WPP.labels.addNewLabel(labelName, { labelColor });
        
    }

}

addLabel("Teste 01", "#1848bf", "554498002676@c.us");

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

![image](https://github.com/wppconnect-team/wa-js/assets/35501007/99c6b930-8c9a-4727-9bdb-1cf70543ba84)

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by icleitoncosta** [comment]
The functions have been removed from WhatsApp Web, and I'm studying a way to make them work again.

**Comment by icleitoncosta** [comment]
Por favor, testa o PR https://github.com/wppconnect-team/wa-js/pull/1625
