### ISSUE TITLE
Property getDisplayNameOrPnForLid was not found for getDisplayNameOrPnForLid

### ISSUE THREAD

**Issue by jchiavellibr** [wppconnect-team/wa-js#1352]
## Description

The error described in the title started to appear when loading the library.

## Environment

- **WhatsApp version:** 2.2337.7
- **WA-JS version(s):** 2.26.0
- **Browser:** Brave 1.56.20 Chromium: 115.0.5790.171
- **OS:** Windows 10
- **MultiDevice (BETA):** no

## Steps to Reproduce

1. Inject wppconnect-wa.js
2. Error occurs

## Log Output
Property getDisplayNameOrPnForLid was not found for getDisplayNameOrPnForLid in module 714574
get @ wppconnect-wa.js:2
(anonymous) @ wppconnect-wa.js:2
setTimeout (async)
(anonymous) @ wppconnect-wa.js:2
E.emitAsync @ wppconnect-wa.js:2
(anonymous) @ wppconnect-wa.js:2
(anonymous) @ wppconnect-wa.js:2

## Additional context / Screenshot
![image](https://github.com/wppconnect-team/wa-js/assets/39078199/7cdd98f5-72d9-48f1-99fc-d72f0706bcc4)

![image](https://github.com/wppconnect-team/wa-js/assets/39078199/1a73da11-95bc-49a2-964e-2484eee3d1ef)

**Comment by edgardmessias** [comment]
Fixed by f6b463dd5d06e56bf3f1ace40dd7dcdf54d62bca and https://github.com/wppconnect-team/wa-js/releases/tag/v2.26.1

**Comment by jchiavellibr** [comment]
Thank you, Edgar!
