### ISSUE TITLE
Audio Playback Time Becomes Illegible in Older Contacts After Sending Messages

### ISSUE THREAD

**Issue by gustavokoz** [wppconnect-team/wa-js#1369]
## Description

The bug basically changes the language of some contacts after sending a message, including everything, even after opening or before opening the contact.

## Environment

- **WhatsApp version:** 2.2340.7
- **WA-JS version(s):** 2.26.1
- **Browser:** Chrome 116.0.5845.96
- **OS:** Linux x86_64
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. Open a chat.
2. Send a message.
3. When opening an older contact with sent audio messages, the audio's playback time becomes illegible.

## Additional context / Screensho

https://github.com/wppconnect-team/wa-js/assets/86996937/f3bacc12-c423-4d6a-9ec4-38cc0a78dc41

**Comment by edgardmessias** [comment]
Unable to reproduce, try with latest version of WA-JS and WhatsApp please.
