### ISSUE TITLE
timeout load

### ISSUE THREAD

**Issue by amiruldev20** [wppconnect-team/wa-js#1370]
I was using the github version of WAJS and the error occurred page.waitForFunction: Timeout 30000ms exceeded.
    at Client.initialize (file:///C:/Users/Administrator/Desktop/basefix/node_modules/mywajs/src/Client.js:162:12) {
  name: 'TimeoutError'
}

the code is in the section

// Wait for WA-JS to load
  await page.waitForFunction(() => window.WPP?.isReady);

but after I tried the npm version. there was no timeout

**Comment by edgardmessias** [comment]
At nightly version, I made a small change to try to avoid visual bugs, and because of this, this afects the isReady property.

I still working for a best solution of that.

This property work with authenticated sessions

**Comment by edgardmessias** [comment]
fixed by https://github.com/wppconnect-team/wa-js/commit/a60bbd3484c86ba8f3b6c4e09e97f6e4d66baf01
