### ISSUE TITLE
events disabled in the latest version

### ISSUE THREAD

**Issue by marcelo386** [wppconnect-team/wa-js#1394]
## Description

[Events disabled in the latest version]

## Environment

- **WhatsApp version:** 2.2340.17
- **WA-JS version(s):** 2.26.1
- **Browser:** Chrome latest version
- **OS:** Windows 10
- **MultiDevice (BETA):** yes

## Steps to Reproduce

**events below are not working**

//Marcelo 26/07/2023
WPP.on('chat.msg_ack_change', (msg) => {
    console.log(msg);
    SetConsoleMessage("Getmsg_ack_change", JSON.stringify({msg}));
});

//Marcelo 26/07/2023
WPP.on('chat.msg_revoke', (msg) => {
    console.log(msg);
    SetConsoleMessage("Getmsg_revoke", JSON.stringify({msg}));
});

//Evento Recebendo Nova Reação Marcelo 25/07/2023
WPP.on("chat.new_reaction", (msg) => {
    console.log(msg);
    SetConsoleMessage("Getnew_reaction", JSON.stringify({msg}));

});

**Comment by edgardmessias** [comment]
I did some tests and they are working like a charm

**Comment by ParthThakkar08** [comment]
Trying group.participant_changed event but doesn't work
