### ISSUE TITLE
Render Larger Thumbnail

### ISSUE THREAD

**Issue by renzhxr** [wppconnect-team/wa-js#1397]
large thumbnail like at baileys. in baileys code example:

contextInfo: {
 externalAdReply: {
                        title: 'this title',
                        mediaType: 1,
                        previewType: 0,
                        renderLargerThumbnail: true, // this is the code
                        thumbnail: thumbs,
                        sourceUrl: inviteCode
                    }
                }
![Screenshot_20230929-124159.png](https://github.com/wppconnect-team/wa-js/assets/52681808/de1d7d1c-7da4-49c0-b6f2-2309ad00ae71)

**Comment by raajrushs** [comment]
any update on this ?
