### ISSUE TITLE
sendImageStatus/sendVideoStatus has thrown an error [invalid jid type: status@broadcast]

### ISSUE THREAD

**Issue by fancywhat** [wppconnect-team/wa-js#1409]
## Environment

- **WhatsApp version:** Version 2.2343.55
- already update WPP 2.27.0

## Steps to Reproduce

sendTextStatus is ok 
sendImageStatus and sendVideoStatus has thrown an error
the result is OK, but when i refresh WhatsApp, the image or video status has gone
Still unable to sync to the mobile device 😢

![image](https://github.com/wppconnect-team/wa-js/assets/50398009/5768742a-8fbb-433c-b106-f37977747e68)

**Comment by edgardmessias** [comment]
This is not a throw error, but only a "warning" caught by "uncaught" proccess, you can ignore it.

About sendImageStatus, I tested it and it is working normally

**Comment by fancywhat** [comment]
> This is not a throw error, but only a "warning" caught by "uncaught" proccess, you can ignore it.
> 
> About sendImageStatus, I tested it and it is working normally

can you sync to the phone?

**Comment by edgardmessias** [comment]
Yes, you must change the default config `sendStatusToDevice` to true, but there are a chance to crash the device: https://wppconnect.io/wa-js/interfaces/Config.html

> can you sync to the phone?

**Comment by fancywhat** [comment]
> Yes, you must change the default config `sendStatusToDevice` to true, but there are a chance to crash the device: https://wppconnect.io/wa-js/interfaces/Config.html
> 
> > can you sync to the phone?

thank you, it works
