### ISSUE TITLE
version 2.27.0 not sending messages to groups, only contacts

### ISSUE THREAD

**Issue by danieeelfc** [wppconnect-team/wa-js#1411]
After struggling with this all day I've discovered that latest wa-js version 2.27.0 is not sending messages to groups.

Version 2.26.1 works as expected.

## Environment

- **WhatsApp version:** 2.23.19.84
- **WA-JS version(s):** 2.27.0
- **Browser:** Chrome 117.0.5938.149
- **OS:** Windows 11 or MacOS 13.5.2
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1) try to send a message to any group

```
            client
                .sendText('123456789@g.us', 'OLA GRUPO 0')
                .then((result) => {
                    console.log('Result: ', result); //return object success
                })
                .catch((erro) => {
                    console.error('Error when sending: ', erro); //return object error
                });
```

2) result object contains a parameter named isSendFailure which value is true
3) message is not sent
4) ctrl+c
5) npm install @wppconnect-team/wa-js@2.26.1
6) npm start
7) message is now sent (no parameter isSendFailure is shown

**Comment by renat473** [comment]
As a solution, you can change the version of WhatsApp web which is used for the latest version.
https://wppconnect.io/whatsapp-versions
