### ISSUE TITLE
how to send whatsapp status text or image ?

### ISSUE THREAD

**Issue by Dev000-8** [wppconnect-team/wa-js#1434]
I'm new to WA.js and I'm trying to update my status using the WPP.status.sendTextStatus function, but it doesn't seem to be working. I'm not sure if I'm missing something or need more functions to send whatsapp status . Can anyone please help me with this?

**Comment by edgardmessias** [comment]
Could you explain more and show some examples?

**Comment by Khaldoun-Baz** [comment]
Yes he is right WPP.status not working well , it post the status but it do not appear to others

**Comment by icleitoncosta** [comment]
> Yes he is right WPP.status not working well , it post the status but it do not appear to others

Please, update wajs for the latest version. 

Examples:

`WPP.status.sendTextStatus(`Bootstrap primary color: #0275d8`, { backgroundColor: '#0275d8', font: 2});`

`WPP.status.sendImageStatus('data:image/jpeg;base64,<a long base64 file...>');`
