### ISSUE TITLE
the screen turn gray after login

### ISSUE THREAD

**Issue by oto-tatsuu** [wppconnect-team/wa-js#1451]
## Description

I have a problem with wa-js. I'm develop a chrome extension using wa-js. I want to listen the login status of WhatsApp. I inject the script and login the WhatsApp then the screen got gray. After some tries I found that it is a common problem not only occurred in chrome extension but also occurred when run npm run launch:local. And this problem is also mentioned in https://github.com/wppconnect-team/wa-js/issues/1249. Please help me resolve it,thx
## Environment

- **WhatsApp version:** 2.2347.56
- **WA-JS version(s):** 2.28.0
- **Browser:** Chrome 118.0.5993.117 / Chromium XX
- **OS:** Windows X / OSX X.Y.Z
- **MultiDevice (BETA):** yes/no

## Steps to Reproduce

1. run command `npm run launch:local`
2. notice that WhatsApp is not login, scan the QR Code
3. WhatApp logined and the problem occurred

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here. If applicable, add screenshots to help explain.
<img width="1438" alt="Screen Shot 2023-10-30 at 15 13 40" src="https://github.com/wppconnect-team/wa-js/assets/39005237/ced02010-ee1d-4731-879d-f6b7437fe896">

**Comment by edgardmessias** [comment]
This is the hardest problem to solve, I have been trying a lot of way, but it still happen

**Comment by rotivjr** [comment]
I am trying to create an chrome extension and I had the same problem, but I could find a "workaround": I inject the wpconnect-wa.js inside a setTimeout function. It worked for me.

**Comment by Krb0** [comment]
#1521 It's the same issue
