### ISSUE TITLE
deleteMessage in group chat

### ISSUE THREAD

**Issue by loic-hamdi** [wppconnect-team/wa-js#1452]
Hi, For some reasons I can't delete messages in group chat anymore.
Is it still working on your side?

Where do you get the data from for:`chatId` and `id` ?

[https://github.com/wppconnect-team/wa-js/blob/main/src/chat/functions/deleteMessage.ts#L47](https://github.com/wppconnect-team/wa-js/blob/main/src/chat/functions/deleteMessage.ts#L47)

[https://wppconnect.io/wa-js/functions/chat.deleteMessage.html](https://wppconnect.io/wa-js/functions/chat.deleteMessage.html)

**Comment by loic-hamdi** [comment]
@edgardmessias 
@edgardmessias 
Hi guys, sorry for the direct tag, I please need your help on this one as it is breaking in my current app.

Could you please test if deleting messages (normal chat & groups) still works on your side?

Thank you in advance.

**Comment by edgardmessias** [comment]
@loic-hamdi , could you post the example of code that you are using?

**Comment by loic-hamdi** [comment]
> @loic-hamdi , could you post the example of code that you are using?

I use this package [https://pub.dev/packages/whatsapp_bot_flutter](https://pub.dev/packages/whatsapp_bot_flutter) that is basically a communication bridge between Dart and wa-js.

The dart code in the package is as follow:
```dart
  /// Delete message
  /// Set revoke: true if you want to delete for everyone in group chat
  Future deleteMessage({
    required String phone,
    required String messageId,
    bool deleteMediaInDevice = false,
    bool revoke = false,
  }) async {
    return await wpClient.evaluateJs(
      '''WPP.chat.deleteMessage(${phone.phoneParse},${messageId.jsParse}, $deleteMediaInDevice, $revoke);''',
      methodName: "deleteMessage",
    );
  }
```

The JS equivalent as you can see is: 
`WPP.chat.deleteMessage(${phone.phoneParse},${messageId.jsParse}, $deleteMediaInDevice, $revoke);`



If I try to delete a message in a group:
```dart 
Future<dynamic> deleteMessageInGroup(WhatsappClient client, Message message) async {
  final messageId = message.id!.serialized;
  final phone = message.id!.serialized.split('_').last;
  final r = await executeWAFunction(() => client.chat.deleteMessage(phone: phone, messageId: messageId, deleteMediaInDevice: true, revoke: true));
  return r;
}
```

The future (_promise in JS_) returns  this error message: 
`{id: false_120363178483272749@g.us_3A7A39E4C00345DE91E3F_15216763775@c.us, sendMsgResult: ERROR_UNKNOWN, isDeleted: false}`

**Comment by loic-hamdi** [comment]
@edgardmessias Did you have a chance to look at it? 
Thanks in advance

**Comment by icleitoncosta** [comment]
Hello, the functions are working fine within WAJS.

I don't have knowledge of Flutter or Dart, as I've never used these languages. However, wouldn't the error be related to phoneParse and jsParse, perhaps?
