### ISSUE TITLE
Integração Pagamentos.

### ISSUE THREAD

**Issue by lucazin** [wppconnect-team/wa-js#1486]
Integração com metodos de pagamentos do whatsapp @icleitoncosta .

**Comment by icleitoncosta** [comment]
Apenas para documentar, não há nenhuma indicação que o whatsapp irá incluir as funções de enviar pagamento no whatsapp web, até o momento, portanto, porenquanto, não há uma forma de fazer isso, até porque me parece que há uma conecção no dispositivo do celular que mantém a segurança da operação.

**Comment by lucazin** [comment]
Eu iria utilizar pra solicitar e enviar pagamentos no nosso pdv, seria uma
mão na roda.

Mas antes estamos com problemas em atualizar o item no catálogo na versão
2.30

Obggg

Em sex., 8 de dez. de 2023 11:24, Edgard Lorraine Messias <
***@***.***> escreveu:

**Comment by icleitoncosta** [comment]
> @icleitoncosta , é possível sim, gera um trabalho mas é possível.
> 
> Eu acredito que não seria bom implementar a parte de enviar pagamento, mas permitir solicitar.
> 
> O problema de enviar pagamento é questão de segurança, vai que alguém utilize o projeto para criar um vírus.



> @icleitoncosta , é possível sim, gera um trabalho mas é possível.
> 
> Eu acredito que não seria bom implementar a parte de enviar pagamento, mas permitir solicitar.
> 
> O problema de enviar pagamento é questão de segurança, vai que alguém utilize o projeto para criar um vírus.

Realmente, achei o código das especificações aqui, tanto do request, cancel, accept, etc. 
Acho meio estranho existir a possibilidade de enviar pagamento... sem validação pelo dispositivo, na proxima semana estudo como implementar essas solicitações, mas imagino que seja da mesma forma que fiz com a sendScheduledCallMessage

**Comment by icleitoncosta** [comment]
The payment request function has been removed from WhatsApp, and sending payments can only be done through the device for Meta's security. Therefore, the issue is closed as it cannot be implemented.
