### ISSUE TITLE
Problems sending messages to edited numbers

### ISSUE THREAD

**Issue by luizsergiorf** [wppconnect-team/wa-js#1487]
Hello, congratulations on the project. However, I have the following problem:

Here in Brazil, we changed the inclusion of an extra digit on phones, so many people's WhatsApp has changed, however in this tool, when I send it with an extra digit, it is not directed to the correct WhatsApp and does not reach the user, for example, +551199889988, it was a WhatsApp before being increased by the ninth, with the implementation the number became +5511999889988. And when the tool sends it to +5511999889988, it doesn't reach the user, only if it is sent by the old one, 551199889988. What could it be?

Strangely, if you use wa.me/+5511999889988, it works and directs you to +551199889988.

**Comment by edgardmessias** [comment]
Hello, first thank you for your appreciation. Second, I am from Brazil too.

So, about your problem, you must use [WPP.contact.queryExists](https://wppconnect.io/wa-js/functions/contact.queryExists.html) function before sending message to get the real number.

**Comment by luizsergiorf** [comment]
Boa tarde Edgard, como sou brasileiro, fica mais fácil me comunicar em português. Estou tentando implementar, mas não estou conseguindo.

contact é uma string. Segue o trecho:

```

const result = await WPP.contact.queryExists(contact);
contact = result._serialized;
```

No entanto, estou obtendo o erro: A propriedade '_serialized' não existe no tipo 'QueryExistsResult'.ts(2339). 

Poderia me ajudar?"

**Comment by icleitoncosta** [comment]
> Boa tarde Edgard, como somos brasileiros, fica mais fácil de comunicar em português. Estou tentando implementar, mas não estou conseguindo.
> 
> contact é uma string. Segue o trecho:
> 
> ```
> 
> const result = await WPP.contact.queryExists(contact);
> contact = result?.wig._serialized;
> ```
> 
> No entanto, estou obtendo o erro: O tipo 'string | undefined' não pode ser atribuído ao tipo 'string'. O tipo 'undefined' não pode ser atribuído ao tipo 'string'.ts
> 
> Poderia me ajudar?"

Olá @luizsergiorf, parece ser um erro de Typescript, tente algo como: 

```
const result = await WPP.contact.queryExists(contact as string);
contact = result?.wig._serialized;
```

**Comment by jormarymaquinas** [comment]
> > Boa tarde Edgard, como somos brasileiros, fica mais fácil de comunicar em português. Estou tentando implementar, mas não estou conseguindo.
> > contact é uma string. Segue o trecho:
> > ```
> > 
> > const result = await WPP.contact.queryExists(contact);
> > contact = result?.wig._serialized;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > No entanto, estou obtendo o erro: O tipo 'string | undefined' não pode ser atribuído ao tipo 'string'. O tipo 'undefined' não pode ser atribuído ao tipo 'string'.ts
> > Poderia me ajudar?"
> 
> Olá @luizsergiorf, parece ser um erro de Typescript, tente algo como:
> 
> ```
> const result = await WPP.contact.queryExists(contact as string);
> contact = result?.wig._serialized;
> ```

Obrigado @icleitoncosta, continuou com o problema, consegui resolver fazendo uma verificação antes da atribuição.


```
const result = await WPP.contact.queryExists(contact);
    if (result && result.wid) {
        contact = result.wid.user;
...
```

**Comment by luizsergiorf** [comment]
> > Boa tarde Edgard, como somos brasileiros, fica mais fácil de comunicar em português. Estou tentando implementar, mas não estou conseguindo.
> > contact é uma string. Segue o trecho:
> > ```
> > 
> > const result = await WPP.contact.queryExists(contact);
> > contact = result?.wig._serialized;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > No entanto, estou obtendo o erro: O tipo 'string | undefined' não pode ser atribuído ao tipo 'string'. O tipo 'undefined' não pode ser atribuído ao tipo 'string'.ts
> > Poderia me ajudar?"
> 
> Olá @luizsergiorf, parece ser um erro de Typescript, tente algo como:
> 
> ```
> const result = await WPP.contact.queryExists(contact as string);
> contact = result?.wig._serialized;
> ```

Obrigado @icleitoncosta por responder, tentei mas não deu certo, consegui fazendo uma verificação antes da atribuição:

```
const result = await WPP.contact.queryExists(contact);
    
    if (result && result .wid) {
        contact = resultAux.wid.user;
     ...
     }
```
