### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by renerlemes** [wppconnect-team/wa-js#152]
Is there any documentation on how to use this library?
For example, how to get the QrCode or how to send a message?

**Comment by edgardmessias** [comment]
@renerlemes , I put some content in the README.md file:

https://github.com/wppconnect-team/wa-js#how-to-use-this-project

Could you review it?

**Comment by renerlemes** [comment]
@edgardmessias yes. I managed to get the status and also send a message. However, I couldn't get the QrCode and other functions because it doesn't have documentation. Would you have more details?
