### ISSUE TITLE
Error when inject the wa-js

### ISSUE THREAD

**Issue by luizsergiorf** [wppconnect-team/wa-js#1521]
I've been having problems since yesterday when injecting wa-js. following error:

Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forwardRef')

![286872928-1ca09776-b383-4aeb-9080-e1025302ccc5](https://github.com/wppconnect-team/wa-js/assets/26284039/bde472fa-9afe-4514-8cb3-8ff8abc754f7)

Until yesterday, the code was working perfectly well, was there any WhatsApp update?

**Comment by edgardmessias** [comment]
Could you put more informations about the version of WhatsApp and WA-JS?
How are you injecting the script?

**Comment by luizsergiorf** [comment]
I found the WhatsApp Web version: 2.2353.0

**Comment by liorn** [comment]
I have the same problem with Whatsapp Web Version 2.2353.0 .
I'm injecting your sample script using TamperMonkey, and it gives me the same error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forwardRef')
    at t.FlatListFactory (app.e6352145ea3a831d9908.js:311:137739)
    at 485189 (main.09aa8246bb66447e103e.js:5:1864798)
    at t (runtime.bb8f0d615cc1abcb0c34.js:1:215)
    at 672578 (main.09aa8246bb66447e103e.js:5:1850498)
    at t (runtime.bb8f0d615cc1abcb0c34.js:1:215)
    at 637624 (main.09aa8246bb66447e103e.js:5:1841520)
    at t (runtime.bb8f0d615cc1abcb0c34.js:1:215)
    at 202391 (main.09aa8246bb66447e103e.js:5:1921647)
    at t (runtime.bb8f0d615cc1abcb0c34.js:1:215)
    at 112258 (main.09aa8246bb66447e103e.js:5:1236393)
```

**Comment by luizsergiorf** [comment]
Hello @edgardmessias,

Were you able to identify the issue? 

I've been trying all weekend but without success to resolve this problem.

**Comment by icleitoncosta** [comment]
> Hello @edgardmessias,
> 
> Were you able to identify the issue?
> 
> I've been trying all weekend but without success to resolve this problem.

Hi, please test the latest verison.

**Comment by icleitoncosta** [comment]
I will mark this issue as resolved, as I have already received feedback on other issues. Please reopen it if it has not been resolved.
