### ISSUE TITLE
Error While Joining Group via Invite Code 

### ISSUE THREAD

**Issue by raajrushs** [wppconnect-team/wa-js#1530]
As par the documentations , I am trying to add member in my group But because of target members Privacy it shows 
'Can't join this group because the number was restricted it'

![image](https://github.com/wppconnect-team/wa-js/assets/139004347/e4ae2050-5ce1-4c91-891c-ddd45a19178b)

Now I am getting same Invite code and Send it via simple text message

![image](https://github.com/wppconnect-team/wa-js/assets/139004347/f9dd928d-c050-41f5-83fb-2a3ee465af47)

Message Sent successfully, 
![image](https://github.com/wppconnect-team/wa-js/assets/139004347/e3118698-f005-4e86-b167-f802d00a0df5)

But Problem is When target person try to Join Group, it shows 'The Group Does Not Exists'

![image](https://github.com/wppconnect-team/wa-js/assets/139004347/95ab740c-c297-457e-a271-525bd218a81a)

Is there any way to send Invitation to Target Number like below image ?

![image](https://github.com/wppconnect-team/wa-js/assets/139004347/4050b688-a8d9-4a4c-966e-87a2131a9b9e)

**Comment by icleitoncosta** [comment]
Hello, I tried to reproduce this error, but without success. Could you retry the test, generating a new invitation code for the group and going through the steps where the error occurred?

**Comment by raajrushs** [comment]
https://wppconnect.io/wa-js/functions/group.addParticipants.html

```
const result = await WPP.group.addParticipants('[group@g.us]', [number@c.us]);
const link = 'https://chat.whatsapp.com/' + result['123@c.us'].invite_code;

WPP.chat.sendTextMessage('[number]@c.us', link );
```

Is this 'invite_code' here for that particular number, Is really working ? I am not talking about Global Group Link

**Comment by edgardmessias** [comment]
They changed the way to do this.

We need to create a new type of message and use this code to send it.

**Comment by raajrushs** [comment]
what is ` inviteGrp: '789@generator.us'` ?

**Comment by raajrushs** [comment]
Its working Perfectly . Thanks @edgardmessias
