### ISSUE TITLE
Could not receive button message

### ISSUE THREAD

**Issue by kakaPup** [wppconnect-team/wa-js#1606]
<!  -- Please fill in as much information as possible, preferably in English.   -->
In the latest version, I tried to send a button message.  In the web version, I could see the message I sent, but the other party could not receive the message, neither in the APP nor in the web version

## Description

[Description of the bug, When Issue Happens]

## Environment

- **WhatsApp version:** X.YYYY.ZZ
- **WA-JS version(s):** X.Y.Z
- **Browser:** Chrome XX / Chromium XX
- **OS:** Windows X / OSX X.Y.Z
- **MultiDevice (BETA):** yes/no

## Steps to Reproduce
WPP.chat.sendTextMessage('8618602984080@c.us', 'Hello', {
useTemplateButtons: true, // False for legacy
buttons: [
{
url: 'https://wppconnect.io/',
text: 'WPPConnect Site'
},
{
phoneNumber: '+55 11 22334455',
text: 'Call me'
},
{
id: 'your custom id 1',
text: 'Some text'
},
{
id: 'another id 2',
text: 'Another text'
}
],
title: 'Title text', // Optional
footer: 'Footer text' // Optional
});

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code
WPP.chat.sendTextMessage('8618602984080@c.us', 'Hello', {
useTemplateButtons: true, // False for legacy
buttons: [
{
url: 'https://wppconnect.io/',
text: 'WPPConnect Site'
},
{
phoneNumber: '+55 11 22334455',
text: 'Call me'
},
{
id: 'your custom id 1',
text: 'Some text'
},
{
id: 'another id 2',
text: 'Another text'
}
],
title: 'Title text', // Optional
footer: 'Footer text' // Optional
});
```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

Add any other context about the problem here.   If applicable, add screenshots to help explain.

**Comment by renat473** [comment]
depracted

**Comment by kakaPup** [comment]
The problem is not solved, and the message sent can only be seen by the web version and cannot be received by the other party
