### ISSUE TITLE
Bug com as etiquetas a partir da Versão 2.2402.2 do Whatsapp web

### ISSUE THREAD

**Issue by waTools-br** [wppconnect-team/wa-js#1607]
![WhatsApp Image 2024-01-11 at 10 39 59](https://github.com/wppconnect-team/wa-js/assets/139009534/0270217c-1860-4f86-b074-feb3ebc81712)

Após essa atualização, as etiquetas retornam "undefined" para color e Hexcolor.

**Comment by icleitoncosta** [comment]
Olá, por favor, testa o PR https://github.com/wppconnect-team/wa-js/pull/1625
