### ISSUE TITLE
Contact dont be removed when i use `WPP.whatsapp.ChatStore.remove()`

### ISSUE THREAD

**Issue by raphaguasta** [wppconnect-team/wa-js#1629]
## Description

Hello, guys!

I am filtering the list according to the user's click, and whenever a new message is received, I need to update the list according to the filter.

I'm doing this clearing the list, and adding just the necessary as follows:
```
window.WPP.on('chat.new_message', (msg) => {
    store.currentTab = name

    let chats = store.allChats.filter(item => !!item)
    let contactToUse = chats.filter(item => store.tabs['myFilter'].includes(item.contact.name))

    window.WPP.whatsapp.ChatStore.remove(chats)
    window.WPP.whatsapp.ChatStore.add(contactToUse)
})
```

But for some reason, some messages give a console error and don't remove the item from the list.

![Captura de Tela 2024-01-22 às 20 33 34](https://github.com/wppconnect-team/wa-js/assets/6708227/c21df8c9-4724-4102-b931-41541fb4930e)

![Captura de Tela 2024-01-22 às 20 33 51](https://github.com/wppconnect-team/wa-js/assets/6708227/20e8fa70-276d-41bd-a84f-6349baa489fb)

## Environment

- **WhatsApp version:** 2.2403.4
- **WA-JS version(s):** 2.28.1
- **Browser:** Chrome 120.0.6099.234
- **OS:** MacOS BigSur
- **MultiDevice (BETA):** no

## Steps to Reproduce

1. Insert wa.js in web whatsapp;
2. Use the filter as I explined;

**Comment by icleitoncosta** [comment]
I tried to reproduce your error (since I don't have the code) as follows:

```
const chat = WPP.chat.get('number@c.us');
WPP.whatsapp.ChatStore.remove([chat]);
```

And it didn't show any errors, using the same version as yours. Try posting the complete code, or reproduce it differently. It might be an error in your own store from where you're fetching these contacts.
