### ISSUE TITLE
infinite errors on console(bussines only)

### ISSUE THREAD

**Issue by gustavokoz** [wppconnect-team/wa-js#1682]
infinite errors in the console.

## Environment

- **WhatsApp version:** 2.2406.4
- **WA-JS version(s):** 2.28.1
- **Browser:** 121 chrome
- **OS:** Windows 1
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. open whatsapp with WPP

![image](https://github.com/wppconnect-team/wa-js/assets/86996937/ae7c787e-1eab-4a9e-9de2-bed25daea374)

**Comment by above7sky** [comment]
Yes.
For me it is showing this error too.

**Comment by icleitoncosta** [comment]
Hi, can you test in the latest version?
