### ISSUE TITLE
Bug Injection WA_JS WhatsApp version:  2.3000.1011510815

### ISSUE THREAD

**Issue by marcelo386** [wppconnect-team/wa-js#1685]
## Description

Bug Injection WA_JS

## Environment

- **WhatsApp version:**  2.3000.1011510815
- **WA-JS version(s):** 2.28.2-alpha.0

**Comment by PwccaCode** [comment]
What is the error code?

**Comment by PwccaCode** [comment]
https://github.com/wppconnect-team/wa-js/tree/whatsapp_2.3000.x

**Comment by heyikang** [comment]
Whatsapp 2.3 version not working

**Comment by edgardmessias** [comment]
Closed by https://github.com/wppconnect-team/wa-js/releases/tag/v3.0.0
