### ISSUE TITLE
Erro ao gerar thumb no WPP.chat.sendTextMessage com ou sem info de linkPreview.

### ISSUE THREAD

**Issue by GMUNDI** [wppconnect-team/wa-js#1714]
Ao fazer envio de mensagem pelo WPP.chat.sendTextMessage que contém link, não gera a thumb e apresenta erro de CORS.
Mesmo colando o link em um chat aberto, quando a lib está injetada, não gera o thumb e dá erro de CORS.
Fiz os testes usando as versões v2.27.0, v2.28.0, v2.28.1e uma versão de testes. Também efetuei os testes tanto na versão Versão 2.2409.2 quanto a 2.3000 do Whatsapp.
Os testes foram feitos tanto injetando a lib em um addon do Chrome como injetando manualmente colando no console.

Versão do chrome: 122.0.6261.95 (Versão oficial) 64 bits

Versão do windows: 
Edição	Windows 10 Pro
Versão	22H2
Instalado em	‎15/‎08/‎2022
Compilação do SO	19045.4046
Experiência	Windows Feature Experience Pack 1000.19053.1000.0

Quando faço a chamada passando parâmetros de linkPreview acontece na maioria das vezes o envio do thumb, mas sempre pequeno.

Uma solução interessante que vi em outra ferramenta, a EvolutionAPI é que no comando de envio pode-se setar um delay para que o server deles espere x milissegundos para que o Whatsapp gere o thumb.

Este é o payload para envio de mensagem de texto na Evolution API:
`{
  "number": "[remoteJid]",
  "options": {
    "delay": 1200,
    "presence": "composing"
  },
  "textMessage": {
    "text": "Veja o link https://www.cnnbrasil.com.br/economia/negocios/justica-de-sp-proibe-meta-de-usar-marca-no-brasil-apos-pedido-de-empresa-homonima/"
  }
}`

Referência: https://doc.evolution-api.com/docs/05-Endpoints/00-send-plain-text

Este é o erro: Refused to load the image 'https://wppc-linkpreview.cloudtrix.com.br/v1/link-preview/fetch-data.png?url=https://www.cnnbrasil.com.br/economia/negocios/justica-de-sp-proibe-meta-de-usar-marca-no-brasil-apos-pedido-de-empresa-homonima/' because it violates the following Content Security Policy directive: "img-src 'self' data: blob: https://*.whatsapp.net https://maps.googleapis.com/maps/api/staticmap https://*.fbcdn.net *.tenor.co *.tenor.com *.giphy.com https://*.ytimg.com".

Comando sem linkPreview:
`await WPP.chat.sendTextMessage('5500000000000@c.us', 'See https://www.cnnbrasil.com.br/economia/negocios/justica-de-sp-proibe-meta-de-usar-marca-no-brasil-apos-pedido-de-empresa-homonima/ ');`

Comando com linkPreview (a imagem passada no thumb não é a mesma da contida no link de propósito. É enviada a imagem que está no base64 do linkPreview):
`await WPP.chat.sendTextMessage('5500000000000@c.us', 'See https://www.cnnbrasil.com.br/economia/negocios/justica-de-sp-proibe-meta-de-usar-marca-no-brasil-apos-pedido-de-empresa-homonima/ ', {
    linkPreview: {
        title: "Teste de titulo",
        description: "Teste de info",
        richPreviewType: 1,
        doNotPlayInline: false,
        thumbnail: "Aqui vai o base64 da imagem",
    }
});
`

**Comment by icleitoncosta** [comment]
Olá @GMUNDI, poderia testar a última versão nightly para ver se os erros continuam ocorrendo? 
https://github.com/wppconnect-team/wa-js/releases/tag/nightly

**Comment by GMUNDI** [comment]
Bom dia!

Fiz testes em 2 versões do whatsapp.

Na versão Versão 2.2412.50 no primeiro envio não gera a thumb e depois gera thumb grande.
Na versão Versão 2.3000.1012380726 no primeiro envio não gera thumb e depois gera thumb grande.

Enviei link de Youtube e na versão 2.2412.50 mostrou apenas o thumb e clicando abre no navegador (testei no web.whatsapp)
Já na versão 2.3000.1012380726 mostrou o thumb e quando clica abre um lightbox com o vídeo sobre o whatsapp.

![-3-WhatsApp](https://github.com/wppconnect-team/wa-js/assets/7459804/d4a2925d-4fcd-4b46-802a-68c492cbb2b9)

**Comment by GMUNDI** [comment]
Usando link de sites de clientes, há uma demora maior para começar a gerar as thumbs. Foram necessários alguns envios (entre 4 e 5) para que a thumb começasse a ser enviada.
![-2-WhatsApp](https://github.com/wppconnect-team/wa-js/assets/7459804/39e624d0-073a-4803-bfa4-48f8ff160c9e)

**Comment by andredealmei** [comment]
Mesmo problema aqui

![image](https://github.com/wppconnect-team/wa-js/assets/33403972/72168eac-9c7a-4412-bd7a-5d0f126dbb14)

**Comment by icleitoncosta** [comment]
Please, test in the latest versions.
