### ISSUE TITLE
f.map is not a function

### ISSUE THREAD

**Issue by Onerazan** [wppconnect-team/wa-js#1715]
## Description

Since the past 2 or 3 weeks, users that utilize my extension are experimenting an error where the WPP.chat.getMessages(); method seemed to not execute and froze the entire process. After some researching and encapsulating the method with try catch blocks, I managed to get at least a error message that indicates that f.map is not a function.

Sometimes the error doesn't happen, sometimes it does. It could be happening with some chats in particular, but it hasn't been investigated yet.

## Environment

- **WhatsApp version:** 2.2409.4
- **WA-JS version(s):** 2.28.2-alpha.0
- **Browser:** Chrome 122.0.6261.95
- **OS:** Windows 11
- **MultiDevice (BETA):** No

## Steps to Reproduce

1. Inject wa-js into Whatsapp Web
2. Get the last message Id and chat Id from all chats
3. Send the chat information to a server and recieve instructions from the server, instructions being a message Id or "getAll" in order to know what messages retrieve from those chats.
4. Call WPP.chat.getMessages() using those chats Ids and instructions;

## Log Output

```
TypeError: f.map is not a function
    at t.getMessages (wppconnect-wa.js:2:145497)
    at async getMessages (<anonymous>:30:20)
```

## Code (This method is also injected into the Whatsapp Web application)

chatData could be something like: {"XXXXXX@c.us":"false_XXXXXX@c.us_BE429563E6B576880A007E09891C896C", "XXXXXX@c.us":"getAll"}

```
async function getMessages(batchSize, stringifiedChatData) {
  let chatData = JSON.parse(stringifiedChatData);
  let numberOfChats = Object.keys(chatData).length;
  let processedChats = 0;
  let extensionId = "xxxxxxxxxxxx";
  console.log(chatData);

  if (numberOfChats == 0) {
    chrome.runtime.sendMessage(extensionId, {
      finishedProcessingChats: true,
    });

    return;
  }

  for (const id in chatData) {
    let instruction = chatData[id];
    let args = { count: batchSize };
    let breakExecution = false;

    if (instruction != "getAll") {
      args.direction = "after";
      args.id = instruction;
    }

    do {
      let messages = [];
    
      try {
        messages = await WPP.chat.getMessages(id, args);
      } catch (e) {
        console.error(e);
      }

      let wrappedMessages = [];
      let messageMedia = [];

      if (messages.length < batchSize) {
        console.log("break");
        breakExecution = true;
      }

      for (let i = 0; i < messages.length; i++) {
        if (messages[i].t < new Date("2024-01-01").getTime() / 1000) {
          breakExecution = true;
          continue;
        }

        try {
          let messageWrapped = {};

          if (!messages[i].body && !messages[i].mediaData) {
            continue;
          }

          messageWrapped.SerializedMessageId = messages[i].id._serialized;
          messageWrapped.IsSentFromUser = messages[i].id.fromMe;
          messageWrapped.SentFrom = messages[i].from.user;
          messageWrapped.To = messages[i].to.user;
          messageWrapped.ChatId = messages[i].id.remote;
          messageWrapped.Message = messages[i].body;
          messageWrapped.Timestamp = messages[i].t;

          if (messages[i].mediaData) {
            let mediaData = {};

            let blobData = await WPP.chat.downloadMedia(
              messageWrapped.SerializedMessageId
            );

            let base64Data = await WPP.util.blobToBase64(blobData);

            base64Data = base64Data.split(",")[1];

            mediaData.blobData = base64Data;
            mediaData.fileName = Date.now();
            mediaData.contentType = blobData.type;
            mediaData.externalId = messageWrapped.SerializedMessageId;

            messageWrapped.Message = null;

            messageMedia.push(mediaData);
          }
          wrappedMessages.push(messageWrapped);
        } catch (error) {
          console.error("Error wrapping message", messages[i], error);
        }
      }

      await chrome.runtime
        .sendMessage(extensionId, {
          wrappedMessages: JSON.stringify(wrappedMessages),
          messageMedia: JSON.stringify(messageMedia),
        })
        .then((response) => {
          if (response != "OK") {
            breakExecution = true;
          }
        });

      if (instruction == "getAll") {
        args.direction = "before";
        args.id = messages[0].id._serialized;
      } else {
        args.id = messages[messages.length - 1].id._serialized;
      }
    } while (!breakExecution);

    processedChats++;

    chrome.runtime.sendMessage(extensionId, {
      processedChats: processedChats,
      numberOfChats: numberOfChats,
    });
  }

  chrome.runtime.sendMessage(extensionId, {
    finishedProcessingChats: true,
  });
}
```

**Comment by Onerazan** [comment]
I kept digging, and it seems the problem comes from the line 160 at the getMessages function.

I managed to modify the minified wa-js compiled file and it appears that when the code finally gets to this part of the code

`msgs = msgs.map((m: any) => {
    if (options?.onlyUnread) m.isNewMsg = true;
    if (m instanceof MsgModel) {
      return m;
    }
    return MsgStore.get(m) || new MsgModel(m);
  });`

the content of msgs is {status: 404}

![image](https://github.com/wppconnect-team/wa-js/assets/75145544/f9a047bd-18bd-4ceb-8173-49bc1cb1b8ad)

**Comment by Onerazan** [comment]
@edgardmessias I think that maybe there is a problem with msgFindQuery, I didn't understand much of the code, so this is as far as I could go. But by examining the arguments that I use when calling getMessages, it would seem like I would get the messages from the line 150 of getMessages.ts

`msgs = await msgFindQuery(direction, params);`

So my guess is that msgFindQuery(direction, params); could be returning {state: 404} instead of an Array of messages. I'm not much of a JavaScript developer (And never did a single line of TypeScript), so I might be off.

**Comment by icleitoncosta** [comment]
Hello, I did several tests and the functions are still normal.
Please update packages and test on the latest released versions

Att,

**Comment by manfe** [comment]
@icleitoncosta @Onerazan  I investigated further on this and looks like, this only happens when you are trying to get messages and the id checkpoint to use to get before or after is deleted.

```ts
const messages = await instance.getMessages(chatWid._serialized, {
  id: deletedMessageId,
  direction: 'before',
  count: 20,
})
```
