### ISSUE TITLE
"getGroupInfoFromInviteLink" não mostra o ID correto da Comunidade

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wa-js#1723]
## Description

Estou tentando fazer um envio de mensagem em comunidade pelo link de convite, mas ao chamar a função "getGroupInfoFromInviteLink " a mesma está trazendo um ID errado.

## Environment

- **WPPConnect version(s):** 2.2347.56
- **WA-JS version(s):** 2.28.0
- **Browser:** Chrome 119.0.6045.160
- **OS:** Windows 10
- **Node version:** Node 18.18.0
- **WhatsApp version:** 2.23.23.79
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. Chame a função "getGroupInfoFromInviteLink" e passe o CÓDIGO do link da comunidade de avisos;
2. Pegue o ID retornado e tente chamar a função "sendText" para o ID retornado;
3. Nada acontecerá.

## Log Output

```
If relevant, paste all of your Log Output
```

## Your Code

```
If relevant, paste all of your challenge code in here
```

## Additional context / Screenshot

✅ Veja o ID da comunidade através do evento "onAnyMessage"

![image](https://github.com/wppconnect-team/wppconnect/assets/35501007/39fdbfd4-b33e-4437-bed5-8132242c2f46)

❌ Veja agora o ID (errado) gerado chamando a função "getGroupInfoFromInviteLink":

![image](https://github.com/wppconnect-team/wppconnect/assets/35501007/f2a022d0-93db-4347-b315-e893e7f0f762)

**Comment by icleitoncosta** [comment]
Hoje passei um tempo tentando resolver essa issue. Quando utilizarmos o getGroupInfoFromInviteLink em uma comunidade, ele retorna um grupo da comunidade, uma instância que tem os dados dela e subtype `create`, porém não a comunidade em si (ou seja, o grupo de anuncios), que é subtype `community`, em breve, vou tentar mais um pouco, e vejo se acho alguma parte do código que dá para pegarmos esse link do grupo de anuncios em si (comunidade).

**Comment by icleitoncosta** [comment]
Improovments/Fixed by https://github.com/wppconnect-team/wa-js/commit/10f29eed5aaa95489b3ef29da4e268eaeb30e259
