### ISSUE TITLE
error on send list

### ISSUE THREAD

**Issue by gustavokoz** [wppconnect-team/wa-js#1728]
When sending a list through WPP.chat.sendListMessage, the message always has a clock and gives this error
![image](https://github.com/wppconnect-team/wa-js/assets/86996937/8ba3d409-cb40-49b0-b091-e5bc1af3f78b)
- **WhatsApp version:** 2.3000.1011957409
- **WA-JS version(s):** 3.0.0
- **Browser:** Chrome 121
- **OS:** Windows 11
- **MultiDevice (BETA):** yes

**Comment by above7sky** [comment]
Will we be able to use the function in this 2.3x version?
