### ISSUE TITLE
Archive chat not working

### ISSUE THREAD

**Issue by CardosoGit** [wppconnect-team/wa-js#1734]
We had tested in chrome console e we get this error.

![image](https://github.com/wppconnect-team/wa-js/assets/10578336/30b13ae8-f028-4f2d-8c53-45851e14d187)

WhatsApp version: 2.3000.1011957409
WA-JS version(s): 3.0.0
Browser: Chrome 121
OS: Windows 11
MultiDevice (BETA): yes

**Comment by icleitoncosta** [comment]
Fixed by https://github.com/wppconnect-team/wa-js/commit/d58e6d734783b9d9660698d6c5745a28775ed2bd
