### ISSUE TITLE
send messages in group chat 

### ISSUE THREAD

**Issue by s1dc0des** [wppconnect-team/wa-js#1758]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by icleitoncosta** [comment]
Please, send:
WhatsApp Version:
WA_JS Version:

**Comment by icleitoncosta** [comment]
> using lates version of wa_js. and using a wrapper around it for dart/flutter https://pub.dev/packages/whatsapp_bot_flutter
> 
> heres how it injects wajs in inappwebview on mobile devices https://github.com/rohitsangwan01/whatsapp_bot_flutter/blob/2534cbd8028061b25eeec762ad24ff398768255a/packages/whatsapp_bot_platform_interface/lib/src/wpp/wpp_connect.dart#L12

What is the version of WhatsApp you are logged in and getting the error?

**Comment by mkamra2000** [comment]
## Description ##
When I'm sending message to any group chat then this error is showing
`Your Message was not sent or sometimes clock icon near to message is visible.`
![image](https://github.com/wppconnect-team/wa-js/assets/73895535/bdb2a33f-c4d7-4741-88ff-c7ab5f50b4bf)

## Environment ##
WhatsApp Version 2.2412.50
WA-JS version(s): 3.0.0
Browser: Chrome 122.0.6261.131 
OS: Windows 10
MultiDevice (BETA): no

## Steps to reproduce ##
Just Send message to any group chat

 ## Question ##
> using lates version of wa_js. and using a wrapper around it for dart/flutter https://pub.dev/packages/whatsapp_bot_flutter
> 
> heres how it injects wajs in inappwebview on mobile devices https://github.com/rohitsangwan01/whatsapp_bot_flutter/blob/2534cbd8028061b25eeec762ad24ff398768255a/packages/whatsapp_bot_platform_interface/lib/src/wpp/wpp_connect.dart#L12

Is this a permanent fix for this issue?

**Comment by icleitoncosta** [comment]
> ## Description
> When I'm sending message to any group chat then this error is showing `Your Message was not sent or sometimes clock icon near to message is visible.` ![image](https://private-user-images.githubusercontent.com/73895535/316735656-bdb2a33f-c4d7-4741-88ff-c7ab5f50b4bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTk0ODQsIm5iZiI6MTcxMTU1OTE4NCwicGF0aCI6Ii83Mzg5NTUzNS8zMTY3MzU2NTYtYmRiMmEzM2YtYzRkNy00NzQxLTg4ZmYtYzdhYjVmNTBiNGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE3MDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MzJiYzFkNWI2MTBlYjdiOTA0YWQyNGIwY2FjMGE1YjA3ZTBhNTRlYWI5YzQxMWZmZTFjY2Q4NjlmNWIwNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._J1-SZoUkvucgXIKypKpf81xyezHPUhoSL02Gehv2NA)
> 
> ## Environment
> WhatsApp Version 2.2412.50 WA-JS version(s): 3.0.0 Browser: Chrome 122.0.6261.131 OS: Windows 10 MultiDevice (BETA): no
> 
> ## Steps to reproduce
> Just Send message to any group chat
> 
> ## Question
> > using lates version of wa_js. and using a wrapper around it for dart/flutter https://pub.dev/packages/whatsapp_bot_flutter
> > heres how it injects wajs in inappwebview on mobile devices https://github.com/rohitsangwan01/whatsapp_bot_flutter/blob/2534cbd8028061b25eeec762ad24ff398768255a/packages/whatsapp_bot_platform_interface/lib/src/wpp/wpp_connect.dart#L12
> 
> Is this a permanent fix for this issue?

Please, inject the latest version of WAJS, try send the message and check the isOfficial
`WPP.whatsapp.isOfficialClient`

**Comment by icleitoncosta** [comment]
I will mark this issue as resolved, as I have already received feedback on other issues. Please reopen it if it has not been resolved.
