### ISSUE TITLE
Erro ao injetar o wa-js  na versão '2.2411.x'

### ISSUE THREAD

**Issue by waTools-br** [wppconnect-team/wa-js#1764]
Ao injetar o wa-js nessa versão acontece esse erro mostrado ai abaixo na qual o carregamento da pagina trava, e caso o usuário esteja no momento de ler o QRcode o erro e ainda pior pois não deixa ele realizar a leitura.

![WhatsApp Image 2024-03-20 at 16 37 55](https://github.com/wppconnect-team/wa-js/assets/139009534/34e3e26c-3419-4f9e-af86-4bd742fa5362)

 whatsAppVersion: '2.2411.x'
- **WA-JS version(s): 3.0
- **Browser:** Todos

**Comment by icleitoncosta** [comment]
Opa @waTools-br, tentei reproduzir o mesmo erro setando essa versão, mas sem sucesso. 
Como você fez para setar a mesma? Utilizou a lib? 

Testei tanto na versão 2.2411.2 e também na 2.2412.1, que são as que você informou e a versão que aparece no Debug.

**Comment by waTools-br** [comment]
Opa, blz?

Então setei o cookie wa_build com w para ir na versão mais antiga, e sim utilizei a lib, tanto que agora refiz o teste novamente injetando o código dela manualmente e na versão mais atual dela

![imagem_2024-03-22_192334134](https://github.com/wppconnect-team/wa-js/assets/139009534/162d233f-bbe6-42f7-9c5f-bef01b58da05)

**Comment by icleitoncosta** [comment]
Solved by [commit ](https://github.com/wppconnect-team/wa-js/commit/79f1f2e5e4a7c574fde8d9c45ac0da271be5422f)
