### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'm')

### ISSUE THREAD

**Issue by DXPRO** [wppconnect-team/wa-js#1778]
### WA-JS Version

v3.0.1

### WhatsApp Version

2.3000.1012314172

### Browser Version

Chrome Version 122.0.6261.131

### Operation System

Windows 11

### Steps to reproduce

1 - Open the browser console connected to WhatsApp web in version 2.3000.x

2 - Inject WA-JS version 3.0.1

3 - Call the WPP.chat.list() await function;

### What is expected?

Show WhatsApp Web conversation list

### What is actually happening?

Generating the error: Uncaught TypeError: Cannot read properties of undefined (reading 'm')
    at Object.p [as searchId] (<anonymous>:12567:58)
    at Object.get [as ChatStore] (<anonymous>:13134:45)
    at t.list (<anonymous>:6574:31)
    at <anonymous>:1:16

This error is caused by the function below:

```
function p(e, r = !1) {
                    let n = Object.keys(t.webpackRequire.m);
                    r && (n = n.reverse());
                    const o = setTimeout(() => {
                        a(`Searching for: ${e.toString()}`);
                    }, 500);
                    for (const r of n)
                        if (!f(r))
                            try {
                                const n = (0, t.webpackRequire)(r);
                                if (e(n, r)) return a(`Module found: ${r} - ${e.toString()}`), clearTimeout(o), r;
                            } catch (e) {
                                continues;
                            }
                    n = Object.keys(t.fallbackModules);
                    for (const r of n)
                        try {
                            const n = t.fallbackModules[r];
                            if (e(n, r)) return a(`Fallback Module found: ${r} - ${e.toString()}`), clearTimeout(o), r;
                        } catch (e) {
                            continues;
                        }
                    return a(`Module not found: ${e.toString()}`), null;
                }
```

**Comment by silemftooh** [comment]
The steps to reproduce the issue are:
1) Login Whatsapp scanning QR code  (whatsapp version > 2.3000)
2) Manual inject wa js in console (single time)

WPP.isInjected is always False

**Comment by opsJson** [comment]
Whatsapp is delivering js that is incompatible with the lib when you have the "wa_build=c" cookie set.

To fix it, set the cookie to any other value, then reload the page:

```js
document.cookie = "wa_build=w;domain=.web.whatsapp.com;path=/";
```

For me, Whatsapp is setting this cookie every time I reload the page, forcing me to set another value for the cookie every time.

**Comment by ono77** [comment]
the problem seems that sometimes in the last 2.300 version, the injected code wrongly set the loaderType = "webpack" instead of "meta".

Maybe a solution is adding a check of wa web version In the injectLoader function, replacing these lines

```
, n = "webpackChunkwhatsapp_web_client"
, o = e[n] || [];
 void 0 === e[n] ? e[n] = o : t.loaderType = "webpack";
```

with
```
,n="webpackChunkwhatsapp_web_client"
,o=e[n]||[];
const versionString = (Debug || {}).VERSION;
const versionNumber = parseFloat(versionString);i
f (void 0 === e[n]) {e[n] = o;} else if (versionNumber < 2.3) { t.loaderType = "webpack";}
```

**Comment by icleitoncosta** [comment]
Hello, could you please test this fix I made on the scenarios you've been facing and provide feedback on the PR?

https://github.com/wppconnect-team/wa-js/pull/1783

**Comment by silemftooh** [comment]
It's a great
Thank you very much 🌹🌹🌹
