### ISSUE TITLE
Script injection fails because of undefined prop

### ISSUE THREAD

**Issue by martin-888** [wppconnect-team/wa-js#1801]
### WA-JS Version

3.1.0

### WhatsApp Version

2.2412.54

### Browser Version

Chrome 123.0.6312.87

### Operation System

MacOS 14.2

### Steps to reproduce

Injecting of last stable version fails because of an uncaught error:

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'VERSION')`

it points to this line in the code (`self.Debug` is undefined)

https://github.com/wppconnect-team/wa-js/blob/main/src/webpack/index.ts#L163

![image](https://github.com/wppconnect-team/wa-js/assets/7429956/95250519-1e79-4378-8c7f-89f7a36f5428)

### What is expected?

it doesn't fail and inject the code successfully

### What is actually happening?

fails and keeps `WPP` global object undefined

**Comment by cleytoncoro** [comment]
I'm getting an "undefined" error too.

Windows 11.
Chromium 121.
wa-js version 3.1.0
wa version at android 2.24.6.77 business

![image](https://github.com/wppconnect-team/wa-js/assets/22160920/81670e89-5cab-4e8a-b673-823f8c304a10)


![image](https://github.com/wppconnect-team/wa-js/assets/22160920/a0c09051-6b83-425c-af99-e72886c749ff)

**Comment by jimenezbre** [comment]
i solved by using evaluate instead of addScripTag, but still hapens with other injections

**Comment by javix64** [comment]
> i solved by using evaluate instead of addScripTag, but still hapens with other injections, but just found another solution you can call page.setBypassCSP(true); just before using page.goto

could you please, share the function that you use it?
