### ISSUE TITLE
Many methods fail to be injected and functions are unavailable

### ISSUE THREAD

**Issue by kakaPup** [wppconnect-team/wa-js#1817]
### WA-JS Version

v3.1.0

### WhatsApp Version

2.3000.1012630795

### Browser Version

1.8.2 modified version

### Operation System

windows

### Steps to reproduce

![Snipaste_2024-04-09_10-20-22](https://github.com/wppconnect-team/wa-js/assets/140926167/01d79f5e-be58-4510-80bb-c31fa8b76d43)

### What is expected?

yes

### What is actually happening?

yes

**Comment by mashuang0323** [comment]
After connecting to wppconnect-wa.js, you can send messages, but you cannot receive messages from others. An error is being reported here.
![image](https://github.com/wppconnect-team/wa-js/assets/50570996/91df488c-06a6-407c-a4be-65b5289348f5)
![image](https://github.com/wppconnect-team/wa-js/assets/50570996/f2cb5dc7-a44b-433d-ad8c-71d893d0dfc6)

**Comment by heyikang** [comment]
I have the same error
<img width="1914" alt="image" src="https://github.com/wppconnect-team/wa-js/assets/34233756/e41a0842-016e-495d-a3be-a0a371825234">

**Comment by wangsen2020** [comment]
No one in this version gets the message.

**Comment by above7sky** [comment]
I also get these error messages! :(

**Comment by icleitoncosta** [comment]
Please test the nightly version

https://github.com/wppconnect-team/wa-js/releases/tag/nightly

**Comment by qeternity** [comment]
The `Unknown File path "9550"` issue persists on nightly.

**Comment by heyikang** [comment]
<img width="1116" alt="image" src="https://github.com/wppconnect-team/wa-js/assets/34233756/b6cba7fc-54dd-4470-85e0-4e25cd0029bd">
