### ISSUE TITLE
Week days appear in spanish

### ISSUE THREAD

**Issue by abhyudayasrinet** [wppconnect-team/wa-js#1829]
### WA-JS Version

3.1.0

### WhatsApp Version

2.3000.1012670384

### Browser Version

Chrome 123.0.6312.106 (Official Build) (64-bit)

### Operation System

Windows 11

### Steps to reproduce

1. inject wpp.js
2. open a chat and look for the yesterday, Monday, Tuesday... tag names (refer screenshot)

### What is expected?

the week day names should appear in whatever the system language is set to

### What is actually happening?

The week day name tags appear in spanish
![image](https://github.com/wppconnect-team/wa-js/assets/5520691/01fe4a0b-db1f-49c2-ad25-47afd6bb46a5)

**Comment by ariona** [comment]
Same here, it seems wpp somehow load `WAWebMoment-es-do`, which make some part of wa web change to espanol.

<img width="480" alt="Screenshot 2024-04-14 at 04 39 43" src="https://github.com/wppconnect-team/wa-js/assets/752483/77b995a7-4ebf-43a3-a256-3195ae9fa10a">

**Comment by trexsiddharth** [comment]
@ariona Did you solve it?

**Comment by ariona** [comment]
> @ariona Did you solve it?

Not at the moment, nothing wrong my our code, whenever we drop wa-js on WhatsApp Web the weekdays on chat turn into spanish.

**Comment by trexsiddharth** [comment]
I have solved it for the moment.

**Comment by ariona** [comment]
> I have solved it for the moment.

can you share your solution?
