### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'VERSION')

### ISSUE THREAD

**Issue by code4you2021** [wppconnect-team/wa-js#1851]
### WA-JS Version

3.1.1

### WhatsApp Version

2.3000.1012938617

### Browser Version

Chrome 124.0.6367.62

### Operation System

macOS 13.3.3

### Steps to reproduce

1. Install the Demo extension
2. Open URL: https://web.whatsapp.com/

<img width="725" alt="" src="https://github.com/wppconnect-team/wa-js/assets/83153991/f2dc29fa-d1a0-41d0-8e4c-0b915f134e67">

[Demo.zip](https://github.com/wppconnect-team/wa-js/files/15051246/Demo.zip)

### What is expected?

it doesn't fail and inject the code successfully

it points to this line in the code (self.Debug is undefined)
https://github.com/wppconnect-team/wa-js/blob/main/src/webpack/index.ts#L163

https://github.com/wppconnect-team/wa-js/issues/1801

### What is actually happening?

fails and keeps WPP global object undefined

**Comment by code4you2021** [comment]
@javix64 

you are right.

Paste the `wppconnect-wa.js` code in the console, and it should run smoothly. 

It won't work properly when injected using `Tampermonkey` and Chrome extensions.

**Comment by javix64** [comment]
Hey @code4you2021 I have found a low quality solution for this issue.

If you search in the entire project `self.Debug.VERSION`, it will appear only two result, change it for a higher version. For example:

`compare(self.Debug.VERSION, '2.3000.0', '>=')` ==> `compare('2.3000.1', '2.3000.0', '>=')`

Let's see what the maintainers need to say about this issue. :smile:
