### ISSUE TITLE
isReady WPP.isReady(WPP.isReady) reading is no longer a function, does not work for api is online

### ISSUE THREAD

**Issue by eduardoff19** [wppconnect-team/wa-js#1863]
### WA-JS Version

wa-js@3.1.1

### WhatsApp Version

 2.3000.1012980395

### Browser Version

24.0.6367.29 

### Operation System

Windows 11

### Steps to reproduce

when reproducing the connection ready VM69:3 says it is no longer valid, Uncaught (in promise) TypeError: Cannot read properties of null (reading '__esModule')
     at conditions (<anonymous>:3:445382) isConnected is not working as expected WAPI.isConnected() no longer works WAPI.isConnected not function

### What is expected?

when reproducing the connection ready VM69:3 says it is no longer valid, Uncaught (in promise) TypeError: Cannot read properties of null (reading '__esModule')
     at conditions (<anonymous>:3:445382) isConnected is not working as expected WAPI.isConnected() no longer works WAPI.isConnected not function

### What is actually happening?

new version changed

**Comment by icleitoncosta** [comment]
Hello, what project are you using?

**Comment by icleitoncosta** [comment]
In WAJS that is working;
Please submit the issue in the project you are using.
