### ISSUE TITLE
CHECKNUMBER STATUS

### ISSUE THREAD

**Issue by uppermesh** [wppconnect-team/wa-js#1888]
### WA-JS Version

3.2.2

### WhatsApp Version

2.2412.54

### Browser Version

ND

### Operation System

UBUNTU

### Steps to reproduce

Apos essse fix https://github.com/wppconnect-team/wa-js/commit/e89a3744afe84011e1c9461e2eee04ceaaf66c28

o checknumber status retorna sempre true independente se o numero tem ou não o 'nono' digito.

### What is expected?

Até a versao wa-js@3.1.0
a função estava retornando corretamente.

### What is actually happening?

Até a versao wa-js@3.1.0
a função estava retornando corretamente.

### Any additional comments?

Desculpe se não abri a issue de forma correta, mas é a primeira vez que faço a abertura.

**Comment by DXPRO** [comment]
De fato após realizar alguns testes, ao usar o const result = await WPP.contact.queryExists('[number]@c.us'); eu posso passar meu numero que não possui o 9 digito, com o 9 digito e o resultado será uma conta valida, porém o ID serialized vem também com o 9 digito, onde após realizar um envio para esse id, fica como um numero invalido nas conversas!

**Comment by tonvital** [comment]
Same bug here!

This number are registred: +55 (48) 8875-1529

I have tested with:
+55 (48) 8875-1529 and results is: ✅ function return "isRegistred"
+55 (48) 9 8875-1529 and results is same: ✅ function return "isRegistred"
