### ISSUE TITLE
Possibilidade de listar os chats desejados no inbox do whatsapp

### ISSUE THREAD

**Issue by waTools-br** [wppconnect-team/wa-js#1892]
Essa função seria muito útil para quem trabalha com a lib utilizando a própria interface do WhatsApp. Gostaria de poder listar apenas os contatos, grupos não lidos, etiquetas e até contatos específicos direto da caixa de entrada do WhatsApp. Seria basicamente exportar a função que gerencia esse filtro abaixo, o que daria mais liberdade para trabalhar com automações direto na página do WhatsApp.

![imagem_2024-05-02_141210057](https://github.com/wppconnect-team/wa-js/assets/139009534/1d09fb2a-b296-437d-8e47-3ff7e49b1ccc)

E caso seja possível ter uma funcionalidade extra na qual eu passo alguns contatos, por exemplo, ['number@c.us', '[number]@g.us'], e apenas eles fiquem visíveis na caixa de entrada. Atualmente, já realizo esse cenário demonstrado, mas demanda muito código e sempre acaba com um bug ou outro por se tratar de uma manipulação paralela a funcionalidade nativa

Bem, no geral, essa é a ideia. Sei que a lib não é focada nesse tipo de função, mas seria bacana tê-la. Ajudaria muito para quem a utiliza diretamente na interface do WhatsApp.

**Comment by icleitoncosta** [comment]
Olá, isso nada mais é, do que um filtro basico do array getLists, por exemplo. 

const chats = await WPP.chat.list();

```
const unread = chats.filter((chat)=> chat.unreadCount > 0));
const groups = chats.filter((chat) => chat.id.toString().includes('@g.us'));
```

E assim, por diante, verificando etiquetas, etc.
