### ISSUE TITLE
event that returns Banned Account Status

### ISSUE THREAD

**Issue by marcelo386** [wppconnect-team/wa-js#1899]
**Is your feature request related to a problem?**
automatically identify Banned Account Status more quickly, to delete instances and warn about this status

**Describe the solution you'd like**
create an event that returns this status

**Describe alternatives you've considered**
Today I do it manually, it takes a long time to identify

**Comment by sandro-salles** [comment]
Hi Marcelo,
Do you mind sharing the way you're currently doing it today? I'm also struggling to find the correct way to do that (currently a lot of false positives, and sometimes false negatives as well).

Best regards!
