### ISSUE TITLE
Wpp.chatt.getmessages () This method is not available. An error is reported

### ISSUE THREAD

**Issue by kakaPup** [wppconnect-team/wa-js#1918]
### WA-JS Version

v3.2.5

### WhatsApp Version

2.3000.1013409128

### Browser Version

1.8.2 modified version

### Operation System

windows

### Steps to reproduce

![image](https://github.com/wppconnect-team/wa-js/assets/140926167/a931d84d-1332-4057-a587-a07a49951995)

### What is expected?

![Snipaste_2024-05-10_09-53-16](https://github.com/wppconnect-team/wa-js/assets/140926167/183ea0e2-94df-4df6-bae7-331af0c1e63c)

### What is actually happening?

1

### Any additional comments?

1

**Comment by icleitoncosta** [comment]
Fixed by https://github.com/wppconnect-team/wa-js/commit/a2f90533d21ffe8b30836c8c08c699da01606564
