### ISSUE TITLE
Adicionar versão do wa-js na descrição no cabeçalho do arquivo.

### ISSUE THREAD

**Issue by GMUNDI** [wppconnect-team/wa-js#1928]
Ajudaria a identificar para quem usa o js localmente ou no servidor próprio e acaba lidando com várias versões em testes.

**Comment by icleitoncosta** [comment]
> Ajudaria a identificar para quem usa o js localmente ou no servidor próprio e acaba lidando com várias versões em testes.



> Ajudaria a identificar para quem usa o js localmente ou no servidor próprio e acaba lidando com várias versões em testes.

Olá @GMUNDI , você diz no arquivo já compactado?

**Comment by GMUNDI** [comment]
Sim, dentro deste arquivo, por exemplo:
https://github.com/wppconnect-team/wa-js/releases/download/v3.2.6/wppconnect-wa.js

Talvez isto no arquivo já ajudaria:
/*! For license information please see wppconnect-wa.js.LICENSE.txt */
/*| wa-js version: v3.2.6 */

Talvez até colocar uma função que retorne qual a versão do wa-js.
E até outras, como a versão do whatsapp (não sei se já tem) e outras info neste sentido (versão do navegador, do SO).

Mas ter fácil a identificação de qual versão do wa-js estamos usando já seria bom.

**Comment by DXPRO** [comment]
Você consegue opter a informação da versão do WA_JS em WPP.version, basta chamar isso no console!
