### ISSUE TITLE
Error Delete Message Uncaught (in promise) ActionError

### ISSUE THREAD

**Issue by marcelo386** [wppconnect-team/wa-js#1939]
### WA-JS Version

3.2.6

### WhatsApp Version

2.3000.1013624694

### Browser Version

101.0.4951.67

### Operation System

windows 10

### Steps to reproduce

Error Uncaught (in promise) ActionError

### What is expected?

Fix Delete message

### What is actually happening?

Fix Delete message

### Any additional comments?

Uncaught (in promise) ActionError

![image](https://github.com/wppconnect-team/wa-js/assets/69150213/2a404c8d-0665-4e9b-9a1a-9888ca4db4af)

**Comment by jimenezbre** [comment]
to com mesmo problema aqui

**Comment by DXPRO** [comment]
Olá, qual é o processo ou função que esta usando no momento, que ocasiona esse erro? Não ficou claro qual é o passo a passo até chegar no erro l!

**Comment by marcelo386** [comment]
> Olá, qual é o processo ou função que esta usando no momento, que ocasiona esse erro? Não ficou claro qual é o passo a passo até chegar no erro l!

WPP.chat.deleteMessage('[number]@c.us', 'msgid', true, true);  exatamente como informado no comentário acima

Na última versão mudou um pouco, eu já encontrei o argumento que mudou passei para o Cleiton, como ficou na versão nova

**Comment by luidiva** [comment]
> Olá, qual é o processo ou função que esta usando no momento, que ocasiona esse erro? Não ficou claro qual é o passo a passo até chegar no erro l!

aqui acontece nos grupos com o revoke true

**Comment by luidiva** [comment]
> > Olá, qual é o processo ou função que esta usando no momento, que ocasiona esse erro? Não ficou claro qual é o passo a passo até chegar no erro l!
> 
> WPP.chat.deleteMessage('[number]@c.us', 'msgid', true, true); exatamente como informado no comentário acima
> 
> Na última versão mudou um pouco, eu já encontrei o argumento que mudou passei para o Cleiton, como ficou na versão nova

coloca aqui como ficou, por favor

**Comment by jimenezbre** [comment]
{
    "name": "ActionError",
    "stack": "ActionError\n    at a.d [as constructor] (https://static.whatsapp.net/rsrc.php/v3iCuB4/yY/l/rt/k5akTZbD-6u.js?_nc_x=Ij3Wp8lg5Kz:604:217)\n    at new a (https://static.whatsapp.net/rsrc.php/v3iCuB4/yY/l/rt/k5akTZbD-6u.js?_nc_x=Ij3Wp8lg5Kz:1526:6018)\n    at Object.a [as current] (https://static.whatsapp.net/rsrc.php/v3iwg34/y2/l/rt/jRjZBSe5C3f.js?_nc_x=Ij3Wp8lg5Kz:126:15399)\n    at https://static.whatsapp.net/rsrc.php/v3iCuB4/yY/l/rt/k5akTZbD-6u.js?_nc_x=Ij3Wp8lg5Kz:3155:282\n    at e.<anonymous> (https://static.whatsapp.net/rsrc.php/v3iCuB4/yY/l/rt/k5akTZbD-6u.js?_nc_x=Ij3Wp8lg5Kz:3209:1205)\n    at b._triggerEvents (https://static.whatsapp.net/rsrc.php/v3iCuB4/yY/l/rt/k5akTZbD-6u.js?_nc_x=Ij3Wp8lg5Kz:1567:3182)\n    at b.trigger (https://static.whatsapp.net/rsrc.php/v3iCuB4/yY/l/rt/k5akTZbD-6u.js?_nc_x=Ij3Wp8lg5Kz:1567:1490)\n    at f.sendDeleteMsgs (https://static.whatsapp.net/rsrc.php/v3iCuB4/yY/l/rt/k5akTZbD-6u.js?_nc_x=Ij3Wp8lg5Kz:1693:7005)\n    at t.deleteMessage (<anonymous>:1:139353)"
}

**Comment by ParthThakkar08** [comment]
I am still facing the same error

**Comment by bosaeed** [comment]
still facing same error

**Comment by bosaeed** [comment]
Hi,
I tried new release and now no error is shown and message is removed from UI only not removed from any other session and if browser closed and opened all message return back

**Comment by icleitoncosta** [comment]
> Hi,
> I tried new release and now no error is shown and message is removed from UI only not removed from any other session and if browser closed and opened all message return back

Try this way
``
await WPP.chat.deleteMessage('[number]@c.us', '[msgid]ADAD1', true, true);
``

**Comment by bosaeed** [comment]
it works when revoke is true but not works if need to delete message in my side only
at first message is deleted and show popup that message delete at my side after that other popup says delete message not completed 
![image](https://github.com/wppconnect-team/wa-js/assets/6698779/3b59afe6-c398-439c-854e-2fda87dea07b)

**Comment by icleitoncosta** [comment]
What is the WhatsApp version?




*Cleiton Carvalho *


Em sex., 7 de jun. de 2024 às 11:50, bosaeed ***@***.***>
escreveu:

**Comment by bosaeed** [comment]
version 2.3000.1014049052

**Comment by bosaeed** [comment]
version 2.3000.1014049052

**Comment by icleitoncosta** [comment]
> it works when revoke is true but not works if need to delete message in my side only
> at first message is deleted and show popup that message delete at my side after that other popup says delete message not completed

Thank you, I just fixed that error.

**Comment by bosaeed** [comment]
working 👍
