### ISSUE TITLE
edit Message error Caption edit File - Uncaught (in promise) Error: Cannot edit this message

### ISSUE THREAD

**Issue by marcelo386** [wppconnect-team/wa-js#1944]
### WA-JS Version

3.2.6

### WhatsApp Version

2.3000.1013681002-alpha

### Browser Version

101.0.4951.67

### Operation System

windows 10

### Steps to reproduce

error when editing caption file

### What is expected?

editing caption file

### What is actually happening?

not working

### Any additional comments?

  let rawMessage: RawMessage = {
    type: 'protocol',
    subtype: 'message_edit',
    protocolMessageKey: msg.id,
    /*body: newText.trim(),*/
    caption: newText.trim(),
    editMsgType: msg.type,
  };
  
  **msg.type**  
  
  check the type and change it to caption instead of body

**Comment by DXPRO** [comment]
Marcelo, em Steps to reproduce, você coloca o passo a passo com o nome da função que esta usando, assim por mais que o Cleiton esteje ciente, outros usuários podem buscar reproduzir o mesmo caminho, e ajudar nas correções!

**Comment by marcelo386** [comment]
result = WPP.chat.sendFileMessage('5517981388414@c.us', 'data:image/png;base64,iVBOR...', {
    caption: 'TESTE',

 });
 
 console.log(result);
  
 result = WPP.chat.editMessage("true_5517981388414@c.us_3EB0BD26925........", "Caption Novo", {} );
 console.log(result);

já achei a solução vou subir um PR em breve

**Comment by marcelo386** [comment]
https://github.com/wppconnect-team/wa-js/commit/b609a9f4b8cc4eef5b0de6d4ad9a51665bb97ad7
