### ISSUE TITLE
How can we use openContextMenu method CmdClass

### ISSUE THREAD

**Issue by mkamra2000** [wppconnect-team/wa-js#2005]
- Can I use `openContextMenu` to open the context menu with a right-click on a chat node, similar to WhatsApp and how?
![image](https://github.com/wppconnect-team/wa-js/assets/73895535/c5b8504c-4608-400b-9e77-d2c214c9de6e)

**Comment by icleitoncosta** [comment]
This is neither a function nor the purpose of wa-js. The project is to use functions that do not interact directly with the interface. In this case, just for your knowledge, I suggest a trigger on the button when it is clicked on the specific message.

document.getElementsByClassName(.....) is one approach.
