### ISSUE TITLE
Reply to message is not working

### ISSUE THREAD

**Issue by Souhaibahar** [wppconnect-team/wa-js#2049]
### WA-JS Version

3.4.0

### WhatsApp Version

2.3000.1014410277-alpha

### Browser Version

Latest Chrome

### Operation System

Windows 10

### Steps to reproduce

 private async Task<bool> SendMessage(SendRequest request) {
            try {
                var encodedMessage = JavaScriptEncoder.Default.Encode(request.Message);

                var options = "{ markIsRead: true }";
                if (request.CreateChat) {
                    options = "{ createChat: true }";
                } else if (!string.IsNullOrEmpty(request.ReplyToMessageId)) {
                    options = "{ quotedMsg: '_MESSAGE_ID_' }".Replace("_MESSAGE_ID_", request.ReplyToMessageId);
                }

                await Page.EvaluateFunctionAsync(@"async () => { await WPP.chat.sendTextMessage('CONTACT_ID@c.us', '_MESSAGE_', _OPTIONS_) }".Replace("CONTACT_ID", request.Name).Replace("_MESSAGE_", encodedMessage).Replace("_OPTIONS_", options)).ConfigureAwait(false);
                return true;
            } catch (Exception ex) {
                Console.WriteLine(ex.ToString());
                return false;
            }
        }

### What is expected?

To the message be sended as a reply ( when quotedMsg isnot null )
but it's not working

### What is actually happening?

The message is sended succefully but not as a response

**Comment by icleitoncosta** [comment]
The function is working normally. I believe it was related to the isStatusV3 error that was occurring, which I have now fixed. I will close the issue, but if the problem persists (after updating), please reopen the issue.
