### ISSUE TITLE
Error WPP.status.sendTextStatus

### ISSUE THREAD

**Issue by waTools-br** [wppconnect-team/wa-js#2052]
### WA-JS Version

3.4.1

### WhatsApp Version

2.3000.1014528158

### Browser Version

TODOS

### Operation System

WINDOWS

### Steps to reproduce

Realizar a chamada da função para postar o status de texto.

### What is expected?

O status ser postado e ficar visível para os contatos

### What is actually happening?

O status e postado porem não fica visível para nenhum contato e nem para o celular do WhatsApp conectado, no caso ele fica visível apenas no WhatsApp Web!

Qualquer outra função de postar o status funciona corretamente, apenas essa função esta apresentando esse problema!

### Any additional comments?

Sugestão de adição: as funções de postar status de imagem e vídeo... não apresentam um campo de texto sendo que a postagem do status de forma nativa e possível adicionar um texto quando realiza a postagem de um vídeo ou imagem no status... caso seja possível seria interessante essa adição!

**Comment by icleitoncosta** [comment]
Please, test: https://github.com/wppconnect-team/wa-js/pull/2074

**Comment by itshahmir** [comment]
I am still facing this issue
