### ISSUE TITLE
WPP.chat.getMessageACK & WPP.chat.openChatAt return isStatusV3 Error

### ISSUE THREAD

**Issue by ariona** [wppconnect-team/wa-js#2064]
### WA-JS Version

3.4.2-alpha.0

### WhatsApp Version

2.3000.1014610951

### Browser Version

126.0.6478.127

### Operation System

OS X Sonoma

### Steps to reproduce

**WPP.chat.getMessageACK**
1. Send message to get MsgId
2. try getting message ack status with WPP.chat.getMessageACK
3. Some will return ack status
4. Some will return error isStatusV3, even the message is exist

**WPP.chat.openChatAt**
1. Try opening chat at using previous msg id
2. This will also return isStatutsV3

### What is expected?

**WPP.chat.getMessageACK** should return message ACK
**WPP.chat.openChatAt** should open chat and highlight given message id

### What is actually happening?

Return Error and not getting messageStatus
```
TypeError: n.isStatusV3 is not a function
    at t.getMessageById (core.js:2:143907)
    at t.getMessageACK (core.js:2:142840)
    at ui.js:557:20177
    at Array.map (<anonymous>)
    at T (ui.js:557:20000)
    at async L (ui.js:557:20476)
```

The error is at `getMessageById` method (at the end of line):
```
if ((null === (r = null === (t = e.remote) || void 0 === t ? void 0 : t.toString()) || void 0 === r ? void 0 : r.includes("status@broadcast")) || (null === (n = e.remote) || void 0 === n ? void 0 : n.isStatusV3()))
```

**Comment by ethan2cl** [comment]
i got the same problem

**Comment by dionatanfmsilva** [comment]
I have the same problem

Here it occurs in the new_message event when she is replying to a message.

WPP.chat.getQuotedMsgKey

**WAJS:** 3.4.1
**WA:** 2.3000.10145x and 2.3000.10146x

In versions 2.3000.10144x the error does not occur

**Comment by icleitoncosta** [comment]
Fixed by https://github.com/wppconnect-team/wa-js/commit/45713137d5c98013cc6d7b250d4a9835e0158fda
