### ISSUE TITLE
StatusEvent

### ISSUE THREAD

**Issue by renerlemes** [wppconnect-team/wa-js#207]
Como é chamado o registro do evento para saber o status, assim como possui na lib wppconnect-team/wppconnect?

`statusFind: (statusSession, session) => {...`

**Comment by edgardmessias** [comment]
No wa-js ainda não implementei muitos eventos, estou fazendo aos poucos, mas esse em específico acredito que eu não vá implementar, pois existem uns outros prontos que seriam mais úteis do que somente o statusFind

**Comment by renerlemes** [comment]
Eu perguntei por esse por ser mais genérico, mas o que estou procurando são dois, um que é disparado após ler o qrcode com sucesso e outro é quando é lido com sucesso! Eu vi a documentação e fiquei meio confuso com alguns eventos e confesso que foi difícil achar o evento que quando recebe uma mensagem. Poderia colocar alguns aqui, não o exemplo completo, mas o caminho para a utilização deles.
