### ISSUE TITLE
Invalid Invite Code on a valid invite.

### ISSUE THREAD

**Issue by carlosmixz** [wppconnect-team/wa-js#2072]
### WA-JS Version

3.4.1

### WhatsApp Version

2.3000.1014619389

### Browser Version

Chrome 126.0.6478.127

### Operation System

Windows 10

### Steps to reproduce

Just try to enter in some groups, randomly one of them will send the Invalid Invite Code.

### What is expected?

Expected to enter the group and return the id.

### What is actually happening?

Not enter and return "Invalid Invite Code" message.

**Comment by icleitoncosta** [comment]
Hi, can you send the logs?

**Comment by carlosmixz** [comment]
How can i get the logs?

**Comment by icleitoncosta** [comment]
Please send me a link to a group that had an error. It can be something occasional too. I've done some tests on this function, and it hasn't had any issues, but it doesn't hurt to try.

**Comment by carlosmixz** [comment]
It doesn't always happen. Any valid link may or may not work. I tested with several different links.

**Comment by ijro** [comment]
> Please send me a link to a group that had an error. It can be something occasional too. I've done some tests on this function, and it hasn't had any issues, but it doesn't hurt to try.

Thanks for the feedback. Remembering that I try to add the user via add-participant-group and, upon receiving the 403 code, I use the returned field invite_code added to the address https://chat.whatsapp.com/ and send it to the same user using the send- method message (I tried send-link-preview too)

https://chat.whatsapp.com/HD7xHjet7Ev8q7aY

![photo1720700833](https://github.com/wppconnect-team/wa-js/assets/3106673/40cb105d-c957-4ca6-aab9-e5ae1ba6ca94)
![photo1720700849](https://github.com/wppconnect-team/wa-js/assets/3106673/15f601c5-4394-46d0-beb1-49406e039bf1)

**Comment by icleitoncosta** [comment]
> Thanks for the feedback. Remembering that I try to add the user via add-participant-group and, upon receiving the 403 code, I use the returned field invite_code added to the address https://chat.whatsapp.com/ and send it to the same user using the send-message method (I tried send-link-preview too)
> 
> https://chat.whatsapp.com/HD7xHjet7Ev8q7aY

Check issues on wppconnect project

**Comment by icleitoncosta** [comment]
> > Please send me a link to a group that had an error. It can be something occasional too. I've done some tests on this function, and it hasn't had any issues, but it doesn't hurt to try.
> 
> Thanks for the feedback. Remembering that I try to add the user via add-participant-group and, upon receiving the 403 code, I use the returned field invite_code added to the address https://chat.whatsapp.com/ and send it to the same user using the send-message method (I tried send-link-preview too)
> 
> https://chat.whatsapp.com/HD7xHjet7Ev8q7aY
> 
> ![photo1720700833](https://private-user-images.githubusercontent.com/3106673/347815822-40cb105d-c957-4ca6-aab9-e5ae1ba6ca94.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNjk4NjUsIm5iZiI6MTcyMTE2OTU2NSwicGF0aCI6Ii8zMTA2NjczLzM0NzgxNTgyMi00MGNiMTA1ZC1jOTU3LTRjYTYtYWFiOS1lNWFlMWJhNmNhOTQuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDIyMzkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZGZlOGY4YTM2NmQ5MTUxYWYzMTZjNmRjYzM2NWJhMzgxZjdiNDY4OWZmNzcyZTgzZTk4NjhlMDZiYTc5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tUH0Jo4nMK8lVkmIVPoX9C9DEFSPQn2jN5xvxZ2-BEI) ![photo1720700849](https://private-user-images.githubusercontent.com/3106673/347815867-15f601c5-4394-46d0-beb1-49406e039bf1.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNjk4NjUsIm5iZiI6MTcyMTE2OTU2NSwicGF0aCI6Ii8zMTA2NjczLzM0NzgxNTg2Ny0xNWY2MDFjNS00Mzk0LTQ2ZDAtYmViMS00OTQwNmUwMzliZjEuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDIyMzkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjM2JjODY1MDVlNjg2NjljMDBmOGNiZmIwNjcxNDViMDRhMDBjMjRmYmVjYTI2Yjg5Y2JjZmU3YzJhMWU5MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0eAZX_HQ2OqetFhYXwpG47v7WWnLEkL7yyh0cDZKeuY)

For send invite link for chat, is necessary use the function:

```WPP.chat.sendGroupInviteMessage(
 '[number]@c.us',
 {
   inviteCode: '123',
   groupId: '789@g.us'
 }
);```
