### ISSUE TITLE
Publish JS file

### ISSUE THREAD

**Issue by renerlemes** [wppconnect-team/wa-js#209]
Na publicação de uma release, poderia ter a opção de compilar o arquivo js final também

**Comment by edgardmessias** [comment]
Feito.

Para sempre pegar a última versão pode se usar:

* latest: https://github.com/wppconnect-team/wa-js/releases/latest/download/wppconnect-wa.js
* nightly: https://github.com/wppconnect-team/wa-js/releases/download/nightly/wppconnect-wa.js
