### ISSUE TITLE
LID chat está com erros

### ISSUE THREAD

**Issue by carlosmixz** [wppconnect-team/wa-js#2090]
### WA-JS Version

3.4.1

### WhatsApp Version

2.3000.1014776932

### Browser Version

Chrome 126

### Operation System

Windows 10

### Steps to reproduce

Tente abrir o chat usando o openChatBottom com um @lid.

### What is expected?

É esperado que abra o chat com o número de telefone censurado.

### What is actually happening?

Dispara um erro: Unexpected null or undefined: Origin type is missing when creating LID chat.

**Comment by icleitoncosta** [comment]
Olá @carlosmixz , tem um exemplo de lid para que eu possa testar?

**Comment by carlosmixz** [comment]
188656472084493

**Comment by icleitoncosta** [comment]
> 188656472084493

Carlos, tentei te enviar algumas mensagens através desse @lid, poderia verificar se recebeu-as?

**Comment by carlosmixz** [comment]
Não sou dono do número desse @lid. O problema está na função de abrir o chat: openChatBottom, não no envio.

**Comment by bracketsApps007** [comment]
![image](https://github.com/wppconnect-team/wa-js/assets/110741940/4d5c2353-3941-47d4-a725-1010a1b75d43)

**Comment by bracketsApps007** [comment]
![image](https://github.com/wppconnect-team/wa-js/assets/110741940/a3d7ace2-c06a-4ea5-9ae2-9e571933f994)

**Comment by icleitoncosta** [comment]
> Não sou dono do número desse @lid. O problema está na função de abrir o chat: openChatBottom, não no envio.

Sim, porém o erro acontece também no envio, o problema está dentro da função findChat, não adianta eu só resolver o openChatBottom, pois também tem que enviar a mensagem, já que é outro bug que achei no processo, abrir o chat irá funcionar, porém, tentarei descobrir como criar um lid para mim para testar essas funções direito antes de migrar o PR.

**Comment by icleitoncosta** [comment]
Olá, por favor, teste a ultima atualização do wa-js com whatsapp >= 2.3000.1014834790.

O whatsapp corrigiu essa função por ele mesmo (o problema é o que LID não estava de fato implementado por eles), por isso irei fechar a issue, já que foi resolvida nessa ultima versão lançada.

**Comment by bracketsApps007** [comment]
> Olá, por favor, teste a ultima atualização do wa-js com whatsapp >= 2.3000.1014834790.
> 
> O whatsapp corrigiu essa função por ele mesmo (o problema é o que LID não estava de fato implementado por eles), por isso irei fechar a issue, já que foi resolvida nessa ultima versão lançada.

yes, its resolved in latest update
