### ISSUE TITLE
【sendFileMessage】how to send a document with empty caption

### ISSUE THREAD

**Issue by ethan2cl** [wppconnect-team/wa-js#2121]
### WA-JS Version

3.4.2

### WhatsApp Version

2.3000.1014600264-alpha

### Browser Version

Chrome for Testing 124.0.6367.78

### Operation System

OS mac apple m3

### Steps to reproduce

`let rawMessage = await prepareRawMessage<RawMessage>(
    chat,
    {
      caption: options.caption || filename,
      filename: filename,
      footer: options.footer,
      isCaptionByUser: options.caption != undefined,
    },
    options
  );`

In this place, when I send document type messages without caption, filename will be used instead of caption by default. In fact, I just want to send a media message from my phone, just sending a simple document without caption

### What is expected?

 I just want to send a media message from my phone, just sending a simple document without caption

### What is actually happening?

`const params = {
  jid: "xxxx",
  destJid: "xxxx",
  caption: "",
  type: "document",
  mentions: [],
  // urlencodeJsonQuotedMessage: JSON.stringify(
  //   {
  //     type: 5,
  //     content: "",
  //     messageId: "3ACB2C78D1E0E00E6D8B",
  //     fromMe: true,
  //     participant: "8619145767870",
  //     contentQiniuUrl:
  //       "https://xhl-hk-cos01.leadscloud.com/whatsapp_test_bucket/whatsapp/audio/3ACB2C78D1E0E00E6D8B/audio.ogg",
  //   }
  // ),
};`

Even if I set the caption to an empty string, there still exists a situation on my phone where filename is treated as caption
![image](https://github.com/user-attachments/assets/5c015617-fefe-4f37-903f-7f6aa61e1c09)

**Comment by icleitoncosta** [comment]
Hi, you can send file message:

```
// Single document
WPP.chat.sendFileMessage(
 '[number]@c.us',
 'data:application/msword;base64,<a long base64 file...>',
 {
   type: 'document',
   filename: 'myfile.doc',
 }
);
```

Reference: https://wppconnect.io/wa-js/functions/chat.sendFileMessage.html

**Comment by ethan2cl** [comment]
> Hi, Use the function sendFileMessage.
> 
> you can send file message without caption:
> 
> ```
> // Single document
> WPP.chat.sendFileMessage(
>  '[number]@c.us',
>  'data:application/msword;base64,<a long base64 file...>',
>  {
>    type: 'document',
>    filename: 'myfile.doc',
>  }
> );
> ```
> 
> Reference: https://wppconnect.io/wa-js/functions/chat.sendFileMessage.html

I am using the sendFileMessage API. You can take a look at the parameters I uploaded. I did not upload a caption, but the sendFileMessage method defaults to using filename instead of caption. Please help me check the sendFileMessage. Thank you
