### ISSUE TITLE
sendListMessage não está sendo enviada

### ISSUE THREAD

**Issue by luidiva** [wppconnect-team/wa-js#2163]
### WA-JS Version

3.7.0

### WhatsApp Version

2.3000.1015145967

### Browser Version

Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

### Operation System

windows 10

### Steps to reproduce

WPP.chat.sendListMessage('[number]@c.us', {buttonText: 'Click Me!', description: "Hello it's list message",title: 'Hello user', footer: 'Click and choose one', sections: [{title: 'Section 1',rows: [{rowId: 'rowid1',title: 'Row 1',description: "Hello it's description 1",},{rowId: 'rowid2',title: 'Row 2',description: "Hello it's description 2",}]}]});

### What is expected?

que a mensagem seja enviada

### What is actually happening?

A mensagem não é enviada, no whatsapp web aparece o simbolo de alerta avisando "Ocorreu um erro. Clique para saber mais" ao lado da mensagem.
Não dá nenhum erro no console.
O retorno possui o id da mensagem, e sendMsgResult: fulfilled

**Comment by Saifallak** [comment]
Does button Messages still work ? i though it's disabled by Meta (for non-biz users) this year.
