### ISSUE TITLE
WPP.whatsapp.Conn is Undefined causing all method related to WA Business unusable

### ISSUE THREAD

**Issue by ariona** [wppconnect-team/wa-js#2182]
### WA-JS Version

3.8.0

### WhatsApp Version

Version 2.3000.1015262107

### Browser Version

Version 126.0.6478.183

### Operation System

OS X Sonoma

### Steps to reproduce

1. Make sure wa web version is 2.3000.1015262107
2. Use method like WPP.whatsapp.Conn.isSMB
3. Or WPP.whatsapp.LabelStore

### What is expected?

Above methods should return all object/method related to WA Business, like isSMB and LabelStore

### What is actually happening?

Error returned, all those method return undefined,

```
wpp.js:2 Module Conn was not found with e=>e.Conn&&e.ConnImpl
wpp.js:2 Property PresenceCollectionImpl was not found for PresenceCollection in module WAWebPresenceCollection
wpp.js:2 Module PresenceStore was not found with e=>(e.default||e[r])instanceof a[r]
wpp.js:2 Module BlocklistCollection was not found with e=>e.BlocklistCollectionImpl
wpp.js:2 Module BlocklistStore was not found with e=>(e.default||e[r])instanceof a[r]
wpp.js:2 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'on')
    at A.<anonymous> (wpp.js:2:138273)
```

**Comment by dllsystem** [comment]
Same problem here

**Comment by Parveen-Mothsara** [comment]
same problem

**Comment by zerosoul** [comment]
same problem, any progress?

**Comment by ariona** [comment]
Hi @icleitoncosta, sorry to directly mention you. could you take a look at this issue, please. 🙇

**Comment by Parveen-Mothsara** [comment]
Any Solution 🙇 :(

**Comment by icleitoncosta** [comment]
Fixed

**Comment by ariona** [comment]
> Fixed

I  can confirm, the fix is works, many thanks 🙇
