### ISSUE TITLE
await WPP.labels.getAllLabels() error

### ISSUE THREAD

**Issue by bracketsApps007** [wppconnect-team/wa-js#2184]
### WA-JS Version

3.8.1-alpha

### WhatsApp Version

2.3000.1015281983

### Browser Version

Chrome 127

### Operation System

Window 11

### Steps to reproduce

`await WPP.labels.getAllLabels();`

![image](https://github.com/user-attachments/assets/af6f8e59-3ee7-43c8-8a1f-ea93acb9b891)

### What is expected?

List of labels 

### What is actually happening?

SHowing error

**Comment by silemftooh** [comment]
I also had the same problem. Please solve it. Thank you very much.

**Comment by CardosoGit** [comment]
I also had ths same problem.

**Comment by icleitoncosta** [comment]
Fixed
