### ISSUE TITLE
Create event for when chat has been closed

### ISSUE THREAD

**Issue by henriquecm** [wppconnect-team/wa-js#2226]
**Is your feature request related to a problem? Please describe.**
When the user presses `ESC` the chat closes, but there's no event to indicate that.

**Describe the solution you'd like**
Create a new event that would inform that the chat was closed, or update active_chat to return null when the chat is closed.

**Describe alternatives you've considered**
I tried a mutationObserver on the main element to detect if the chat or the home is displaying.

**Additional context**

**Comment by icleitoncosta** [comment]
Try use:

```
WPP.on('chat.active_chat', (chat) => {
  // Your code
});
```

**Comment by henriquecm** [comment]
I've tried that, no event is sent when the chat is closed, only when a chat is open.

**Comment by icleitoncosta** [comment]
Implemented by https://github.com/wppconnect-team/wa-js/commit/8c5ae191a8da3fa665b3104d4ac23bfc681b7eae
