### ISSUE TITLE
Failed to download media resources using 'downloadMedia', causing the process to stop

### ISSUE THREAD

**Issue by depgzh** [wppconnect-team/wa-js#2246]
### WA-JS Version

v3.8.2

### WhatsApp Version

2.3000.1015802715

### Browser Version

127.0.6533.120

### Operation System

win11

### Steps to reproduce

When a certain image in the chat history cannot be viewed due to "Can't view this photo because it's no longer on your phone.". Using downloadMedia to download this resource again will cause an error in the browser, which will stop my operation of downloading other media resources.

### What is expected?

I hope to catch this error

### What is actually happening?

![20240820161141](https://github.com/user-attachments/assets/aee45eb5-f7eb-468d-aadb-d0853554000e)

**Comment by depgzh** [comment]
![20240820161333](https://github.com/user-attachments/assets/8e7fd827-80ec-41a8-96c2-0ceb093813a4)
After checking the source code, it was found that it is most likely caused by this "await"

**Comment by depgzh** [comment]
This await will not block continuously, it will take about one or two minutes to continue

**Comment by depgzh** [comment]
> ![20240820161333](https://private-user-images.githubusercontent.com/90696337/359394071-8e7fd827-80ec-41a8-96c2-0ceb093813a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDcxMjAsIm5iZiI6MTcyNDE0NjgyMCwicGF0aCI6Ii85MDY5NjMzNy8zNTkzOTQwNzEtOGU3ZmQ4MjctODBlYy00MWE4LTk2YzItMGNlYjA5MzgxM2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA5NDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ZWU4MjM0ZmJiYzZiYmQ2YWNhOWIwNTRhNDQ0Yjc5NDhjZjhhMDk0NmMzOWJkMTVmNWY2ODg2MjcxMGI2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yVN_rQf1CQQqCGmeFsWtyc9kyGXmWpCPcYXM2k1_UaE) 
What should I do to obtain the result of this' await '

**Comment by icleitoncosta** [comment]
Thanks for reporting the error, I will check and resolve it
