### ISSUE TITLE
WhatsApp Button Functionality Inconsistent Across Different Numbers

### ISSUE THREAD

**Issue by Ruchitghadiya** [wppconnect-team/wa-js#2253]
### WA-JS Version

v3.8.3

### WhatsApp Version

2.3000.1015851946

### Browser Version

127.0.6533.120

### Operation System

windows

### Steps to reproduce

We've noticed an issue where the WhatsApp button functionality is inconsistent. For some phone numbers, the button works perfectly and initiates the WhatsApp chat as expected. However, for other numbers, it fails to work, and no chat is initiated.

![image_2024_08_21T12_40_08_668Z](https://github.com/user-attachments/assets/7d621f5f-b5ef-4b44-aad3-152cae832de7)

### What is expected?

The WhatsApp button should function consistently across all numbers. When clicked, it should open a chat with the specified phone number in WhatsApp, regardless of the number being used.

### What is actually happening?

The WhatsApp button is working inconsistently. For some phone numbers, the button functions as expected and opens a WhatsApp chat, while for other numbers, it may fail to initiate a chat, not respond at all, or behave unexpectedly.

**Comment by rayaa007** [comment]
You are in past. Buttons are deprecated
