### ISSUE TITLE
WPP.conn.isMainReady() return false

### ISSUE THREAD

**Issue by selvam920** [wppconnect-team/wa-js#2262]
### WA-JS Version

3.8.3

### WhatsApp Version

2.3000.1015947493

### Browser Version

Edge 128.0.2739.42/Chrome 

### Operation System

Win 11

### Steps to reproduce

WPP.conn.isMainReady() return false after login & main page loaded

### What is expected?

should be return true

### What is actually happening?

return false

**Comment by icleitoncosta** [comment]
Fixed by https://github.com/wppconnect-team/wa-js/commit/af5b3981a30f5e9dd53cf0c1bcf84c18d94219d2
