### ISSUE TITLE
How to Delete message for everyone from group ?

### ISSUE THREAD

**Issue by bracketsApps007** [wppconnect-team/wa-js#2300]
How to Delete message for everyone from group ?

the  function `WPP.chat.deleteMessage('[number]@c.us', 'msgid', true, true);` delete a message only for me not for everyone on group

**Comment by jamesxt-94** [comment]
The problem in this file (line 94):
https://github.com/wppconnect-team/wa-js/blob/main/src/chat/functions/deleteMessage.ts

the portion of code: 
```javascript
} else if (revoke && isSentByMe) {
```

only revoking message when isSentByMe. 
It's an error
