### ISSUE TITLE
Button issue with sending messages to URL, phoneNumber, and ID.

### ISSUE THREAD

**Issue by Ruchitghadiya** [wppconnect-team/wa-js#2339]
### WA-JS Version

v3.10.1

### WhatsApp Version

2.3000.1016513787

### Browser Version

127.0.6533.120

### Operation System

windows

### Steps to reproduce

Send button message using provided code:
WPP.chat.sendTextMessage('number@c.us', 'Hello', {
  useInteractiveMessage: true, // False for legacy
  buttons: [
    {
      url: 'https://wppconnect.io/',
      text: 'WPPConnect Site'
    },
    {
      phoneNumber: '+55 11 22334455',
      text: 'Call me'
    },
    {
      id: 'your custom id 1',
      text: 'Some text'
    },
  ],
  title: 'Title text', // Optional
  footer: 'Footer text' // Optional
});

### What is expected?

Button message sent to url, phoneNumber and id three option proper send.

### What is actually happening?

1. **Scenario 1:** Properly sending to URL, phoneNumber, and code.
2. **Scenario 2:** Properly sending to URL and phoneNumber.
3. **Scenario 3:**  Properly sending text to buttons for the two and three ID.
4. **Scenario 4:** Not sending to URL, phoneNumber, and ID.

![image](https://github.com/user-attachments/assets/84d409ca-462f-429f-b739-bf4e4af18645)

**Comment by icleitoncosta** [comment]
The error is clear
Click buttons can only be shipped alone, no other models together.
