### ISSUE TITLE
Quoted Messages is not working?

### ISSUE THREAD

**Issue by willpexeroo** [wppconnect-team/wa-js#2350]
I am currently unable to interpret ANY 'quoted' messages in WPPConnect that come from chats with @lid identifiers. Only chats with @c.us are being recognized. Initially, I thought the issue was with my script, but then I created a 'mini bot' just to monitor all types of incoming messages via onMessage. That's when I realized this flaw. Any alternative solution for this?

**Comment by joseamonteironeto** [comment]
Same issue in here! Found any fix for that?

**Comment by brunolittlesalt** [comment]
just saw this and noticed that this happens with me too ! hoping there's a fix for this soon

**Comment by icleitoncosta** [comment]
Hey, my chats with @lid won't show up.
Will we be able to work together to carry out this fix?

**Comment by icleitoncosta** [comment]
Fixed by https://github.com/wppconnect-team/wa-js/commit/2a40d0126c6c4f16ae27add91f4fc7d1263073af
