### ISSUE TITLE
'MentionedList' with button Message in group is not working

### ISSUE THREAD

**Issue by bracketsApps007** [wppconnect-team/wa-js#2388]
### WA-JS Version

3.10.2-alpha.0

### WhatsApp Version

2.3000.1016909378

### Browser Version

Chrome 130

### Operation System

Window 11

### Steps to reproduce

Try to send Button message to group with mentionedList.

`await WPP.chat.sendTextMessage('XXXXXXX@g.us', 'test message with buttons', {
                    mentionedList:["XXXXX@c.us"],
                    useInteractiveMessage: true,
                    buttons: [{"text":"Link","url":"https://sample-videos.com/download-sample-png-image.php#google_vignette"}],
                    title: 'title',
                    footer: 'footer',
                });`
                
Button works ok . but mentionedList is not

### What is expected?

 mentionedList should work

### What is actually happening?

Its not tagging (mentioning)

**Comment by icleitoncosta** [comment]
The WPPConnect team will not release buttons for groups
