### ISSUE TITLE
Mensagem temporária/ephemeralDuration sempre 0

### ISSUE THREAD

**Issue by carlosmixz** [wppconnect-team/wa-js#2389]
### WA-JS Version

3.10.1

### WhatsApp Version

2.3000.1016915021

### Browser Version

Chrome 129

### Operation System

Windows 11

### Steps to reproduce

WPP.chat.getActiveChat().ephemeralDuration

### What is expected?

Mostrar o tempo das mensagens temporárias

### What is actually happening?

Sempre aparece zerado

**Comment by icleitoncosta** [comment]
Olá @carlosmixz, fiz alguns testes, e está normal. 
Será que não é um problema especifico do whatsapp nessa versão, atualize para uma versão mais recente, o whatsapp está lançando atualizações diárias, e vira e mexe sai algum bug
