### ISSUE TITLE
Como acessar a variável global WPP por meio da minha extensão do Google Chrome

### ISSUE THREAD

**Issue by RodrigoSerrasqueiro** [wppconnect-team/wa-js#2392]
Estou trabalhando em uma extensão do Google Chrome para o Whatsapp Web. Já consigo injetar o script de wppconnect-wa.js dentro da página e a variável WPP já fica disponível através das ferramentas do desenvolvedor. Porém, estou tendo dificuldades em acessar essa variável através do código da minha extensão. Pesquisei sobre o assunto e descobri que isso acontece pois o script é adicionado a um contexto diferente do contexto da extensão. Então, gostaria de saber se existe alguma maneira de resolver isso.

**Comment by icleitoncosta** [comment]
> Estou trabalhando em uma extensão do Google Chrome para o Whatsapp Web. Já consigo injetar o script de wppconnect-wa.js dentro da página e a variável WPP já fica disponível através das ferramentas do desenvolvedor. Porém, estou tendo dificuldades em acessar essa variável através do código da minha extensão. Pesquisei sobre o assunto e descobri que isso acontece pois o script é adicionado a um contexto diferente do contexto da extensão. Então, gostaria de saber se existe alguma maneira de resolver isso.

Olá rodrigo, o WPP fica dentro da variável window. 
Então dentro da extensão, quando a fizer é só chamar a variável window.WPP que irá te trazer as funções necessárias
