### ISSUE TITLE
Not allowed more then three buttons in file messages - When Button count is 3 already

### ISSUE THREAD

**Issue by bracketsApps007** [wppconnect-team/wa-js#2395]
### WA-JS Version

3.10.2-alpha.0

### WhatsApp Version

2.3000.1016983418

### Browser Version

Chrome 130

### Operation System

Window 11

### Steps to reproduce

![image](https://github.com/user-attachments/assets/2fea65b9-a125-40b3-a14a-9382cca039c2)

`WPP.chat.sendFileMessage('XXXXXXXXXX@c.us',`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAIAAADTED8xAAADMElEQVR4nOzVwQnAIBQFQYXff81RUkQCOyDj1YOPnbXWPmeTRef+/3O/OyBjzh3CD95BfqICMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMK0CMO0TAAD//2Anhf4QtqobAAAAAElFTkSuQmCC`,
                         {
                             type: 'image',
                             caption: `test`,
                             filename: `Logo80.png`,
                             createChat:true,
                             useInteractiveMessage: true,
                             buttons: 
                                 [  
                                     {text: 'abc','url': 'https://www.google.com/'} , 
                                     {text: 'now','url': 'https://www.google.com/'} , 
                                     {text: 'rec','url': 'https://www.google.com/'} 
                                 ]
                                 ,title: `join`
                                 ,footer:`demo text`});`

### What is expected?

Should Send button message

### What is actually happening?

Showing error  Not allowed more then three buttons in file messages

**Comment by icleitoncosta** [comment]
The error message is incorrect.
Unfortunately, with files, you can only place 2 buttons to ensure compatibility across all devices.
