### ISSUE TITLE
Add/Edit Business Label not working. 

### ISSUE THREAD

**Issue by trexsiddharth** [wppconnect-team/wa-js#2439]
### WA-JS Version

3.11.0

### WhatsApp Version

2.3000.1017582984

### Browser Version

129.0.6668.103 (Official Build) (arm64)

### Operation System

Mac Os Sonoma 14.6.1

### Steps to reproduce

WPP.labels.addNewLabel
WPP.labels.editLabel

### What is expected?

It should create / edit new business label on web whatsapp and whatsapp mobile.

### What is actually happening?

its creating/editing a business label locally but on refreshing whatsapp it disappears.
Neither is it being made on the whatsapp mobile.

**Comment by icleitoncosta** [comment]
How are you calling the function?
