### ISSUE TITLE
Relative time info displayed as Spanish Language

### ISSUE THREAD

**Issue by ariona** [wppconnect-team/wa-js#2443]
### WA-JS Version

3.11.0

### WhatsApp Version

2.3000.1017589883

### Browser Version

129.0.6668.90 (Official Build) (arm64)

### Operation System

OS X Sonoma

### Steps to reproduce

Some time relative label displayed in spanish languages
<img width="199" alt="Screenshot 2024-10-24 at 08 13 55" src="https://github.com/user-attachments/assets/b4362de8-f7c2-4052-9e4b-59fd2b8b4a6b">
<img width="142" alt="Screenshot 2024-10-24 at 08 13 11" src="https://github.com/user-attachments/assets/5bc26ef5-646c-44c5-8354-ecd03d8b35ba">

### What is expected?

Languange should follow system language. On my current system is English then it should be in english

### What is actually happening?

Time relative label is displayed in spanish

**Comment by icleitoncosta** [comment]
Hi, are you using wa-version in your project or only wa-js?

**Comment by ariona** [comment]
hi, what do you mean by using wa-version?
But this seems to be resolved, but sometime it become spanish again

**Comment by icleitoncosta** [comment]
I'm running tests. What language is the device you're using in?

**Comment by ariona** [comment]
> I'm running tests. What language is the device you're using in?

English, but now it's fixed, i still can reproduce the issue. this happened sometimes
