### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'm')     at Object.searchId (index.ts:294:40)

### ISSUE THREAD

**Issue by abdullahhosenakash** [wppconnect-team/wa-js#2445]
### WA-JS Version

3.11.0

### WhatsApp Version

 2.3000.1017630779

### Browser Version

Version 1.71.114 Chromium: 130.0.6723.58 (Official Build) (64-bit)

### Operation System

Ubuntu 22.04

### Steps to reproduce

Fix the issue about webpackRequire

### What is expected?

wepackRequire.m should not say cannot read properties of undefined 'm'

### What is actually happening?

webpackRequire is undefined

**Comment by abdullahhosenakash** [comment]
I actually cloned the repo and followed the instruction
npm install > npm run build:dev
included the wppconnect-wa.js file in the manifest.json contentscript and console.log to the contentscript file about window.wpp and saw the webpack object. but when called the function window.WPP.chat.sendTextMessage('[number]@c.us', message, {options here}). 
Then saw in the console that Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'm') at Object.searchId (index.ts:294:40)
in the indext.ts file I saw the webpackRequire.m in present there. Don't know how to resolve it. please help.
Thank in advance and pardon me if I make any mistake.

**Comment by icleitoncosta** [comment]
Hi @abdullahhosenakash 
It seems like this is your first time using WAJS, right?

I suggest you get the file directly from here (latest version), and take its contents and paste it directly into the Browser Console and test the functions. Start like this, or if you want to use something more complete, use TamperMonkey

Latest version:
https://github.com/wppconnect-team/wa-js/releases/download/v3.12.0/wppconnect-wa.js

**Comment by abdullahhosenakash** [comment]
Thank you so much replying my comment. I will definitely check this in the next working day and let you know the result.

**Comment by abdullahhosenakash** [comment]
I have pasted the contents of file to the browser console and it it working fine. But when i tried to use in my chrome extension again the same error occurs. Will you please guide me how can i use this code in my extension?

**Comment by icleitoncosta** [comment]
I’m not the best person to help you solve this issue since it's been a few years since I last developed Chrome extensions. However, it seems you’re facing a basic injection configuration issue, as most users run it directly in the browser.

I suggest joining our WhatsApp/Discord groups to see if someone else can assist you better. You can find the links on the project’s homepage on GitHub.
