### ISSUE TITLE
Customer Notes Field for Quick Context Overview

### ISSUE THREAD

**Issue by ImPedro29** [wppconnect-team/wa-js#2468]
Problem
Without a "customer notes" field, human agents need to read entire chat histories to get context. This slows down response time, as they lack a quick summary.

Solution
Add a "Customer Notes" field where the AI co-pilot can log brief conversation summaries. This would give agents an at-a-glance overview, keeping them informed without lengthy review.

Alternatives
Using an external database for notes, but it complicates workflow and doesn’t offer the same quick accessibility as an integrated solution.

Additional context
An in-app notes field would streamline workflows, letting agents quickly understand each client’s needs with AI-generated summaries.

**Comment by icleitoncosta** [comment]
Implemented functions by https://github.com/wppconnect-team/wa-js/commit/4f64e4ed554e83857994a18868bd7c6b1a138682
