### ISSUE TITLE
How can I listen for when unread messages in a conversation have been marked as read?

### ISSUE THREAD

**Issue by flyingkang** [wppconnect-team/wa-js#2478]
How can I listen for when unread messages in a conversation have been marked as read?
If I read unread messages on another device, can I listen for when those messages have been marked as read on the web? Is there an API for this?

**Comment by icleitoncosta** [comment]
```
await WPP.on('chat.msg_ack_change', (ack) => console.log(ack));
```

**Comment by flyingkang** [comment]
This method listens for status changes of the messages I send out. However, I want to listen for when messages sent by others are marked as read. In other words, I want to detect when the unread message count in the conversation list disappears. When that unread count disappears, I want to perform some actions.
