### ISSUE TITLE
 Error: findOrCreateLatestChat: could not find phone number for lid while enforcing pre-migration rules

### ISSUE THREAD

**Issue by bracketsApps007** [wppconnect-team/wa-js#2480]
### WA-JS Version

3.14.1-alpha.0

### WhatsApp Version

2.3000.1018043676

### Browser Version

Chrome 130

### Operation System

Window 11

### Steps to reproduce

1) try to get any LID from any community 

2) WPP.chat.sendTextMessage('103929719304330@lid', 'hi', {
				  createChat: true
				})

### What is expected?

Send message to xxxxxxxxx@lid 

### What is actually happening?

![image](https://github.com/user-attachments/assets/6173cfdc-81c6-4dec-9385-754e08c829f8)

**Comment by carlosmixz** [comment]
Same than #2472
