### ISSUE TITLE
Buttons Not Showing in WhatsApp App After Update to v 2.24.22.79

### ISSUE THREAD

**Issue by eduardoff19** [wppconnect-team/wa-js#2484]
### WA-JS Version

3.14.1

### WhatsApp Version

2.24.22.79

### Browser Version

130.0.6723.3

### Operation System

Windows 11

### Steps to reproduce

The buttons are not appearing in the WhatsApp app after the app update. It is possible to send the buttons, and they show up in the WhatsApp Web version, but they do not appear in the app.

### What is expected?

make the buttons appear on android devices

### What is actually happening?

buttons appear on the web version and not on the mobile device

**Comment by icleitoncosta** [comment]
Yes, they're not working; we've been aware of it for almost a month. I haven't had enough time to study another solution yet, especially because I need a rooted Android phone for testing (and I don't have one). But the buttons are something we don't officially maintain in the API, so maybe we'll be able to make them work again soon, but there are no plans at the moment.

**Comment by eduardoff19** [comment]
Hello, friend, thanks for the feedback and effort, I can suggest an android emulator for pc, I use NoxPlayer which is better than BlueStacks, in NoxPlayer By default, Nox is without root. But you can easily turn it to root mode in Nox System Settings >> Common Settings >> Choose Open in the Start Root drop-down list >> Click Save… follow the link: https://pt.bignox.com/ good luck friend, and I hope you find a solution

**Comment by eduardoff19** [comment]
![image](https://github.com/user-attachments/assets/ad683a18-e6bf-4ce9-8dce-97ebe9dce7a0)
![image](https://github.com/user-attachments/assets/d5c2b021-9756-4d80-8e39-8fce6a60d934)

**Comment by icleitoncosta** [comment]
Thank you, i will try ths way

**Comment by eduardoff19** [comment]
Thank you @icleitoncosta  Can you tell me any other project that is running interactive buttons? I still see many domestic companies that use buttons and do not use a WhatsApp template or HSM that sends buttons. It is a very good solution and it would be good to have it working on mobile devices again.

**Comment by icleitoncosta** [comment]
> Thank you @icleitoncosta  Can you tell me any other project that is running interactive buttons? I still see many domestic companies that use buttons and do not use a WhatsApp template or HSM that sends buttons. It is a very good solution and it would be good to have it working on mobile devices again.

In an easier way for me, if you send me those contacts that send the buttons, I can try to figure out what they do, but I must confess I’m really short on time.

The saddest part about the buttons is that if I add some code to the project, within weeks it spreads to other projects (without giving credit, haha), and on top of that, it gets to Meta, and they block everything we’ve done.

**Comment by eduardoff19** [comment]
https://github.com/wppconnect-team/wa-js/issues/2484#issuecomment-2484453112 I really appreciate it my friend, and we would be very happy if you can get some solution, the number I witnessed is +55 800 649 9800 is the number that is sending buttons normally and appears on the cell phone and it is not an official verified account, maybe it can help. thanks for the time and I know it is very accurate.

**Comment by eduardoff19** [comment]
![image](https://github.com/user-attachments/assets/ee6d377b-54fa-4b7c-b58b-bbda0ad074aa)

**Comment by eduardoff19** [comment]
Alguma novidade meu amigo @icleitoncosta algo que possamos te ajudar?

**Comment by leandroveronezi** [comment]
Any solution to the case?
