### ISSUE TITLE
await WPP.chat.list({onlyUsers: true}); Returns Empty array

### ISSUE THREAD

**Issue by bracketsApps007** [wppconnect-team/wa-js#2490]
### WA-JS Version

3.14.2-alpha.0

### WhatsApp Version

2.3000.1018197845

### Browser Version

Chrome 130

### Operation System

Window 11

### Steps to reproduce

`await WPP.chat.list({onlyUsers: true});`

![image](https://github.com/user-attachments/assets/9daf6109-a40a-457b-845e-5d46341aa74d)

### What is expected?

Return LIst of only users

### What is actually happening?

empty array

**Comment by silemftooh** [comment]
All function that contain "isUser"  not working

**Comment by bracketsApps007** [comment]
> All function that contain "isUser" not working

becaus of this 
https://github.com/wppconnect-team/wa-js/issues/2491

**Comment by icleitoncosta** [comment]
Fixed with https://github.com/wppconnect-team/wa-js/commit/d87ea3d302b8b3da780dc8ba607de4ba655e3c7a
