### ISSUE TITLE
New WhatsApp update: labels (tags) are not working.

### ISSUE THREAD

**Issue by mbf-dev** [wppconnect-team/wa-js#2500]
### WA-JS Version

nightly

### WhatsApp Version

2.3000.1018268928

### Browser Version

Chrome

### Operation System

Windows

### Steps to reproduce

Using the latest version, including the nightly version, it still doesn't work.

### What is expected?

New WhatsApp update: labels (tags) are not working, it doesn't filter groups either. Do you have any updates, please?

### What is actually happening?

New WhatsApp update: labels (tags) are not working, it doesn't filter groups either. Do you have any updates, please?

**Comment by smukideejeah** [comment]
i guess this:

```javascript
WPP.chat.setChatList("labels",[1]) //this
WPP.chat.setChatList("labels","1") //or maybe this way

//it's not working

```
