### ISSUE TITLE
Is is possible to auto add default footer message in each message after user sends any text message ?

### ISSUE THREAD

**Issue by bracketsApps007** [wppconnect-team/wa-js#2504]
Is is possible to auto add default footer message in each message after user sends any text message ?

![ezgif-7-5c62d01c2e](https://github.com/user-attachments/assets/631d117c-7ae9-4401-a0be-839600b32128)

**Comment by DXPRO** [comment]
This is something you do yourself in your application, just combine the argument with the user's message and your default message if the user is in a trial period!

**Comment by DXPRO** [comment]
You can use the function to edit a message!

I'll leave a Javascript code model below, which will work very well after you inject the wppconnect-wajs content into the console:

```
(function () {
    // Footer to be added
    const footer = "\n*Footer*: *_Submitted by WPP_*";

    // Initializes the global array for events, if it does not already exist
    window.EVENTSWPP = window.EVENTSWPP || [];
    const messagesProcessed = new Set(); // Stores the IDs of already processed messages

    // Monitor all events on WhatsApp Web
    WPP.onAny(function (event, value) {
        window.EVENTSWPP.push({
            event: event,
            value: value
        });
    });

    // Function to process message events
    async function processEvents() {
        // Filters only events of type 'chat.new_message'
        const newEvents = window.EVENTSWPP.filter(evt => evt.event === "chat.new_message");

        // Iterates over the events found
        for (const evt of newEvents) {
            const { value } = evt;

            // Checks if the event has the __x_id object
            if (value && value.__x_id) {
                const { __x_id, __x_body } = value;

                // Checks if the message was sent by you (fromMe === true)
                if (__x_id.fromMe) {
                    // Gets the value of _serialized and checks the message body (__x_body)
                    const serializedId = __x_id._serialized;

                    // Checks if the message ID has already been processed
                    if (messagesProcessed.has(serializedId)) {
                        console.log(`Message with ID ${serializedId} already processed, ignoring.`);
                        continue; // Ignores already processed messages
                    }

                    const body = __x_body;

                    if (body && body.trim() !== "") {
                        // Avoid duplicating the footer by comparing the current text
                        if (!body.endsWith(footer.trim())) {
                            const newText = body + footer;

                            try {
                                // Attempt to edit the message
                                await WPP.chat.editMessage(serializedId, newText);
                                console.log(`Edited message: ${newText}`);
                            } catch (error) {
                                console.error(
                                    `Failed to edit message with ID ${serializedId}: ${error.message}`
                                );
                            }
                        } else {
                            console.log(`Footer already present in the message with ID ${serializedId}, ignoring.`);
                        }

                        // Mark the message ID as processed
                        messagesProcessed.add(serializedId);
                    } else {
                        console.log(`Empty or null message body, ignoring message with ID ${serializedId}.`);
                    }
                }
            }

            // Remove the processed event from the list to avoid future duplication
            const index = window.EVENTSWPP.indexOf(evt);
            if (index > -1) window.EVENTSWPP.splice(index, 1);
        }
    }

    // Checks and processes events every 1 second
    setInterval(processEvents, 1000);
})();
```


After inserting this code into WhatsApp web, any text message you send, the javascript will edit it including the Footer!

**Comment by bracketsApps007** [comment]
> You can use the function to edit a message!
> 
> I'll leave a Javascript code model below, which will work very well after you inject the wppconnect-wajs content into the console:
> 
> ```
> (function () {
>     // Footer to be added
>     const footer = "\n*Footer*: *_Submitted by WPP_*";
> 
>     // Initializes the global array for events, if it does not already exist
>     window.EVENTSWPP = window.EVENTSWPP || [];
>     const messagesProcessed = new Set(); // Stores the IDs of already processed messages
> 
>     // Monitor all events on WhatsApp Web
>     WPP.onAny(function (event, value) {
>         window.EVENTSWPP.push({
>             event: event,
>             value: value
>         });
>     });
> 
>     // Function to process message events
>     async function processEvents() {
>         // Filters only events of type 'chat.new_message'
>         const newEvents = window.EVENTSWPP.filter(evt => evt.event === "chat.new_message");
> 
>         // Iterates over the events found
>         for (const evt of newEvents) {
>             const { value } = evt;
> 
>             // Checks if the event has the __x_id object
>             if (value && value.__x_id) {
>                 const { __x_id, __x_body } = value;
> 
>                 // Checks if the message was sent by you (fromMe === true)
>                 if (__x_id.fromMe) {
>                     // Gets the value of _serialized and checks the message body (__x_body)
>                     const serializedId = __x_id._serialized;
> 
>                     // Checks if the message ID has already been processed
>                     if (messagesProcessed.has(serializedId)) {
>                         console.log(`Message with ID ${serializedId} already processed, ignoring.`);
>                         continue; // Ignores already processed messages
>                     }
> 
>                     const body = __x_body;
> 
>                     if (body && body.trim() !== "") {
>                         // Avoid duplicating the footer by comparing the current text
>                         if (!body.endsWith(footer.trim())) {
>                             const newText = body + footer;
> 
>                             try {
>                                 // Attempt to edit the message
>                                 await WPP.chat.editMessage(serializedId, newText);
>                                 console.log(`Edited message: ${newText}`);
>                             } catch (error) {
>                                 console.error(
>                                     `Failed to edit message with ID ${serializedId}: ${error.message}`
>                                 );
>                             }
>                         } else {
>                             console.log(`Footer already present in the message with ID ${serializedId}, ignoring.`);
>                         }
> 
>                         // Mark the message ID as processed
>                         messagesProcessed.add(serializedId);
>                     } else {
>                         console.log(`Empty or null message body, ignoring message with ID ${serializedId}.`);
>                     }
>                 }
>             }
> 
>             // Remove the processed event from the list to avoid future duplication
>             const index = window.EVENTSWPP.indexOf(evt);
>             if (index > -1) window.EVENTSWPP.splice(index, 1);
>         }
>     }
> 
>     // Checks and processes events every 1 second
>     setInterval(processEvents, 1000);
> })();
> ```
> 
> After inserting this code into WhatsApp web, any text message you send, the javascript will edit it including the Footer!

Edit a message is secondery option , i was looking for modify the message before sending it.. anyways ! 
Thanks for the solution i wrote  anither script based on your logic 

```
const header="header\n";
const footer="\nfooter";
WPP.on('chat.new_message', async function(msg){
    if(msg.__x_id.fromMe)
    {
        const serializedId =msg.__x_id._serialized;
        const newText =  header + msg.__x_body + footer;
		
		let ifError=true;
		
		function sleep(ms) {
			return new Promise(resolve => setTimeout(resolve, ms));
		}
		
		while (ifError)
		{
			try
			{
				console.log('checking');
				await WPP.chat.editMessage(serializedId, newText);
				ifError=false;
			}
			catch(err)
			{
				 await sleep(400);
				 ifError=true;
				 console.log('error');
			}
		}
			
    }
})
```

**Comment by erSurajMahajan** [comment]
you also can try something like this


```
WPP.on('chat.active_chat', (msg) => {
	(function(){
	var a, e, f;
	e="--header--";
	a = document.querySelector("#main > footer div[contenteditable]");
	a.addEventListener("keydown", function(evt) {
		if(a.innerText.indexOf(e) ==-1 && evt.key !="Backspace")
		{
			 var i, s;
		var n = new MouseEvent("click", {
						  view: window,
						  bubbles: !0,
						  cancelable: !0
						});

		a.dispatchEvent(n);
		i = new DataTransfer;
		window.getSelection().selectAllChildren(a);
		 i.setData("text/plain", "".concat(e, " ").concat(a.innerText));
		 s = new ClipboardEvent("paste", {
								  clipboardData: i,
								  bubbles: !0
								})

		a.dispatchEvent(s);
		 setTimeout((function () {
								  i.clearData()
								}), 200);
		}
	   

	});
	})();
});
```
