### ISSUE TITLE
I want to create a custome filters like "friends", "office colleagues", "leads", etc. How can i create one

### ISSUE THREAD

**Issue by Khushal-Batham** [wppconnect-team/wa-js#2507]
Filters are not working.
Is there any way to filter chats based. 

**Describe the solution you'd like**
I can create a custome filter and add contact/chats in it. Such that it can organise my contacts. There can be some method or way or function through which I can create new filter and chatlist

**Describe alternatives you've considered**
Till now, we are using __x_shouldAppearInList, shouldAppearInList method.

**Comment by icleitoncosta** [comment]
Please, test the PR https://github.com/wppconnect-team/wa-js/pull/2498

**Comment by icleitoncosta** [comment]
Already merge PR, you can use WPP.chat.setChatList function
