### ISSUE TITLE
sent file with extention '.apk', its showing BIN file at receivers end not as APK file

### ISSUE THREAD

**Issue by bracketsApps007** [wppconnect-team/wa-js#2527]
### WA-JS Version

3.15.2-alpha.0

### WhatsApp Version

 2.3000.1018416734

### Browser Version

Chrome 131

### Operation System

Window 11

### Steps to reproduce

1) Send  ay apk file - `WPP.chat.sendFileMessage('XXXXXXXXXX@c.us' ,'data:application/octet-stream;base64,UEsDBBQAAAA.....{LONG_APK_FILE_BASE64_HERE}',{type: 'document',caption: '',filename: 'bitbar-sample-app.apk',createChat: true});`

2) Its Showing as bin file
![image](https://github.com/user-attachments/assets/4069dae3-83a4-4d88-9295-544fd746ee8b)

### What is expected?

![image](https://github.com/user-attachments/assets/da8752e2-e0d8-4d81-8987-71c84b0c9886)

### What is actually happening?

Showing BIN file

**Comment by DXPRO** [comment]
For it to work as expected, you need to change the Data Type: Currently you are using it like this:
data:application/octet-stream

Replace with:
data:file/zip

**Comment by bracketsApps007** [comment]
this is perfect ! working. thanks a lot

**Comment by bracketsApps007** [comment]
its working but APK file is not opening...

![image](https://github.com/user-attachments/assets/b5ea7a14-603a-41fb-9ea6-c9d1da7bb241)

where as if i send apk file manually, then is working find

**Comment by DXPRO** [comment]
Sorry, use the following Data Type:

data:application/vnd.android.package-archive

**Comment by bracketsApps007** [comment]
its working ..! tanks a lott
