### ISSUE TITLE
sendTextMessage to Channel/Newsletter not working

### ISSUE THREAD

**Issue by danukidd** [wppconnect-team/wa-js#2528]
### WA-JS Version

3.15.0

### WhatsApp Version

2.3000.1018416734

### Browser Version

Chrome Version 130.0.6723.117

### Operation System

macOS Sonoma 14.5

### Steps to reproduce

await WPP.chat.sendTextMessage('xxx@newsletter', '👍', {
  createChat: true
});

### What is expected?

Send text message to channel/newsletter.

### What is actually happening?

I tried to send a sendTextMessage with the id xxx@newsletter but it didn't work and an exclamation mark icon appeared like this image.

![image](https://github.com/user-attachments/assets/cbc09b85-d780-445b-94b1-cfd31e23877e)

**Comment by DXPRO** [comment]
I did this test, in fact the first time I sent this error, when I clicked on the exclamation mark and pressed to try again the message was sent!
