### ISSUE TITLE
Sending Message or Attachment to group chat isn't working

### ISSUE THREAD

**Issue by mkamra2000** [wppconnect-team/wa-js#2533]
### WA-JS Version

3.15.1

### WhatsApp Version

2.3000.1018445780

### Browser Version

Chrome 131.0.6778.86

### Operation System

Windows 11

### Steps to reproduce

Run `WPP.chat.sendTextMessage(chat.id.user, "Hi")` with any group chat id

### What is expected?

It should send message by running `WPP.chat.sendTextMessage(chat.id.user, "Hi")` 

### What is actually happening?

On running `WPP.chat.sendTextMessage(chat.id.user, "Hi")` Showing following error:-
![image](https://github.com/user-attachments/assets/b154079a-cb18-49e0-83e0-a7348ba50532)

### Any additional comments?
Although it's working perfectly, if we are using serialized id `chat.id._serialized`

**Comment by ariona** [comment]
First parameter should be in format `id@c.us` or `id@g.us` for group or you can use _serialized property.

```
WPP.chat.sendTextMessage(chat.id._serialized, "Hi")
```

**Comment by mkamra2000** [comment]
Yeah, using the `_serialized` ID is working properly. 

However, in the codebase, I was previously using `chat.id.user`, and it worked fine at that time. Do I need to update the implementation to use `_serialized` IDs now?
