### ISSUE TITLE
Group mention participants are not showing on iPhone devices.

### ISSUE THREAD

**Issue by Ruchitghadiya** [wppconnect-team/wa-js#2540]
### WA-JS Version

v3.15.1

### WhatsApp Version

2.3000.1018458657

### Browser Version

127.0.6533.120

### Operation System

windows

### Steps to reproduce

1. Open the group chat on an Android device.
2. Use the mention feature (@) to tag participants; it works as expected.
3. Repeat the same steps on an iPhone device.
4. The mention feature does not display participants on the iPhone.
Iphone pic =
![WhatsApp Image 2024-11-25 at 11 50 04 AM](https://github.com/user-attachments/assets/6776e870-30e1-450f-8f2c-15b447b5b4e2)

Android pic = 
![WhatsApp Image 2024-11-25 at 11 49 01 AM](https://github.com/user-attachments/assets/6933df08-5f5e-42de-a67a-cb0b4ebd4d12)

### What is expected?

The mention feature (@) should display a list of participants on iPhone devices, similar to how it works on Android.

### What is actually happening?

The mention feature (@) does not display any participants on iPhone devices, but it works correctly on Android.

### Any additional comments?

WPP.chat.sendTextMessage(chatId, data.message, { createChat: true, mentionedList: data.mentionedList, });

**Comment by icleitoncosta** [comment]
Hey @Ruchitghadiya , for u use mentioned, send like this:
WPP.chat.sendTextMessage(chatId, 'Hello @number, { createChat: true, mentionedList: ['number@c.us'], });

Apparently, ghost tags are being fixed by WhatsApp, so you will have to tag directly in the message as well.
