### ISSUE TITLE
Como pegar a lista de chats?

### ISSUE THREAD

**Issue by GustavoDMS** [wppconnect-team/wa-js#271]
No wapi existe a função getAllChats que pega a lista de chats no side-panel, porem não achei nada semelhante aqui.
Estou tentando contribui com a lib em c# mas estou meio perdido no wa-js.

**Comment by edgardmessias** [comment]
Closed by https://github.com/wppconnect-team/wa-js/commit/8657dd1d896f7856d28aeac47c076b4f2dfc4b9b
