### ISSUE TITLE
Como obter o status de uma sessão 

### ISSUE THREAD

**Issue by DXPRO** [wppconnect-team/wa-js#292]
É de muita importância, uma função que pudesse verificar o estado atual de uma sessão, se o celular está desconectado ou o se o computador está desconectado por exemplo!

**Comment by edgardmessias** [comment]
Atualmente existe o `WPP.conn.isAuthenticated` para validar se está autenticado

**Comment by edgardmessias** [comment]
Hoje existe várias funções para verificar isso, veja em https://wppconnect.io/wa-js/modules/conn.html
