### ISSUE TITLE
ERROR: await WPP.contact.queryExists

### ISSUE THREAD

**Issue by DXPRO** [wppconnect-team/wa-js#347]
Na manhã desta Sexta-feira - 22/04/2022 a função **(WPP.contact.queryExists)** para verificar a existencia de uma número passou a retornar o erro abaixo:

Uncaught Module Features not found with e=>{var t,r;return(null===(t=e.GK)||void 0===t?void 0:t.supportsFeature)||(null===(r=e.default)||void 0===r?void 0:r.supportsFeature)}

**Comment by lianyu6569** [comment]
same+1

**Comment by pablodosreis** [comment]
+1

**Comment by edgardmessias** [comment]
This problem was solved with this commit: https://github.com/wppconnect-team/wa-js/commit/0b464e8eafa66adf5bfe3488f0ba467747ccebb5

Today I will release a new release

**Comment by pablodosreis** [comment]
Hi @edgardmessias 

I've update the wa-js but the problem keep on my whatsapp.
I'm on whatsapp version 2.2214.9

I could see in the commit that you talk about 2.2214.8 version

**Comment by edgardmessias** [comment]
@DXPRO , could you check with the latest release? Reopen if the problem persist
