### ISSUE TITLE
Running on chrome extension

### ISSUE THREAD

**Issue by JimmyBastos** [wppconnect-team/wa-js#348]
When i try to load wppconnect-wa.js using manifest.json content scripts, the WPP gets available in the window object and then disappears. The status never changes for ready. 

```json
// manifest.json
{
  "manifest_version": 3,
  "name": "Hitter",
  "homepage_url": "https://hitter.pro",
  "description": "Acelere as suas vendas no WhatsApp!",
  "update_url": "https://clients2.google.com/service/update2/crx",
  "version": "0.0.1",
  "permissions": [
    "tabs",
    "storage",
    "webNavigation",
    "unlimitedStorage",
    "downloads"
  ],
  "action": {
    "default_popup": "index.html",
    "default_title": "React Browser Extension Template"
  },
  "web_accessible_resources": [
    {
      "matches": [
        "*://web.whatsapp.com/*"
      ],
      "resources": [
        "static/js/content.bundle.js"
      ]
    }
  ],
  "background": {
    "service_worker": "static/js/worker.bundle.js"
  },
  "content_scripts": [
    {
      "matches": [
        "*://web.whatsapp.com/*"
      ],
      "js": [
        "static/js/wppconnect-wa.js",
        "static/js/content.bundle.js"
      ]
    }
  ],
  "commands": {
    "_execute_browser_action": {
      "suggested_key": {
        "default": "Ctrl+Shift+H",
        "mac": "MacCtrl+Shift+H",
        "linux": "Ctrl+Shift+H",
        "windows": "Alt+Shift+H"
      },
      "description": "Abre o Hitter"
    }
  },
  "key": ""
}

```

**Comment by uhzair** [comment]
Content scripts injected using the declarative method have a separate window object than the page. Injecting using the manifest.json won't allow wa-js to access whatsapp web internals, you need to inject it programmatically. Here's how I do that:

```
let scriptEl = document.createElement("script");
scriptEl.src = chrome.runtime.getURL("assets/js/vendor/wpp.js");
(document.head || document.documentElement).appendChild(scriptEl);
```

**Comment by rahulbansal16** [comment]
@uhzair Thanks this works. What happens to the separate window object? Does it stay un referenced and garbage collected?

**Comment by uhzair** [comment]
Hey @rahulbansal16, I was incorrect there, content scripts don't have a separate window object; they just run in isolated environment and the window object is isolated from content-scripts. You can read more about that [here](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#isolated_world)

**Comment by rahulbansal16** [comment]
@uhzair so content scripts run in isolated form but they can access the dom. Is there a way to communicate or share the functions between the content scripts and the page scripts?
