### ISSUE TITLE
WPP.whatsapp.LabelStore - Esta listando Etiquetas Inexistentes

### ISSUE THREAD

**Issue by DXPRO** [wppconnect-team/wa-js#365]
Ao utilizar a função **WPP.whatsapp.LabelStore** para buscar as etiquetas criadas em minha conta Bussiness, me deparo com a situação da mesma buscar etiquetas que já foram excluidas anteriormente!

**Comment by edgardmessias** [comment]
Acredito que isso seja apenas problema de sincronia entre a web e o celular
