### ISSUE TITLE
status message ack, como pegar o retorno se a mensagem foi entregue e se foi visualizada para o id único da messagem 

### ISSUE THREAD

**Issue by marcelo386** [wppconnect-team/wa-js#370]
Exemplo que encontrei na internet 

{ // It has the same JSON payload as /messages has
  // Sending to POST JSON body
    "messages": [{
        //unique id
        "id": "false_17472822486@c.us_DF38E6A25B42CC8CCE57EC40F",
        //text message for type "chat" or link to download the file for "ptt", "image", "audio" and "document"
        "body": "Ok!",
        //type of the message - "chat" - text, "image" - image, "ptt" - voice, "document" - text document, "audio" - audio file, "call_log" - call
        "type": "chat",
        //Sender name
        "senderName": "Ilya",
        //true - outgoing, false - incoming
        "fromMe": true,
        //Author ID of the message, useful for groups
        "author": "17472822486@c.us",
        //send time, unix timestamp
        "time": 1504208593,
        //chat ID
        "chatId": "17472822486@c.us",
        //sequence number of the message in the database
        "messageNumber": 100
    }, {
        //...
    }],
    "ack": [{//message delivered
        "id": "false_17472822486@c.us_DF38E6A25B42CC8CCE57EC40F",
        "queueNumber": 100
        "chatId": "17472822486@c.us",
        "status": "delivered",
    },{//message viewed
        "id": "false_17472822486@c.us_DF38E6A25B42CC8CCE57EC40F",
        "queueNumber": 100
        "chatId": "17472822486@c.us",
        "status": "viewed",
    }, {
        //...
    }],
}

**Comment by edgardmessias** [comment]
A partir do atributo ACK, você pode saber os status da mensagem:
* 1 - Enviado
* 2 - Entregue
* 3 - Lido

Lista de ACK: https://wppconnect-team.github.io/wa-js/enums/whatsapp.enums.ACK.html

**Comment by marcelo386** [comment]
getMessageById está função tem como retornar o json no Console quando também é executado com sucesso, estou, tentando pegar o resultado para ler o json

function SetConsoleMessage(jsName, resultValue) {
    Obj = {
        name: jsName,
        result: '{"result":' + resultValue + '}'
    }
    console.log(JSON.stringify(Obj));
}

Igual está função

SetConsoleMessage("getMessageById", JSON.stringify(resultadoJSON));

desse jeito ficaria mais fácil para ler o retorno da função e pegar o ACK da Mensagem

**Comment by daviladanielc** [comment]
Também estou nessa de gerar o json. pelo o que eu sei, precisa criar a classe de mensagens e passar os dados da função para dentro dessa classe e assim gerar o JSON. 
Eu consigo copiar de outros frameworks que usam o WAPI, mas do wa-js as classes são um pouco diferentes no nome e não consegui fazer.

**Comment by marcelo386** [comment]
Resolvi desta Forma, adicionei no final do arquivo "wppconnect-wa.js" a seguintes funções, desta forma consigo obter o retorno com o componente CEF4 Chromium, terei que fazer o mesmo com as demais funções

function SetConsoleMessage(jsName, resultValue) {
  Obj = {
  name: jsName,
  result: '{"result":' + resultValue + '}'
}
  console.log(JSON.stringify(Obj));
}

window.WAPI.getMessageById2 = async function(UniqueID) {
  const result = await WPP.chat.getMessageById(UniqueID);

  if (result) {     
    try {            	       
		 //console.log("getMessageById:" + JSON.stringify(result));
		 SetConsoleMessage("getMessageById", JSON.stringify(result));
		 
    } catch (err) { 
		console.log(err); 
	  };      
	  
   }  
};
