### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by swetapatel27** [wppconnect-team/wa-js#397]
I am able to set up the environment locally. Can anyone guide me how to and where to write code to send messages using playwright ?

**Comment by hkpanchani** [comment]
It would really help to get me started also, if I can have some wiki's or brief documentation to use..

Right now unable to figure out how to start it..

`npm run launch:local`  did help me start the chromium but than after i couldn't figure out where to keep the custom code. From what file or which place can I call the WPP functions to send messages and all.

I tried to modify the tool/launchLocal.ts but unable to use WPP object over there..

It would be a great help if some can share a small snippet to simply send message from local environment..

Thanks

**Comment by edgardmessias** [comment]
There are a short example in the README file: https://github.com/wppconnect-team/wa-js#playwright

`npm install playwright-chromium@latest @wppconnect/wa-js@latest`

```ts
import * as playwright from 'playwright-chromium';

async function start() {
  const browser = await playwright.chromium.launch();
  const page = browser.newPage();

  await page.goto('https://web.whatsapp.com/');

  await page.addScriptTag({
    path: require.resolve('@wppconnect/wa-js'),
  });

  // Wait WA-JS load
  await page.waitForFunction(() => window.WPP?.isReady);

  // Evaluating code: See https://playwright.dev/docs/evaluating/
  const isAuthenticated: string = await page.evaluate(() =>
    WPP.auth.isAuthenticated()
  );

  // Sending message: See https://playwright.dev/docs/evaluating/
  const sendResult: string = await page.evaluate(
    (to, message) => WPP.chat.sendTextMessage(to, message),
    to,
    message
  );
}

start();
```
