### ISSUE TITLE
Arquivar chat e desarquivar chat

### ISSUE THREAD

**Issue by daviladanielc** [wppconnect-team/wa-js#423]
Não encontrei nos fontes nenhuma possibilidade chamar o arquivamento de chat e também para desarquivar. 
Se possível implementar, deixa o whatsapp mais leve quando tem muitas conversas.

**Comment by edgardmessias** [comment]
Closed by https://github.com/wppconnect-team/wa-js/commit/8e7b0c7ef38aaada2ac752b176b8e9f414d94412
