### ISSUE TITLE
Criar Função WPP.Labels.GetLabels

### ISSUE THREAD

**Issue by DXPRO** [wppconnect-team/wa-js#435]
**// Obter Id e Nomes das Etiquetas criadas no WhatsApp Bussiness**

WPP.Labels.GetLabels = function () {
  var etiquetas = WPP.whatsapp.LabelStore._models.filter((label) => label.colorIndex);
   var names = [];

    for (var i = 0; i < etiquetas.length; i++) {
		if (etiquetas[i])
		{
		  names.push(etiquetas[i].id + "&" + etiquetas[i].name);	
		}
    }
  
  return names;
};

**Comment by edgardmessias** [comment]
Hoje você já consegue ter todas etiquetas chamando `WPP.labels.getAllLabels()`
