### ISSUE TITLE
Título/Descrição do carregamento da thumb ficando com &quot; 

### ISSUE THREAD

**Issue by alonsobruno** [wppconnect-team/wa-js#461]
Boa tarde,

Quando compartilha o link pelo WhatsApp Web cria a thumb perfeito, mas quando o título/descrição tem aspas duplas, fica assim com o &quot; e compartilhando pelo celular fica normal carregando as aspas duplas do titulo/descrição.

Segue o link: https://www.avozdascidades.com.br/noticia/justica-impede-maiara-e-maraisa-de-usar-a-marca-as-patroas

![image](https://user-images.githubusercontent.com/43257659/174817582-f9d7f906-5786-4dc2-a51a-a35e350ea98d.png)

**Comment by edgardmessias** [comment]
Atualizei o server para responder corretamente, agora esperar todos terminarem de atualizar os servers.
