### ISSUE TITLE
Add function to capture all links from chat and groups

### ISSUE THREAD

**Issue by alonsobruno** [wppconnect-team/wa-js#480]
Add function to capture all links from chat and groups

![image](https://user-images.githubusercontent.com/43257659/174806658-78952110-5591-403b-aec6-738a91595cea.png)

**Comment by icleitoncosta** [comment]
Olá, já foi implementado através do último commit.

Att

**Comment by alonsobruno** [comment]
Olá, muito obrigadão! Poderia me dizer qual é nome da função? E foi lançada na ultima versão do wa-js 2.10.1?

**Comment by edgardmessias** [comment]
Ainda não foi lançada, apenas na night

https://wppconnect.io/wa-js/functions/chat.getMessages.html

> Olá, muito obrigadão! Poderia me dizer qual é nome da função? E foi lançada na ultima versão do wa-js 2.10.1?
