### ISSUE TITLE
setPresenceOnline(FALSE) funciona temporariamente

### ISSUE THREAD

**Issue by mvac1991** [wppconnect-team/wa-js#484]
## Description

Eu ativo a função setPresenceOnline passando parâmetro FALSE para que o browser não mostre meu status online 24 horas. Na hora que eu ativo essa função, o status fica OFFLINE (isso está correto). Porém, com o passar dos minutos ou horas (não sei como e nem quando acontece) o status ONLINE volta a aparecer....

Detalhe: Eu uso o WPPConnect, só estou abrindo a issue conforme solicitado no grupo WPPConnect:

![image](https://user-images.githubusercontent.com/35501007/175168198-41a62e21-1284-4f64-bf8a-ce30d21882e2.png)

## Environment

- **WhatsApp version:** 2.2220.8
- **WA-JS version(s):** 2.7.3
- **Browser:** Chrome 
- **OS:** Windows 10 / Linux Centos 7
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. setOnlinePresence(false)

## Your Code

```
client.setOnlinePresence(false);
```

## Additional context / Screenshot

![image](https://user-images.githubusercontent.com/35501007/175168906-6158b5a1-d36e-4734-9d38-9f5646b536dd.png)

**Comment by edgardmessias** [comment]
Lançado novas funções no WA-JS para resolver esse problema, em breve será atualizado no WPPConnect.

WPP.conn.markAvailable e WPP.conn.markUnavailable


https://github.com/wppconnect-team/wa-js/releases/tag/v2.12.0
