### ISSUE TITLE
Status functions

### ISSUE THREAD

**Issue by shirser121** [wppconnect-team/wa-js#500]
When I upload status - sometimes it works and sometimes it's not.
I can't see the status from my phone, and can't delete it - its super important that we can delete the status.
after I upload the status - my phone's WhatsApp starts to crash for a while.

please help!

**Comment by edgardmessias** [comment]
Hello @shirser121 , yes, status (broadcast) it is a mess, everyone is trying to resolve some problems to avoid crash.

So, first of all: If you app start crashing, you can disconect the WhatsApp Web session and try to open the APP again, or wait for 24 hours for status expires.

Second: I don't know why, but status works better with iPhone.

Third: to show the status in a android, follow this steps:
* Connect the whatsapp web (after QRCode)
* Wait for sync
* Using your phone, send some status and wait some seconds
* See it on WhatsApp WEB (optional)
* You can delete this status (optional)
* Now, send some status from WEB
* You will see the post in the phone

**Comment by edgardmessias** [comment]
@shirser121 , could you teste with latest version?

**Comment by ccchai** [comment]
The Status function was fixed at version 2.9.0. However, in version 2.10.0, the problems come back again.
- The Status won't show at Sender's phone, so unable to delete it, and will crash the phone app too.
- If I post several Statuses within minutes, recipients can see the first one only.

WhatsApp version: 2.22.16.75
WA-JS version(s): 2.10.0
Browser: Chrome 104.0.5112.81
OS: Windows 10
MultiDevice (BETA): yes
