### ISSUE TITLE
Categorise Chats

### ISSUE THREAD

**Issue by rhutikcodes** [wppconnect-team/wa-js#525]
Is there any way to categorise chats like only groups, unread messages like in Cooby whatsapp chrome extension?

**Comment by rhutikcodes** [comment]
HI @edgardmessias can you please suggest how this can be possible?

**Comment by edgardmessias** [comment]
Cooby extension is a external service, so, that data are save externally.

You can use the WA-JS to get the WhatsApp data and create by your self a service like that
