### ISSUE TITLE
sendTextMessage with buttons isn't working

### ISSUE THREAD

**Issue by ccchai** [wppconnect-team/wa-js#570]
## Description
When using sendTextMessage / sendFileMessage / sendLocationMessage with buttons, WhatsApp web will display "Could not deliver message" error. If I remove the buttons, the the message will deliver correctly. 

```
WPP.chat.sendTextMessage(
    '[number]@c.us',
    'Test message',
    { buttons: [{ id: 'test', text: 'Click here' }]  } //will deliver correctly if I remove this line
 ); 
```
## Environment

- **WhatsApp version:** Latest version available on Android 
- **WA-JS version(s):** 2.9.0
- **Browser:** Chrome 104.0.5112.81
- **OS:** Windows 10
- **MultiDevice (BETA):** yes

**Comment by edgardmessias** [comment]
Please use the `useTemplateButtons: true` option

**Comment by ccchai** [comment]
The message with buttons can be delivered after adding `useTemplateButtons: true` but with an issue: 

On the sender side, the Android app will display all messages with buttons in a separate chat room with the sender phone number, as if I am sending the messages to myself. However, the messages are displaying correctly on WhatsApp Web at the right chat rooms.

On the recipient side, the messages are showing correctly both on WhatsApp Web and Android app.

 I still have the issue after upgrading the Android app to the latest version. And the same issue happens on WhatsApp Business Android app too.
