### ISSUE TITLE
Not Work Send Buttons and ListMenu WhatsApp: 2.22.16.75

### ISSUE THREAD

**Issue by marcelo386** [wppconnect-team/wa-js#571]
## Environment

- **WhatsApp version:** 2.22.16.75
- **WA-JS version(s):** 2.9.0
- **Browser:** Chrome 101.0.4951.67 / Chromium 101.0.18.0
- **OS:** Windows 10
- **MultiDevice (BETA):** yes

**Comment by CarlaFeldens** [comment]
+1
