### ISSUE TITLE
sendLocationMessage with buttons has problem

### ISSUE THREAD

**Issue by ccchai** [wppconnect-team/wa-js#573]
Prior to WA-JS 2.9.0, sendLocationMessage does not work
In version 2.9.0, sendLocationMessage works both with or without buttons.
In version 2.10.0, sendLocationMessage works without buttons only. If I add buttons to the message, it won't get delivered

## Environment

- **WhatsApp version:** 2.22.16.75
- **WA-JS version(s):** 2.10.0
- **Browser:** Chrome 104.0.5112.81
- **OS:** Windows 10
- **MultiDevice (BETA):** yes

**Comment by edgardmessias** [comment]
@ccchai , could you make the same test with image, document messages?

Probally the problem is the same

**Comment by 3mora2** [comment]
> Both sendTextMessage & sendFileMessage (video & image) with buttons are working. Only sendLocationMessage with buttons are not working.
![image](https://user-images.githubusercontent.com/66757189/182868155-d58e3208-54d4-4cf5-b453-9899e17793fa.png)

 sendFileMessage ( image) with buttons not working with me also.

**Comment by ccchai** [comment]
> sendFileMessage ( image) with buttons not working with me also.

Need to specify `useTemplateButtons: true`

**Comment by 3mora2** [comment]
> > sendFileMessage ( image) with buttons not working with me also.
> 
> Need to specify `useTemplateButtons: true`

thanks, it work now.
what can use to send more button

**Comment by edgardmessias** [comment]
After some tests, the problem is with WhatsApp servers
