### ISSUE TITLE
The Status function isn't working properly in version 2.10.0

### ISSUE THREAD

**Issue by ccchai** [wppconnect-team/wa-js#576]
The Status function was fixed at version 2.9.0. However, in version 2.10.0, the problems come back again.
- The Status won't show at Sender's phone, so unable to delete it, and will crash the phone app too.
- If I post several Statuses within minutes, recipients can see the first one only.

WhatsApp version: 2.22.16.75
WA-JS version(s): 2.10.0
Browser: Chrome 104.0.5112.81
OS: Windows 10
MultiDevice (BETA): yes

_Originally posted by @ccchai in https://github.com/wppconnect-team/wa-js/issues/500#issuecomment-1207338622_

**Comment by icleitoncosta** [comment]
Hello, this bug still occurs in the latest version? I tried to reproduce it, but without success.

**Comment by ccchai** [comment]
I am still using version 2.10.0. Maybe I should latest version when I am free.

**Comment by ccchai** [comment]
It is indeed no problem with version 2.11.1 now.
