### ISSUE TITLE
iOS Not Working Template Button Crash App

### ISSUE THREAD

**Issue by marcelo386** [wppconnect-team/wa-js#577]
## iOS Not Working Template Button Crash App

[iOS List is Working, Android is Working List and Button ]

## Environment

- **WhatsApp version:** 2.22.15.77
- **WA-JS version(s):** 2.10.0
- **OS:** Windows 10
- **MultiDevice (BETA):** yes

**Comment by marcelo386** [comment]
**WhastApp Web**: 2.2228.14

**Comment by edgardmessias** [comment]
To work button on iPhone, you can not use 'phoneNumber' or 'url' buttons, and you must use 'useTemplateButtons: false', to use quick reply buttons instead of template buttons

**Comment by Maker4You** [comment]
> 
buttons don't work on iPhone and MD web
