### ISSUE TITLE
sendFileMessage Not Working Buttons Picture, Documents, Vídeo and Location with useTemplateButtons = undefined

### ISSUE THREAD

**Issue by marcelo386** [wppconnect-team/wa-js#584]
## sendFileMessage Not Working Buttons Picture, Documents, Vídeo and Location with useTemplateButtons = undefined

[Android and iOS not Working]

## Environment

- **WhatsApp version:** 2.22.16.75
- **WA-JS version(s):** 2.10.1
- **OS:** Windows 10
- **MultiDevice (BETA):** yes

**Comment by edgardmessias** [comment]
This is a problem with WhatsApp servers
