### ISSUE TITLE
Get Return when WhatsAppWeb Update Available Button is displayed, and the current version number

### ISSUE THREAD

**Issue by marcelo386** [wppconnect-team/wa-js#652]
**Sua solicitação de recurso está relacionada a um problema? Por favor descreva.**
Quando Exibe está Atualização Disponivel, algumas funções param de funcionar enquanto não é atualizado a versão

**Descreva a solução desejada**
Tendo está função posso forçar reiniciar a Aplicação para já vir atualizado

![image](https://user-images.githubusercontent.com/69150213/190924597-b85d963f-4fd6-4058-88ce-62889e1eaf57.png)

**Comment by edgardmessias** [comment]
Já faz umas versões que existe esse recurso, que é o WPP.conn.needsUpdate()

https://wppconnect.io/wa-js/functions/conn.needsUpdate.html

Também tem a opção de evento.
https://wppconnect.io/wa-js/interfaces/ev.ConnEventTypes.html#conn_needs_update
