### ISSUE TITLE
Could get the group invite link by API?

### ISSUE THREAD

**Issue by zuo305** [wppconnect-team/wa-js#686]
**Is your feature request related to a problem? Please describe.**
Hi, I want to send a group invite link to all my customers, is it possible?

**Describe the solution you'd like**
I hope there is an API that I can call to get the group invite link back by the group name or id.

**Describe alternatives you've considered**
I hope to at least get the group invite link.

**Additional context**
Thank you very much.

**Comment by edgardmessias** [comment]
You can use [WPP.group.getInviteCode](https://wppconnect.io/wa-js/functions/group.getInviteCode.html)
