### ISSUE TITLE
Module isMDBackend was not found with e => e.isMDBackend

### ISSUE THREAD

**Issue by bracketsapps** [wppconnect-team/wa-js#719]
Module isMDBackend was not found with e => e.isMDBackend after initialising the wpconnect.js
after updating web whatsapp

**Comment by edgardmessias** [comment]
This was fixed at [v2.13.4](https://github.com/wppconnect-team/wa-js/releases/tag/v2.13.4)

**Comment by bracketsapps** [comment]
is buttons stopped working ?

**Comment by edgardmessias** [comment]
Facebook is trying to block all kind of buttons, but they are working some time on Android only, the iOS is not working

**Comment by bracketsapps** [comment]
after updating whatsapp only message is sent but buttons are not

`await WAPI.sendButtons('9186XXXXXXXX@c.us', "test message with button", [
        {
            id: "022d8b0c-bfb4-4e72-b468-a96e4dbdf318",
            "text": " 👉👉 Open our site",
            "url":"https://keep.google.com/u/0/"
        },
        {
            id: "57d12727-6ed8-4662-8bc0-f8e666df1596",
            "text": "Call",
            "phoneNumber":"45678"
        },
        {
            id: "a0e3706e-9aef-4d13-b177-f03fb0b46eed",
            "text": "Normal Link"
        }
    ])`
    
    
![image](https://user-images.githubusercontent.com/116897926/198658531-1716be77-e7d9-46ed-977d-f07e6b81bd51.png)
