### ISSUE TITLE
error Using WPP.chat.sendFileMessage

### ISSUE THREAD

**Issue by arunbm123** [wppconnect-team/wa-js#733]
hi

I am getting this error  when using WPP.chat.sendFileMessage
 `VM31:1272 Uncaught (in promise) Module Clock not found with e => {
                var t;
                return null === (t = e.Clock) || void 0 === t ? void 0 : t.globalUnixTime
            }`

Kindly someone give me solution please

**Comment by edgardmessias** [comment]
Hi @arunbm123 , you are using an old version of WA-JS, please upgrate it.

This issue was fixed at [v2.13.1](https://github.com/wppconnect-team/wa-js/releases/tag/v2.13.1)

**Comment by arunbm123** [comment]
Thank u sir

**Comment by arunbm123** [comment]
Thanks Edgard Lorraine Messias
It worked
