### ISSUE TITLE
How to lazy load profile pictures not yet in the store

### ISSUE THREAD

**Issue by clmnin** [wppconnect-team/wa-js#735]
I can get the profile picture URL using
```js
const url = await WPP.contact.getProfilePicture('[number]@c.us');
```
(as per the doc [getProfilePictureUrl](https://wppconnect.io/wa-js/functions/contact.getProfilePictureUrl.html))

But if my WhatsApp web has not downloaded the profile picture then using the fuction will return `undefined`. 

How do I ask WhatsApp to load the profile picture (and save it to the store) for a chat?

**Comment by edgardmessias** [comment]
I did a lot of tests and this is a bug on WhatsApp servers, that send the wrong picture URL.

Currently, the methods always return the latest URL
