### ISSUE TITLE
BUG: Click replied message, I receive "Não foi possível encontrar a mensagem"  

### ISSUE THREAD

**Issue by tonbotfy** [wppconnect-team/wa-js#737]
## Description
When the bot sends the message, the recipient can see which message was replied to, but cannot go to it.
However, if I look at the bot's whatsapp and click on the answers, it can see all of them normally.

## Environment

- **WhatsApp version:** **_2.2234.13_**
- **WA-JS version(s):** **_2.14.1_**
- **OS:** **_Windows 10_**

## Steps to Reproduce
Receive any message and use the sendText() method with quotedMessage.

## Your Code
this.client.onAnyMessage((message) => this.onNewMessage(message))

onNewMessage = async (message: Message) => {
  await this.client.sendText(message.chatId, 'replyed message', {
          createChat: true,
          quotedMsg: message.id,
          waitForAck: true,
  });
}

## Additional context / Screenshot
![image](https://user-images.githubusercontent.com/106827778/200179406-54611fcf-efb4-420f-9e58-7263a4be1a5a.png)

**Comment by tonbotfy** [comment]
@edgardmessias 
Any answer?

**Comment by edgardmessias** [comment]
Fixed at [v2.15.2](https://github.com/wppconnect-team/wa-js/releases/tag/v2.15.2)
