### ISSUE TITLE
getMessageACK function

### ISSUE THREAD

**Issue by nadomendes** [wppconnect-team/wa-js#740]
Quando possível gostaria da inserção da rota para getMessageACK

**Comment by edgardmessias** [comment]
Primeiro será necessário criar essa função na LIB, e depois criar a rota no server.

Nesse primeiro momento estou trazendo mais algumas funções no WA-JS para depois mexer na LIB.

**Comment by edgardmessias** [comment]
Caso quiser, você pode abrir issues nos respectivos projetos solicitando o recurso
