### ISSUE TITLE
WPP.contact.queryExists doesnt work

### ISSUE THREAD

**Issue by cherichitoun** [wppconnect-team/wa-js#758]
Using latest version of wa-js,
WPP.contact.queryExists - returning null if user exists or not.

**Comment by cherichitoun** [comment]
Fixed with using phone format without country code
For kz - 776155... not **7**776155...

**Comment by cherichitoun** [comment]
Yesterday full number format worked

**Comment by sergey-chechaev** [comment]
> Yesterday full number format without exit code worked

Yes it works for me too

**Comment by edgardmessias** [comment]
Today I will release a new version of WA-JS with this fix

**Comment by Zer0bytte** [comment]
> Today I will release a new version of WA-JS with this fix

queryExists doesnt work with exitcode too, how to fix it?

**Comment by edgardmessias** [comment]
I need some numbers to test the result, could someone send it to my test number? https://wa.me/5521977218347
