### ISSUE TITLE
WPP.contact.queryExists() doesn't work for WhatsApp group ID

### ISSUE THREAD

**Issue by limshengli** [wppconnect-team/wa-js#778]
## Description

When using `WPP.contact.queryExists()` with valid WhatsApp group ID (@g.us), it'll returned null.

## Environment

- **WhatsApp version:** 2.2245.9
- **WA-JS version(s):** 2.16.2
- **Browser:** Microsoft Edge Chromium 107.0.1418.56
- **OS:** Windows 11
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. call WPP.contact.queryExists() with WhatsApp Group ID

**Comment by edgardmessias** [comment]
And this is not Wrong, group are always a chat.

You can use WPP.chat.get or WPP.group.ensureGroup to check group exists.

https://wppconnect.io/wa-js/functions/group.ensureGroup.html
