### ISSUE TITLE
Como eu uso essa função em JavaScript?

### ISSUE THREAD

**Issue by higormachado3** [wppconnect-team/wa-js#817]
export async function clear(chatId: string | Wid, keepStarred = true) {
  const wid = assertWid(chatId);

  const chat = assertGetChat(wid);

  sendClear(chat, keepStarred);

  let status = 200;

  if (chat.promises.sendClear) {
    const result = await chat.promises.sendClear.catch(() => ({
      status: 500,
    }));
    status = result.status || status;
  }

  return {
    wid,
    status,
    keepStarred,
  };

**Comment by edgardmessias** [comment]
Chamando no console assim: ``WPP.chat.clear('id-do-chat@c.us', false)`

https://wppconnect.io/wa-js/functions/chat.clear.html
