### ISSUE TITLE
Existe uma forma de apagar a mensagem que está sendo criada?

### ISSUE THREAD

**Issue by higormachado3** [wppconnect-team/wa-js#818]
![imagem_2022-12-16_163038405](https://user-images.githubusercontent.com/97197707/208174595-eb547e0b-c5ee-40fc-858c-10ad1a92dc40.png)

Estou fazendo outra rota para o envio das mensagens pois quero colocar uma assinatura nela e estou tendo essa barreira de não conseguir apagar a mensagem  já enviada do campo de digitação, sempre que eu  deleto o campo pelo javascript ou defino como  { innerHtml = ' ' } o whatsapp regenera o campo com a mensagem;

**Comment by boinaweb** [comment]
Delete text via keyboard using nodejs

**Comment by edgardmessias** [comment]
@higormachado3 , depois vou ver a possibilidade de exportar uma função para pegar e apagar esse campo

**Comment by higormachado3** [comment]
![imagem_2022-12-23_150739779](https://user-images.githubusercontent.com/97197707/209387685-72391b07-6963-4969-a802-70a41444fa5d.png)

Certo, seria legal ter algo do tipo, principalmente para fazer assinatura como o exemplo mostrado acima eu consegui fazer mais tive que alterar  bastante parte do código base do whatsapp que não fica legal pois gera bastante bugs

**Comment by icleitoncosta** [comment]
Hi, created function by https://github.com/wppconnect-team/wa-js/commit/ebb247ee1bb013167c2c9e720a0ca642ee70f997
