### ISSUE TITLE
Envio de link através de mensagem de texto sem adicionar imagem de preview.

### ISSUE THREAD

**Issue by GMUNDI** [wppconnect-team/wa-js#850]
## Description

Ao enviar mensagem com link, não é gerado a imagem de preview com o link.
A solução tem sido desconectar e reconectar (usando close) ou gerando novo token e reconectando.
Algumas vezes é necessário fazer este procedimento mais de uma vez.
E mesmo depois de voltar a funcionar, sem o cliente desconectar e reconectar ou reiniciar o server, acontece de novamente apresentar o problema.

## Environment

- wpp-connect 1.7.2
- Ubuntu 20.04
- Node version: 16.18.1

**Comment by edgardmessias** [comment]
Pelos testes que tenho feito, o que pode estar acontecendo mais é quando o site que se está utilizando tem proteção contra crawler, que acaba não respondendo.

A solução atual utiliza servidores próprios, e tem vários que ele tenta antes de não conseguir gerar o preview.

A nova versão do WhatsApp WEB está trazendo de volta o recurso de link preview, por isso vou fechar essa issue.
