### ISSUE TITLE
Como enviar uma mensagem com um ID criado?

### ISSUE THREAD

**Issue by higormachado3** [wppconnect-team/wa-js#855]
Preciso enviar uma mensagem com um ID já definido para que eu possa fazer uma busca posteriormente e definir uma ação no meu sistema, existe alguma possibilidade de estar fazendo isso?

**Comment by icleitoncosta** [comment]
Olá Higor, sim. É só passar o parâmetro messageId.
Exemplo:

```
const msgId = WPP.chat.generateMessageID('numero@c.us'); 
await WPP.chat.sendTextMessage('numero@c.us', 'Hello World', { messageId: msgId }); 

await WPP.chat.getMessageById(msgId);
```
Esse exemplo irá imprimir a mensagem consultada pelo ID.

Repare que eu utilizei uma própria função do projeto para geração do ID, em versões anteriores poderia se passar qualquer tipo de string ou numero que aceitava, porém, nas versões mais recentes, é obrigatório utilizar uma ID similar, pois o WhatsApp está utilizando o msgId, para pegar alguns dados na última versão.
