### ISSUE TITLE
How to set unread messages on the left pane in chrome extension?

### ISSUE THREAD

**Issue by rahulbansal16** [wppconnect-team/wa-js#869]
I want to add functionality on Whatsapp web to show all unread chats similar to Gmail. The functionality will be added as a part of the chrome extension that runs on WhatsApp web.

Here is a rough path that I have in my mind.
1. Inject an Unread Button.  Add an unread button in the body of the content script using javascript.
2. Add a handler to fetch all unread messages. I can use the `WPP.chat.list();` to read all the chats and put a filter to search for unread.
3. Set the unread messages on the left pane.

I am not able to understand. How to set the messages on the left pane? Does anyone have any idea about doing that?

**Comment by icleitoncosta** [comment]
I'm one of those who program here at WAJS, I know it's possible, but I don't even know where to start, I advise you to look in the JS files with wa-source, and go looking for the line you want to change, at least wa-source will format for you. Remembering that this feature should be launched soon by WhatsApp.

**Comment by edgardmessias** [comment]
@rahulbansal16 , you probably need manipulate the `shouldAppearInList` of each chat, but this attribute is derived

**Comment by rahulbansal16** [comment]
@edgardmessias thanks it works. How is `shouldAppearInList` re-rendering the UI to update the chat list? How's react re-rendering getting triggered with the variable?

**Comment by edgardmessias** [comment]
@rahulbansal16 Each model and collection has a event that trigger the change for "useEffect"

**Comment by jeffsmor** [comment]
> I want to add functionality on Whatsapp web to show all unread chats similar to Gmail. The functionality will be added as a part of the chrome extension that runs on WhatsApp web.
> 
> Here is a rough path that I have in my mind.
> 
> 1. Inject an Unread Button.  Add an unread button in the body of the content script using javascript.
> 2. Add a handler to fetch all unread messages. I can use the `WPP.chat.list();` to read all the chats and put a filter to search for unread.
> 3. Set the unread messages on the left pane.
> 
> I am not able to understand. How to set the messages on the left pane? Does anyone have any idea about doing that?

Hi man, could you share your extension as boilerplate? I'm trying to make wa-js works inside a chrome extension, but I haven't got success yet.
