### ISSUE TITLE
How to track incoming messages

### ISSUE THREAD

**Issue by TrueDoleron** [wppconnect-team/wa-js#899]
I read documentation, but found only 

```
WPP.on('chat.new_message', (msg) => {
});
```
And this not working when people text me on whatsapp.
I wan't track every messages

**Comment by edgardmessias** [comment]
Sorry, I don't get what you want exactly

**Comment by TrueDoleron** [comment]
> Sorry, I don't get what you want exactly

I want track incoming messages from chat

**Comment by edgardmessias** [comment]
This is the purpose of this event, this event will trigger for each new message

**Comment by TrueDoleron** [comment]
> This is the purpose of this event, this event will trigger for each new message

Sorry, I worked with old version(
Close

**Comment by jpliraa** [comment]
@TrueDoleron what version do you use?, i am really tired fron trying without result, using 3.2.4 and 3.2.6, but events dont work, function are working propertly
