### ISSUE TITLE
How to send document with buttons?

### ISSUE THREAD

**Issue by sandro-salles** [wppconnect-team/wa-js#947]
All file messages (image and video) are working correctly when sent with buttons. Except for document files. When i send a pdf file with buttons, the buttons part are not appearing anywhere (IOs, android, web…)

Do you think it’s a limitation of whatsapp itself or maybe a property that should be set on the message?

**Comment by Saifallak** [comment]
> it is not possible to send buttons through whatsapp, due to recent updates of whatsapp itself.

oh wait? they removed this feature completely?

**Comment by edgardmessias** [comment]
@sandro-salles , you can look for some example here: https://wppconnect.io/wa-js/functions/chat.sendFileMessage.html

And for @Saifallak too: The is a limitation of WhatsApp app at moment, there are nothing to do to work around this problem.
