### ISSUE TITLE
WPP.chat.downloadMedia not working

### ISSUE THREAD

**Issue by Gethin0321** [wppconnect-team/wa-js#956]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **WhatsApp version:** 2.2308.7
- **WA-JS version(s):**2.20.2
- **Browser:**  Chromium 982053
- **OS:** ubuntu 16.04
- **MultiDevice (BETA):** yes
## Steps to Reproduce

1. 
```
const message_id = "false_status@broadcast_23775B803F6384BCB135A11614984476_91xxxxxxxx@c.us";
const result = await client.pupPage.evaluate(
                        (message_id) => WPP.chat.downloadMedia(message_id),
                        message_id,
                    );
                    console.log(result);
```

## Log Output
always got : {}

**Comment by icleitoncosta** [comment]
This is possibly an error in your code, it could be in the Puppeteer configuration.

You can call the functions directly through the browser console and test them.
In a simple way: open the project through VSCode -> Run -> Start Debugging, it will open an instance of chrome, you can directly call the function in the console.

Something like:
```
await WPP.chat.downloadMedia('messageId');
```
You can see that it continues to function normally.

Well, did you do that and did it work? We have to check your code, but there is a problem in Puppeteer, an issue already known and discussed by them, which brings undefined returns, in the WppConnect LIB it is treated like this: JSON.parse(JSON.stringify(result));

It's something you can try, here's a reference:
https://github.com/wppconnect-team/wppconnect/blob/master/src/api/layers/sender.layer.ts
(Line 125 ex )

**Comment by edgardmessias** [comment]
WPP.chat.downloadMedia returna Blob content, that is a non serializable content, but you can do this: `WPP.chat.downloadMedia('true_[number]@c.us_ABCDEF').then(WPP.util.blobToBase64)` to get a base64Content
