### ISSUE TITLE
WPP.chat.getMessageById and WPP.chat.getMessages  always return undefined

### ISSUE THREAD

**Issue by Gethin0321** [wppconnect-team/wa-js#957]
## Description

[Description of the bug, When Issue Happens]

## Environment

- **WhatsApp version:** 2.2308.7
- **WA-JS version(s):** 2.20.2
- **Browser:** Chromium 982053
- **OS:** ubuntu 16.04
- **MultiDevice (BETA):** yes

1,WPP.chat.getMessages
```
let chat_id = '9195xxxxxxx@c.us';
   const result = await client.pupPage.evaluate(
                        (chat_id) => WPP.chat.getMessages(chat_id,{
                            count:20,
                        }),
                        chat_id,
                    );
console.log(result);
```
got undefined

2,WPP.chat.getMessageById
```
 let message_id = 'false_91xxxxxxx@c.us_3EB052F0692148177865';
  const result = await client.pupPage.evaluate(
                        (message_id) => WPP.chat.getMessageById(message_id),
                        message_id,
                    );

console.log(result);
```
got undefined

**Comment by icleitoncosta** [comment]
This is possibly an error in your code, it could be in the Puppeteer configuration.

You can call the functions directly through the browser console and test them.
In a simple way: open the project through VSCode -> Run -> Start Debugging, it will open an instance of chrome, you can directly call the function in the console.

Something like:
```
await WPP.chat.getMessageById('messageId');
```
You can see that it continues to function normally.

Well, did you do that and did it work? We have to check your code, but there is a problem in Puppeteer, an issue already known and discussed by them, which brings undefined returns, in the WppConnect LIB it is treated like this: JSON.parse(JSON.stringify(result));

It's something you can try, here's a reference:
https://github.com/wppconnect-team/wppconnect/blob/master/src/api/layers/sender.layer.ts
