### ISSUE TITLE
Aprimorar o mentionedList

### ISSUE THREAD

**Issue by DXPRO** [wppconnect-team/wa-js#962]
Ao utilizar este recurso no WA-JS fica claro o que precisamos fazer, passar como pararametro os Ids desejados!

**Mas uma sugestão de melhoria seria:**
_1 - definir uma opção True ou False para este recurso, com alguns filtros, caso o usuário deixe como True, mas não informe os Ids, que o recurso pudesse capitar os ids automaticamente dos chats definidos como Grupos, assim não haveria nenhuma dificuldade das pessoas para testar o recurso por não saber as vezes como pegar esses IDs!_

_2 - Esse recurso é muito util para grupos onde somos administradores, porém pode se tornar uma dor de cabeça se usado de forma errada, logo, seria muito util usar um outro tipo de filtro neste recurso mentionedList, como por exemplo, um filtro para não marcar usuários administradores e também usuários que estão bloqueados no chat!_

_**Eu tenho feito algumas gambiarras para chegar a esse resultado, como o exemplo abaixo:**_

**Criei essa função que verifica se um determinado ID não é um admin ou se não esta bloqueado**

```
window.WPP.NoAdminNoBlock = async function (chatid) {
	const contatos = await WPP.group.getParticipants(chatid);
	const NoAdmin = contatos.filter(c => (c.isAdmin)==false).filter(b => (b.contact.isContactBlocked) == false);
	let names = [];
   for (let i = 0; i < NoAdmin.length; i++) {
   if (NoAdmin[i]) {
      names.push(NoAdmin[i].id._serialized);
    }
  }
  return names;
};
```
Dessa forma, caso eu não seja o administrador de um grupo, não irei ficar marcando os admins para não ser removido, ou marcando pessoas que eu bloqueiei por não desejarem ser marcadas!

Sei que já tenho obtido o resultado esperado, mas se for possivel aprimorar para que essas configurações sejam apenas paramentros a serem definidos, ficaria bem melhor! Obrigado desde já por tudo!

**Comment by robertoitec** [comment]
Olá, =) 
Como faz para mencionar os selecionados de forma oculta?

**Comment by edgardmessias** [comment]
Desculpe, mas esse tipo de recurso não seria bom de colocar, o objetivo maior do WA-JS é extrair funções para poderem serem utilizadas, e com os métodos atuais, você consegue fazer esse tipo de verificação, como alternativa, podemos melhorar a documentação para alguns casos, e colocar até no exemplo.
