### ISSUE TITLE
How to get correct number for brazil  

### ISSUE THREAD

**Issue by bracketsApps007** [wppconnect-team/wa-js#968]
In Brazil, the number pattern is like this: 55759817021XX, but the system asks you to put the number like 5575817021XX, but I noticed that sometimes there are users who do not receive it without the 9 before the number, others just receive with 9. I don’t know if it makes a difference if the recipient number is business or not.

**Comment by edgardmessias** [comment]
Look the `WPP.contact.queryExists` function: https://wppconnect.io/wa-js/functions/contact.queryExists.html
