### ISSUE TITLE
Android not receiving templateButtons & List Message

### ISSUE THREAD

**Issue by luidigo** [wppconnect-team/wa-js#977]
## Description

A mensagem não aparece no Android

## Environment

WhatsApp version: 2.2305.7
WA-JS version(s): 2.22.2
Browser: Chrome 110.0.5481.180
OS: Windows 10
MultiDevice (BETA): yes

## Steps to Reproduce

Send templateButtons message or list message to number that use iOS

**Comment by edgardmessias** [comment]
This is a known issue, but there's nothing that we can do about it.

**Comment by bracketsApps007** [comment]
Yes, since last couple of days lots of android devices are not able to receive buttons.

**Comment by ccchai** [comment]
I am facing problems with Android devices not receiving templateButtons message too.

**Comment by raajrush** [comment]
https://github.com/adiwajshing/Baileys/pull/2674

**Comment by andredealmei** [comment]
Baseado na pr do [Baileys](https://github.com/adiwajshing/Baileys) que já possui algumas correções, não seria possível já começar os trabalhos por aqui ?

**Comment by andredealmei** [comment]
> Mas é claro @andredealmei , pode enviar o seu PR que analisamos e fazemos o merge sim.
> 
> > Baseado na pr do [Baileys](https://github.com/adiwajshing/Baileys) que já possui algumas correções, não seria possível já começar os trabalhos por aqui ?

Bela abordagem hein para uma duvida, considerando voce um membro do time, se eu tivesse esse tipo de conhecimento especifico com certeza eu já teria feito. Agora esse tipo de comentário, nenhuma comunidade merece.

**Comment by edgardmessias** [comment]
@andredealmei , desculpe se entendi errado o seu comentário, mas faz parte.

Sobre os trabalhos, eu já estava testando há algum tempo isso, mas nada 100% para liberar, e como você pode ver, mesmo no Baileys, tem tido problemas.

Sobre comunidade, eu tenho tentado montar uma desde o começo, mas só tenho recebido cobrança e pouca gratificação, já pensei em parar com isso diversas vezes, mas em respeito aos que realmente merecem eu continuo esse trabalho.

O WPPConnect não é minha fonte de renda e nunca vai ser, pois é uma coisa que quero deixar livre, mas eu tenho trabalho, família e etc.

**Comment by andredealmei** [comment]
> @andredealmei , desculpe se entendi errado o seu comentário, mas faz parte.
> 
> Sobre os trabalhos, eu já estava testando há algum tempo isso, mas nada 100% para liberar, e como você pode ver, mesmo no Baileys, tem tido problemas.
> 
> Sobre comunidade, eu tenho tentado montar uma desde o começo, mas só tenho recebido cobrança e pouca gratificação, já pensei em parar com isso diversas vezes, mas em respeito aos que realmente merecem eu continuo esse trabalho.
> 
> O WPPConnect não é minha fonte de renda e nunca vai ser, pois é uma coisa que quero deixar livre, mas eu tenho trabalho, família e etc.

Nada cara, compreendo como trabalhar com projetos abertos e gratuitos é algo ingrato

**Comment by Saifallak** [comment]
Semi Fixed By https://github.com/wppconnect-team/wa-js/commit/6ec2d93b299d70db911e53cfe740d4ee494c37cc

**Comment by bracketsApps007** [comment]
> Semi Fixed By [6ec2d93](https://github.com/wppconnect-team/wa-js/commit/6ec2d93b299d70db911e53cfe740d4ee494c37cc)

Not working (target and source both have normal whatsapp account)

`await WPP.chat.sendTextMessage('1864279----@c.us','Testing URL/Phone Button', {
  useTemplateButtons: true,
  buttons: [
    {
        url: "https://google.com/",
        text: "Google Site"
    },
    {
        phoneNumber: "+628888888888",
        text: "Call me"
    },
    {
        id: "your custom id 1",
        text: "Some text"
    },

  ],
  title: "Title text",
  footer: "Footer text"
})`

**Comment by Saifallak** [comment]
Templates not working yet,
Only Buttons and List Buttons.
And from normal whatsapps only.

**Comment by raajrush** [comment]
How to send Only Buttons and List Buttons.

**Comment by Saifallak** [comment]
useTemplateButtons: false

**Comment by raajrush** [comment]
Where can I get full snippet

**Comment by Saifallak** [comment]
> Where can I get full snippet

https://wppconnect.io/wa-js/

**Comment by luidigo** [comment]
Aqui segue sem funcionar. Enviando de um iphone WA "normal" para um Android normal e para um business, o botão não chega.

`await WPP.chat.sendTextMessage('55xxxxxxxxxxx@c.us', 'mensagem com botoes', {"useTemplateButtons":false,"buttons":[{"id":"1","text":"1 - Botao 1?"},{"id":"2","text":"2 - Botao 2"},{"id":"3","text":"3 - Botao 3"}],"title":null,"footer":null})`

WA-JS v2.23.0
WA web v2.2314.7

**Comment by renat473** [comment]
@luidigo , aguarde a atualização.

Por enquanto não esta funcionando para bussines.

**Comment by raajrush** [comment]
> Aqui segue sem funcionar. Enviando de um iphone WA "normal" para um Android normal e para um business, o botão não chega.
> 
> `await WPP.chat.sendTextMessage('55xxxxxxxxxxx@c.us', 'mensagem com botoes', {"useTemplateButtons":false,"buttons":[{"id":"1","text":"1 - Botao 1?"},{"id":"2","text":"2 - Botao 2"},{"id":"3","text":"3 - Botao 3"}],"title":null,"footer":null})`
> 
> WA-JS v2.23.0 WA web v2.2314.7

![IMG-20230403-WA0000](https://user-images.githubusercontent.com/54767677/229410596-22fcebf8-8ecf-4ea7-9f5d-a5b5b359e44f.jpg)
